#! /bin/sh -x
set -e

SDK_ROOT=../../..
ANDROID_SDK=$SDK_ROOT/Externals/android-sdk/
pushd $ANDROID_SDK/platform-tools > /dev/null
ADB=`pwd`/adb
popd > /dev/null

case $1 in
  debug) suffix=DEBUG;;
  checked) suffix=CHECKED;;
  profile) suffix=PROFILE;;
  release) suffix=;;
  *) echo Must have a config!; exit 1;;
esac

snippetName=$2

if [ -z $snippetName ]; then
	echo Must have a snippet name!;	
	exit 1;
fi

executable=Snippet$snippetName$suffix

echo Executable is $executable

# wait until device is ready
$ADB  wait-for-device

# run
$ADB  shell "cd data/tmp; ./$executable"
