PxJointLimitPyramid Class Reference
PxJointLimitPyramid Class Reference
Extensions
Describes a pyramidal joint limit.
#include <PxJointLimit.h>
Public Member Functions
PxJointLimitPyramid (PxReal yLimitAngleMin, PxReal yLimitAngleMax, PxReal zLimitAngleMin, PxReal zLimitAngleMax, PxReal contactDist=-1.0f)
Construct a pyramid hard limit.
PxJointLimitPyramid (PxReal yLimitAngleMin, PxReal yLimitAngleMax, PxReal zLimitAngleMin, PxReal zLimitAngleMax, const PxSpring &spring)
Construct a pyramid soft limit.
PX_INLINE bool isValid () const
Returns true if the limit is valid.
Public Member Functions inherited from PxJointLimitParameters
PxJointLimitParameters ()
PxJointLimitParameters (const PxJointLimitParameters &p)
PX_INLINE bool isValid () const
Returns true if the current settings are valid.
PX_INLINE bool isSoft () const
Public Attributes
PxReal yAngleMin
the minimum angle from the Y axis of the constraint frame.
PxReal yAngleMax
the maximum angle from the Y axis of the constraint frame.
PxReal zAngleMin
the minimum angle from the Z-axis of the constraint frame.
PxReal zAngleMax
the maximum angle from the Z-axis of the constraint frame.
Public Attributes inherited from PxJointLimitParameters
PxReal restitution
Controls the amount of bounce when the joint hits a limit.
PxReal bounceThreshold
PxReal stiffness
if greater than zero, the limit is soft, i.e. a spring pulls the joint back to the limit
PxReal damping
if spring is greater than zero, this is the damping of the limit spring
PxReal contactDistance
the distance inside the limit value at which the limit will be considered to be active by the solver. As this value is made larger, the limit becomes active more quickly. It thus becomes less likely to violate the extents of the limit, but more expensive.
Additional Inherited Members
Protected Member Functions inherited from PxJointLimitParameters
~PxJointLimitParameters ()
Detailed Description
Describes a pyramidal joint limit.
See also
PxD6Joint
Constructor & Destructor Documentation
PxJointLimitPyramid() [1/2]
PxJointLimitPyramid::PxJointLimitPyramid (PxReal yLimitAngleMin, PxReal yLimitAngleMax, PxReal zLimitAngleMin, PxReal zLimitAngleMax, PxReal contactDist = -1.0f) inline
Construct a pyramid hard limit.
Parameters
[in] yLimitAngleMin The minimum limit angle from the Y-axis of the constraint frame
[in] yLimitAngleMax The maximum limit angle from the Y-axis of the constraint frame
[in] zLimitAngleMin The minimum limit angle from the Z-axis of the constraint frame
[in] zLimitAngleMax The maximum limit angle from the Z-axis of the constraint frame
[in] contactDist The distance from the limit at which it becomes active. Default is the lesser of 0.1 radians, and 0.49 * the lower of the limit angles
See also
PxJointLimitParameters
References PxJointLimitParameters::contactDistance, and PxMin().
PxJointLimitPyramid() [2/2]
PxJointLimitPyramid::PxJointLimitPyramid (PxReal yLimitAngleMin, PxReal yLimitAngleMax, PxReal zLimitAngleMin, PxReal zLimitAngleMax, const PxSpring & spring) inline
Construct a pyramid soft limit.
Parameters
[in] yLimitAngleMin The minimum limit angle from the Y-axis of the constraint frame
[in] yLimitAngleMax The maximum limit angle from the Y-axis of the constraint frame
[in] zLimitAngleMin The minimum limit angle from the Z-axis of the constraint frame
[in] zLimitAngleMax The maximum limit angle from the Z-axis of the constraint frame
[in] spring The stiffness and damping of the limit spring
See also
PxJointLimitParameters
References damping, spring, and stiffness.
Member Function Documentation
isValid()
PX_INLINE bool PxJointLimitPyramid::isValid () const inline
Returns true if the limit is valid.
Returns
true if the current settings are valid
References PxJointLimitParameters::isValid(), PxIsFinite(), and PxPi.
Member Data Documentation
yAngleMax
PxReal PxJointLimitPyramid::yAngleMax
the maximum angle from the Y axis of the constraint frame.
Unit: Angular: Radians Range: Angular: (-PI,PI)
Default: PI/2
yAngleMin
PxReal PxJointLimitPyramid::yAngleMin
the minimum angle from the Y axis of the constraint frame.
Unit: Angular: Radians Range: Angular: (-PI,PI)
Default: -PI/2
zAngleMax
PxReal PxJointLimitPyramid::zAngleMax
the maximum angle from the Z-axis of the constraint frame.
Unit: Angular: Radians Range: Angular: (-PI,PI)
Default: PI/2
zAngleMin
PxReal PxJointLimitPyramid::zAngleMin
the minimum angle from the Z-axis of the constraint frame.
Unit: Angular: Radians Range: Angular: (-PI,PI)
Default: -PI/2
The documentation for this class was generated from the following file:
PxJointLimit.h