physx::Gu::ContactBuffer Class Reference
physx::Gu::ContactBuffer Class Reference
#include <GuContactBuffer.h>
Public Member Functions
PX_FORCE_INLINE void reset ()
PX_FORCE_INLINE bool contact (const PxVec3 &worldPoint, const PxVec3 &worldNormalIn, PxReal separation, PxU32 faceIndex1=PXC_CONTACT_NO_FACE_INDEX)
PX_FORCE_INLINE bool contact (const PxVec3 &worldPoint, const PxVec3 &worldNormalIn, PxReal separation, PxU16 internalUsage, PxU32 faceIndex1=PXC_CONTACT_NO_FACE_INDEX)
PX_FORCE_INLINE bool contact (const Gu::ContactPoint &pt)
PX_FORCE_INLINE Gu::ContactPoint * contact ()
Public Attributes
Gu::ContactPoint contacts [MAX_CONTACTS]
PxU32 count
PxU32 pad
Static Public Attributes
static const PxU32 MAX_CONTACTS = 64
Member Function Documentation
contact() [1/4]
PX_FORCE_INLINE bool physx::Gu::ContactBuffer::contact (const PxVec3 & worldPoint, const PxVec3 & worldNormalIn, PxReal separation, PxU32 faceIndex1 = PXC_CONTACT_NO_FACE_INDEX) inline
References contacts, count, physx::Gu::ContactPoint::internalFaceIndex1, PxVec3::magnitude(), MAX_CONTACTS, PX_ASSERT, PxAbs(), physx::Gu::ContactPoint::separation, and separation.
contact() [2/4]
PX_FORCE_INLINE bool physx::Gu::ContactBuffer::contact (const PxVec3 & worldPoint, const PxVec3 & worldNormalIn, PxReal separation, PxU16 internalUsage, PxU32 faceIndex1 = PXC_CONTACT_NO_FACE_INDEX) inline
References contacts, count, physx::Gu::ContactPoint::forInternalUse, physx::Gu::ContactPoint::internalFaceIndex1, PxVec3::magnitude(), MAX_CONTACTS, PX_ASSERT, PxAbs(), physx::Gu::ContactPoint::separation, and separation.
contact() [3/4]
PX_FORCE_INLINE bool physx::Gu::ContactBuffer::contact (const Gu::ContactPoint & pt) inline
References contacts, count, and MAX_CONTACTS.
contact() [4/4]
PX_FORCE_INLINE Gu::ContactPoint* physx::Gu::ContactBuffer::contact () inline
References contacts, count, and MAX_CONTACTS.
reset()
PX_FORCE_INLINE void physx::Gu::ContactBuffer::reset () inline
References count.
Member Data Documentation
contacts
Gu::ContactPoint physx::Gu::ContactBuffer::contacts[MAX_CONTACTS]
Referenced by contact().
count
PxU32 physx::Gu::ContactBuffer::count
Referenced by contact(), and reset().
MAX_CONTACTS
const PxU32 physx::Gu::ContactBuffer::MAX_CONTACTS = 64 static
Referenced by contact().
pad
PxU32 physx::Gu::ContactBuffer::pad
The documentation for this class was generated from the following file:
GuContactBuffer.h