physx::intrinsics Namespace Reference
physx::intrinsics Namespace Reference
Functions
PX_CUDA_CALLABLE PX_FORCE_INLINE float abs (float a)
platform-specific absolute value
PX_CUDA_CALLABLE PX_FORCE_INLINE float fsel (float a, float b, float c)
platform-specific select float
PX_CUDA_CALLABLE PX_FORCE_INLINE float sign (float a)
platform-specific sign
PX_CUDA_CALLABLE PX_FORCE_INLINE float recip (float a)
platform-specific reciprocal
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipFast (float a)
platform-specific reciprocal estimate
PX_CUDA_CALLABLE PX_FORCE_INLINE float sqrt (float a)
platform-specific square root
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrt (float a)
platform-specific reciprocal square root
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrtFast (float a)
PX_CUDA_CALLABLE PX_FORCE_INLINE float sin (float a)
platform-specific sine
PX_CUDA_CALLABLE PX_FORCE_INLINE float cos (float a)
platform-specific cosine
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMin (float a, float b)
platform-specific minimum
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMax (float a, float b)
platform-specific maximum
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (float a)
platform-specific finiteness check (not INF or NAN)
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (double a)
platform-specific finiteness check (not INF or NAN)
PX_FORCE_INLINE void * memZero (void *dest, uint32_t count)
PX_FORCE_INLINE void * memSet (void *dest, int32_t c, uint32_t count)
PX_FORCE_INLINE void * memCopy (void *dest, const void *src, uint32_t count)
PX_FORCE_INLINE void * memMove (void *dest, const void *src, uint32_t count)
PX_FORCE_INLINE void memZero128 (void *dest, uint32_t offset=0)
Function Documentation
abs()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::abs (float a)
platform-specific absolute value
Referenced by PxAbs().
cos()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::cos (float a)
platform-specific cosine
Referenced by PxCos().
fsel()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::fsel (float a, float b, float c)
platform-specific select float
isFinite() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool physx::intrinsics::isFinite (float a)
platform-specific finiteness check (not INF or NAN)
Referenced by PxTransform::getInverse(), PxVec2::isNormalized(), PxVec3::isNormalized(), PxVec4::isNormalized(), PxQuat::isSane(), PxTransform::isSane(), PxQuat::isUnit(), PxControllerDesc::isValid(), PxIsFinite(), PxTransform::rotate(), PxTransform::rotateInv(), PxTransform::transform(), and PxTransform::transformInv().
isFinite() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool physx::intrinsics::isFinite (double a)
platform-specific finiteness check (not INF or NAN)
memCopy()
PX_FORCE_INLINE void* physx::intrinsics::memCopy (void * dest, const void * src, uint32_t count)
Copies count bytes from src to dst. User memMove if regions overlap.
Referenced by PxMemCopy().
memMove()
PX_FORCE_INLINE void* physx::intrinsics::memMove (void * dest, const void * src, uint32_t count)
Copies count bytes from src to dst. Supports overlapping regions.
Referenced by PxMemMove().
memSet()
PX_FORCE_INLINE void* physx::intrinsics::memSet (void * dest, int32_t c, uint32_t count)
Sets count bytes starting at dst to c.
Referenced by memZero128(), memZero128(), and PxMemSet().
memZero()
PX_FORCE_INLINE void* physx::intrinsics::memZero (void * dest, uint32_t count)
Sets count bytes starting at dst to zero.
Referenced by PxMemZero().
memZero128()
PX_FORCE_INLINE void physx::intrinsics::memZero128 (void * dest, uint32_t offset = 0)
Set 128B to zero starting at dst+offset. Must be aligned.
References memSet(), and PX_SHARED_ASSERT.
recip()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::recip (float a)
platform-specific reciprocal
recipFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::recipFast (float a)
platform-specific reciprocal estimate
recipSqrt()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::recipSqrt (float a)
platform-specific reciprocal square root
Referenced by PxRecipSqrt().
recipSqrtFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::recipSqrtFast (float a)
selectMax()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::selectMax (float a, float b)
platform-specific maximum
Referenced by PxMax().
selectMin()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::selectMin (float a, float b)
platform-specific minimum
Referenced by PxMin().
sign()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::sign (float a)
platform-specific sign
Referenced by PxSign().
sin()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::sin (float a)
platform-specific sine
Referenced by PxSin().
sqrt()
PX_CUDA_CALLABLE PX_FORCE_INLINE float physx::intrinsics::sqrt (float a)
platform-specific square root
Referenced by PxSqrt().