PxGeometryHelpers.h File Reference
PxGeometryHelpers.h File Reference
#include "foundation/PxPlane.h"
#include "foundation/PxTransform.h"
#include "foundation/PxUnionCast.h"
#include "common/PxPhysXCommonConfig.h"
#include "geometry/PxGeometry.h"
#include "geometry/PxBoxGeometry.h"
#include "geometry/PxSphereGeometry.h"
#include "geometry/PxCapsuleGeometry.h"
#include "geometry/PxPlaneGeometry.h"
#include "geometry/PxConvexMeshGeometry.h"
#include "geometry/PxHeightFieldGeometry.h"
Classes
class PxGeometryHolder
Geometry holder class.
Functions
class PxGeometryHolder PX_ALIGN_SUFFIX (4)
PX_FORCE_INLINE PxGeometryType::Enum getType () const
PX_FORCE_INLINE PxGeometry & any ()
PX_FORCE_INLINE PxSphereGeometry & sphere ()
PX_FORCE_INLINE PxPlaneGeometry & plane ()
PX_FORCE_INLINE PxCapsuleGeometry & capsule ()
PX_FORCE_INLINE PxBoxGeometry & box ()
PX_FORCE_INLINE PxConvexMeshGeometry & convexMesh ()
PX_FORCE_INLINE PxTriangleMeshGeometry & triangleMesh ()
PX_FORCE_INLINE PxHeightFieldGeometry & heightField ()
PX_FORCE_INLINE void storeAny (const PxGeometry &geometry)
PX_FORCE_INLINE PxGeometryHolder ()
PX_FORCE_INLINE PxGeometryHolder (const PxGeometry &geometry)
template<typename T >
void put (const PxGeometry &geometry)
template<typename T , PxGeometryType::Enum type>
T & get ()
Variables
union {
PxU8 geometry [sizeof(PxGeometry)]
PxU8 box [sizeof(PxBoxGeometry)]
PxU8 sphere [sizeof(PxSphereGeometry)]
PxU8 capsule [sizeof(PxCapsuleGeometry)]
PxU8 plane [sizeof(PxPlaneGeometry)]
PxU8 convex [sizeof(PxConvexMeshGeometry)]
PxU8 mesh [sizeof(PxTriangleMeshGeometry)]
PxU8 heightfield [sizeof(PxHeightFieldGeometry)]
} bytes
Function Documentation
any()
PX_FORCE_INLINE const PxGeometry & any ()
Referenced by PxGeometryHolder::get(), PxGeometryHolder::getType(), and PxGeometryHolder::put().
box()
PX_FORCE_INLINE PxBoxGeometry& PX_ALIGN_SUFFIX::box ()
capsule()
PX_FORCE_INLINE PxCapsuleGeometry& PX_ALIGN_SUFFIX::capsule ()
convexMesh()
PX_FORCE_INLINE const PxConvexMeshGeometry & convexMesh ()
Referenced by PxConvexMeshGeometry::isValid().
get()
template<typename T , PxGeometryType::Enum type> T & get () private
getType()
PX_FORCE_INLINE PxGeometryType::Enum PX_ALIGN_SUFFIX::getType () const
Referenced by PxGeometryHolder::get().
heightField()
PX_FORCE_INLINE const PxHeightFieldGeometry & heightField ()
Referenced by PxHeightFieldGeometry::isValid().
plane()
PX_FORCE_INLINE PxPlaneGeometry& PX_ALIGN_SUFFIX::plane ()
put()
template<typename T > void PX_ALIGN_SUFFIX::put (const PxGeometry & geometry) private
PxGeometryHolder() [1/2]
PX_FORCE_INLINE PX_ALIGN_SUFFIX::PxGeometryHolder ()
PxGeometryHolder() [2/2]
PX_FORCE_INLINE PX_ALIGN_SUFFIX::PxGeometryHolder (const PxGeometry & geometry)
sphere()
PX_FORCE_INLINE PxSphereGeometry& PX_ALIGN_SUFFIX::sphere ()
storeAny()
PX_FORCE_INLINE void PX_ALIGN_SUFFIX::storeAny (const PxGeometry & geometry)
References geometry.
triangleMesh()
PX_FORCE_INLINE const PxTriangleMeshGeometry & triangleMesh ()
References PxGeometryType::eCAPSULE, PxGeometryType::eGEOMETRY_COUNT, PxGeometryType::ePLANE, PxGeometryType::eSPHERE, geometry, and PX_ASSERT_WITH_MESSAGE.
Referenced by PxTriangleMeshGeometry::isValid().
Variable Documentation
box
PX_FORCE_INLINE const PxBoxGeometry & box
Referenced by PxBounds3::isInside().
bytes
union { ... } bytes
Referenced by PxGeometryHolder::any(), PxStrideIterator< T >::byteAdd(), and PxStrideIterator< T >::byteSub().
capsule
PX_FORCE_INLINE const PxCapsuleGeometry & capsule
convex
PxU8 convex[sizeof(PxConvexMeshGeometry)]
geometry
PxU8 geometry[sizeof(PxGeometry)]
Referenced by PxRigidActorExt::createExclusiveShape(), PxPhysics::createShape(), PxGeometryHolder::put(), PxMassProperties::PxMassProperties(), storeAny(), and triangleMesh().
heightfield
PxU8 heightfield[sizeof(PxHeightFieldGeometry)]
mesh
PxU8 mesh[sizeof(PxTriangleMeshGeometry)]
plane
PX_FORCE_INLINE const PxPlaneGeometry & plane
Referenced by PxTransform::inverseTransform(), and PxTransform::transform().
sphere
PX_FORCE_INLINE const PxSphereGeometry & sphere