PxWindowsIntrinsics.h File Reference
PxWindowsIntrinsics.h File Reference
#include "foundation/Px.h"
#include "foundation/PxSharedAssert.h"
#include <math.h>
#include <float.h>
Functions
PX_CUDA_CALLABLE PX_FORCE_INLINE float abs (float a)
platform-specific absolute value
PX_CUDA_CALLABLE PX_FORCE_INLINE float fsel (float a, float b, float c)
platform-specific select float
PX_CUDA_CALLABLE PX_FORCE_INLINE float sign (float a)
platform-specific sign
PX_CUDA_CALLABLE PX_FORCE_INLINE float recip (float a)
platform-specific reciprocal
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipFast (float a)
platform-specific reciprocal estimate
PX_CUDA_CALLABLE PX_FORCE_INLINE float sqrt (float a)
platform-specific square root
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrt (float a)
platform-specific reciprocal square root
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrtFast (float a)
platform-specific reciprocal square root estimate
PX_CUDA_CALLABLE PX_FORCE_INLINE float sin (float a)
platform-specific sine
PX_CUDA_CALLABLE PX_FORCE_INLINE float cos (float a)
platform-specific cosine
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMin (float a, float b)
platform-specific minimum
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMax (float a, float b)
platform-specific maximum
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (float a)
platform-specific finiteness check (not INF or NAN)
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (double a)
platform-specific finiteness check (not INF or NAN)
PX_FORCE_INLINE void * memZero (void *dest, uint32_t count)
PX_FORCE_INLINE void * memSet (void *dest, int32_t c, uint32_t count)
PX_FORCE_INLINE void * memCopy (void *dest, const void *src, uint32_t count)
PX_FORCE_INLINE void * memMove (void *dest, const void *src, uint32_t count)
PX_FORCE_INLINE void memZero128 (void *dest, uint32_t offset=0)
Function Documentation
abs()
PX_CUDA_CALLABLE PX_FORCE_INLINE float abs (float a)
platform-specific absolute value
Referenced by PxStrideIterator< T >::isCompatible(), and PxAbs().
cos()
PX_CUDA_CALLABLE PX_FORCE_INLINE float cos (float a)
platform-specific cosine
Referenced by PxCos().
fsel()
PX_CUDA_CALLABLE PX_FORCE_INLINE float fsel (float a, float b, float c)
platform-specific select float
isFinite() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (float a)
platform-specific finiteness check (not INF or NAN)
isFinite() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (double a)
platform-specific finiteness check (not INF or NAN)
memCopy()
PX_FORCE_INLINE void* memCopy (void * dest, const void * src, uint32_t count)
Copies count bytes from src to dst. User memMove if regions overlap.
memMove()
PX_FORCE_INLINE void* memMove (void * dest, const void * src, uint32_t count)
Copies count bytes from src to dst. Supports overlapping regions.
memSet()
PX_FORCE_INLINE void* memSet (void * dest, int32_t c, uint32_t count)
Sets count bytes starting at dst to c.
memZero()
PX_FORCE_INLINE void* memZero (void * dest, uint32_t count)
Sets count bytes starting at dst to zero.
memZero128()
PX_FORCE_INLINE void memZero128 (void * dest, uint32_t offset = 0)
Set 128B to zero starting at dst+offset. Must be aligned.
References physx::intrinsics::memSet(), and PX_SHARED_ASSERT.
recip()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recip (float a)
platform-specific reciprocal
recipFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipFast (float a)
platform-specific reciprocal estimate
recipSqrt()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrt (float a)
platform-specific reciprocal square root
recipSqrtFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrtFast (float a)
platform-specific reciprocal square root estimate
selectMax()
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMax (float a, float b)
platform-specific maximum
selectMin()
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMin (float a, float b)
platform-specific minimum
sign()
PX_CUDA_CALLABLE PX_FORCE_INLINE float sign (float a)
platform-specific sign
sin()
PX_CUDA_CALLABLE PX_FORCE_INLINE float sin (float a)
platform-specific sine
Referenced by PxSin().
sqrt()
PX_CUDA_CALLABLE PX_FORCE_INLINE float sqrt (float a)
platform-specific square root
Referenced by PxRecipSqrt(), and PxSqrt().