
# TODO
# TODO: PX_FORCE_INLINE (PX_VC or PX_LINUX?)
# TODO: Does applied2 use FastXML?
# TODO: extensions/serialization/Xml/SnXml.
# TODO: write out dependency graph.
# TODO: build shared libraries with CMake and inspect link dependencies.
# TODO: set defines in 1 location.

# cc_library(
#     name = "PhysXTODO",
#     srcs = [
#         ],
#     hdrs = [
#         ],
#     defines = [
#         "PX_BUILD_NUMBER=0",
#         "PX_CHECKED=1",  # TODO, use optimized.
#         "PX_NVTX=0",  # TODO what is this?
#         "PX_PHYSX_STATIC_LIB",
#         "PX_SUPPORT_PVD=0",
#         "NDEBUG",
#     ],
#     deps = [
#         ],
#     )

cc_library(
    name = "pxshared",
    hdrs = [
        "pxshared/include/foundation/Px.h",
        "pxshared/include/foundation/PxAllocatorCallback.h",
        "pxshared/include/foundation/PxAssert.h",
        "pxshared/include/foundation/PxBitAndData.h",
        "pxshared/include/foundation/PxBounds3.h",
        "pxshared/include/foundation/PxErrorCallback.h",
        "pxshared/include/foundation/PxErrors.h",
        "pxshared/include/foundation/PxFlags.h",
        "pxshared/include/foundation/PxIO.h",
        "pxshared/include/foundation/PxIntrinsics.h",
        "pxshared/include/foundation/PxMat33.h",
        "pxshared/include/foundation/PxMat44.h",
        "pxshared/include/foundation/PxMath.h",
        "pxshared/include/foundation/PxMathUtils.h",
        "pxshared/include/foundation/PxMemory.h",
        "pxshared/include/foundation/PxPlane.h",
        "pxshared/include/foundation/PxPreprocessor.h",
        "pxshared/include/foundation/PxProfiler.h",
        "pxshared/include/foundation/PxQuat.h",
        "pxshared/include/foundation/PxSimpleTypes.h",
        "pxshared/include/foundation/PxStrideIterator.h",
        "pxshared/include/foundation/PxTransform.h",
        "pxshared/include/foundation/PxUnionCast.h",
        "pxshared/include/foundation/PxVec2.h",
        "pxshared/include/foundation/PxVec3.h",
        "pxshared/include/foundation/PxVec4.h",
        "pxshared/include/foundation/unix/PxUnixIntrinsics.h",
    ],
)

# File paths come from physx/source/compiler/cmake/linux.
cc_library(
    name = "PhysXFoundation",
    srcs = [
        "physx/source/foundation/src/PsAllocator.cpp",
        "physx/source/foundation/src/PsAssert.cpp",
        "physx/source/foundation/src/PsFoundation.cpp",
        "physx/source/foundation/src/PsMathUtils.cpp",
        "physx/source/foundation/src/PsString.cpp",
        "physx/source/foundation/src/PsTempAllocator.cpp",
        "physx/source/foundation/src/PsUtilities.cpp",
        "physx/source/foundation/src/unix/PsUnixAtomic.cpp",
        "physx/source/foundation/src/unix/PsUnixCpu.cpp",
        "physx/source/foundation/src/unix/PsUnixFPU.cpp",
        "physx/source/foundation/src/unix/PsUnixMutex.cpp",
        "physx/source/foundation/src/unix/PsUnixPrintString.cpp",
        "physx/source/foundation/src/unix/PsUnixSList.cpp",
        "physx/source/foundation/src/unix/PsUnixSocket.cpp",
        "physx/source/foundation/src/unix/PsUnixSync.cpp",
        "physx/source/foundation/src/unix/PsUnixThread.cpp",
        "physx/source/foundation/src/unix/PsUnixTime.cpp",
    ],
    hdrs = [
        # "pxshared/include/foundation/PxIntrinsics.h",
        # TODO(dembia): Do physx/include/*.h files belong elsewhere?
        "physx/include/PxPhysicsVersion.h",
        "physx/include/PxPhysXConfig.h",
        "physx/include/PxPhysicsAPI.h",
        "physx/include/PxDeletionListener.h",
        "physx/include/PxPhysics.h",
        "physx/include/PxQueryReport.h",
        "physx/include/PxContact.h",
        "physx/include/PxConstraintDesc.h",
        "physx/include/PxVisualizationParameter.h",
        "physx/include/PxFoundation.h",
        "physx/source/foundation/include/Ps.h",
        "physx/source/foundation/include/PsAlignedMalloc.h",
        "physx/source/foundation/include/PsAlloca.h",
        "physx/source/foundation/include/PsAllocator.h",
        "physx/source/foundation/include/PsAoS.h",
        "physx/source/foundation/include/PsArray.h",
        "physx/source/foundation/include/PsAtomic.h",
        "physx/source/foundation/include/PsBasicTemplates.h",
        "physx/source/foundation/include/PsBitUtils.h",
        "physx/source/foundation/include/PsBroadcast.h",
        "physx/source/foundation/include/PsCpu.h",
        "physx/source/foundation/include/PsFPU.h",
        "physx/source/foundation/include/PsFoundation.h",
        "physx/source/foundation/include/PsHash.h",
        "physx/source/foundation/include/PsHashInternals.h",
        "physx/source/foundation/include/PsHashMap.h",
        "physx/source/foundation/include/PsHashSet.h",
        "physx/source/foundation/include/PsInlineAllocator.h",
        "physx/source/foundation/include/PsInlineAoS.h",
        "physx/source/foundation/include/PsInlineArray.h",
        "physx/source/foundation/include/PsIntrinsics.h",
        "physx/source/foundation/include/PsMathUtils.h",
        "physx/source/foundation/include/PsMutex.h",
        "physx/source/foundation/include/PsPool.h",
        "physx/source/foundation/include/PsSList.h",
        "physx/source/foundation/include/PsSocket.h",
        "physx/source/foundation/include/PsSort.h",
        "physx/source/foundation/include/PsSortInternals.h",
        "physx/source/foundation/include/PsString.h",
        "physx/source/foundation/include/PsSync.h",
        "physx/source/foundation/include/PsTempAllocator.h",
        "physx/source/foundation/include/PsThread.h",
        "physx/source/foundation/include/PsTime.h",
        "physx/source/foundation/include/PsUserAllocated.h",
        "physx/source/foundation/include/PsUtilities.h",
        "physx/source/foundation/include/PsVecMath.h",
        "physx/source/foundation/include/PsVecMathAoSScalar.h",
        "physx/source/foundation/include/PsVecMathAoSScalarInline.h",
        "physx/source/foundation/include/PsVecMathSSE.h",
        "physx/source/foundation/include/PsVecMathUtilities.h",
        "physx/source/foundation/include/PsVecQuat.h",
        "physx/source/foundation/include/PsVecTransform.h",
        "physx/source/foundation/include/unix/PsUnixAoS.h",
        "physx/source/foundation/include/unix/PsUnixFPU.h",
        "physx/source/foundation/include/unix/PsUnixInlineAoS.h",
        "physx/source/foundation/include/unix/PsUnixIntrinsics.h",
        "physx/source/foundation/include/unix/PsUnixTrigConstants.h",
        "physx/source/foundation/include/unix/neon/PsUnixNeonAoS.h",
        "physx/source/foundation/include/unix/neon/PsUnixNeonInlineAoS.h",
        "physx/source/foundation/include/unix/sse2/PsUnixSse2AoS.h",
        "physx/source/foundation/include/unix/sse2/PsUnixSse2InlineAoS.h",
    ],
    defines = [
        "PX_BUILD_NUMBER=0",
        # "PX_DEBUG=1", # TODO
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        # PVD: PhysX Visual Debugger (visualizer).
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    includes = [
        "physx/include",
        "physx/include/common",
        "physx/include/geometry",
        "physx/include/geomutils",
        "physx/source",
        "physx/source/common/include",
        "physx/source/common/src",
        "physx/source/common/src/linux",
        "physx/source/foundation/include",
        "physx/source/geomutils/include",
        "physx/source/geomutils/src",
        "physx/source/geomutils/src/ccd",
        "physx/source/geomutils/src/common",
        "physx/source/geomutils/src/contact",
        "physx/source/geomutils/src/convex",
        "physx/source/geomutils/src/distance",
        "physx/source/geomutils/src/gjk",
        "physx/source/geomutils/src/hf",
        "physx/source/geomutils/src/intersection",
        "physx/source/geomutils/src/mesh",
        "physx/source/geomutils/src/pcm",
        "physx/source/geomutils/src/sweep",
        "physx/source/physxgpu/include",
        "pxshared/include",
    ],
    linkopts = [
        "-pthread",
    ],
    deps = [
        ":pxshared",
    ],
)

cc_library(
    name = "PhysXTask",
    srcs = [
        "physx/source/task/src/TaskManager.cpp",
    ],
    hdrs = [
        "physx/include/task/PxCpuDispatcher.h",
        "physx/include/task/PxGpuDispatcher.h",
        "physx/include/task/PxGpuTask.h",
        "physx/include/task/PxTask.h",
        "physx/include/task/PxTaskDefine.h",
        "physx/include/task/PxTaskManager.h",
    ],
    deps = [
        ":PhysXFoundation",
    ],
)

cc_library(
    name = "PhysXCommon",
    srcs = [
        "physx/source/common/src/CmBoxPruning.cpp",
        "physx/source/common/src/CmCollection.cpp",
        "physx/source/common/src/CmMathUtils.cpp",
        "physx/source/common/src/CmPtrTable.cpp",
        "physx/source/common/src/CmRadixSort.cpp",
        "physx/source/common/src/CmRadixSortBuffered.cpp",
        "physx/source/common/src/CmRenderOutput.cpp",
        "physx/source/common/src/CmVisualization.cpp",
        "physx/source/geomutils/src/GuAABBTreeBuild.cpp",
        "physx/source/geomutils/src/GuBVHStructure.cpp",
        "physx/source/geomutils/src/GuBounds.cpp",
        "physx/source/geomutils/src/GuBox.cpp",
        "physx/source/geomutils/src/GuCCTSweepTests.cpp",
        "physx/source/geomutils/src/GuCapsule.cpp",
        "physx/source/geomutils/src/GuGeometryQuery.cpp",
        "physx/source/geomutils/src/GuGeometryUnion.cpp",
        "physx/source/geomutils/src/GuInternal.cpp",
        "physx/source/geomutils/src/GuMTD.cpp",
        "physx/source/geomutils/src/GuMeshFactory.cpp",
        "physx/source/geomutils/src/GuMetaData.cpp",
        "physx/source/geomutils/src/GuOverlapTests.cpp",
        "physx/source/geomutils/src/GuRaycastTests.cpp",
        "physx/source/geomutils/src/GuSerialize.cpp",
        "physx/source/geomutils/src/GuSweepMTD.cpp",
        "physx/source/geomutils/src/GuSweepSharedTests.cpp",
        "physx/source/geomutils/src/GuSweepTests.cpp",
        "physx/source/geomutils/src/ccd/GuCCDSweepConvexMesh.cpp",
        "physx/source/geomutils/src/ccd/GuCCDSweepPrimitives.cpp",
        "physx/source/geomutils/src/common/GuBarycentricCoordinates.cpp",
        "physx/source/geomutils/src/common/GuSeparatingAxes.cpp",
        "physx/source/geomutils/src/contact/GuContactBoxBox.cpp",
        "physx/source/geomutils/src/contact/GuContactCapsuleBox.cpp",
        "physx/source/geomutils/src/contact/GuContactCapsuleCapsule.cpp",
        "physx/source/geomutils/src/contact/GuContactCapsuleConvex.cpp",
        "physx/source/geomutils/src/contact/GuContactCapsuleMesh.cpp",
        "physx/source/geomutils/src/contact/GuContactConvexConvex.cpp",
        "physx/source/geomutils/src/contact/GuContactConvexMesh.cpp",
        "physx/source/geomutils/src/contact/GuContactPlaneBox.cpp",
        "physx/source/geomutils/src/contact/GuContactPlaneCapsule.cpp",
        "physx/source/geomutils/src/contact/GuContactPlaneConvex.cpp",
        "physx/source/geomutils/src/contact/GuContactPolygonPolygon.cpp",
        "physx/source/geomutils/src/contact/GuContactSphereBox.cpp",
        "physx/source/geomutils/src/contact/GuContactSphereCapsule.cpp",
        "physx/source/geomutils/src/contact/GuContactSphereMesh.cpp",
        "physx/source/geomutils/src/contact/GuContactSpherePlane.cpp",
        "physx/source/geomutils/src/contact/GuContactSphereSphere.cpp",
        "physx/source/geomutils/src/contact/GuFeatureCode.cpp",
        "physx/source/geomutils/src/convex/GuBigConvexData.cpp",
        "physx/source/geomutils/src/convex/GuConvexHelper.cpp",
        "physx/source/geomutils/src/convex/GuConvexMesh.cpp",
        "physx/source/geomutils/src/convex/GuConvexSupportTable.cpp",
        "physx/source/geomutils/src/convex/GuConvexUtilsInternal.cpp",
        "physx/source/geomutils/src/convex/GuHillClimbing.cpp",
        "physx/source/geomutils/src/convex/GuShapeConvex.cpp",
        "physx/source/geomutils/src/distance/GuDistancePointBox.cpp",
        "physx/source/geomutils/src/distance/GuDistancePointTriangle.cpp",
        "physx/source/geomutils/src/distance/GuDistanceSegmentBox.cpp",
        "physx/source/geomutils/src/distance/GuDistanceSegmentSegment.cpp",
        "physx/source/geomutils/src/distance/GuDistanceSegmentTriangle.cpp",
        "physx/source/geomutils/src/gjk/GuEPA.cpp",
        "physx/source/geomutils/src/gjk/GuGJKSimplex.cpp",
        "physx/source/geomutils/src/gjk/GuGJKTest.cpp",
        "physx/source/geomutils/src/hf/GuHeightField.cpp",
        "physx/source/geomutils/src/hf/GuHeightFieldUtil.cpp",
        "physx/source/geomutils/src/hf/GuOverlapTestsHF.cpp",
        "physx/source/geomutils/src/hf/GuSweepsHF.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionBoxBox.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionCapsuleTriangle.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionEdgeEdge.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionRayBox.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionRayCapsule.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionRaySphere.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionSphereBox.cpp",
        "physx/source/geomutils/src/intersection/GuIntersectionTriangleBox.cpp",
        "physx/source/geomutils/src/mesh/GuBV32.cpp",
        "physx/source/geomutils/src/mesh/GuBV32Build.cpp",
        "physx/source/geomutils/src/mesh/GuBV4.cpp",
        "physx/source/geomutils/src/mesh/GuBV4Build.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_AABBSweep.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_BoxOverlap.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_CapsuleSweep.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_CapsuleSweepAA.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_OBBSweep.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_Raycast.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_SphereOverlap.cpp",
        "physx/source/geomutils/src/mesh/GuBV4_SphereSweep.cpp",
        "physx/source/geomutils/src/mesh/GuMeshQuery.cpp",
        "physx/source/geomutils/src/mesh/GuMidphaseBV4.cpp",
        "physx/source/geomutils/src/mesh/GuMidphaseRTree.cpp",
        "physx/source/geomutils/src/mesh/GuOverlapTestsMesh.cpp",
        "physx/source/geomutils/src/mesh/GuRTree.cpp",
        "physx/source/geomutils/src/mesh/GuRTreeQueries.cpp",
        "physx/source/geomutils/src/mesh/GuSweepsMesh.cpp",
        "physx/source/geomutils/src/mesh/GuTriangleMesh.cpp",
        "physx/source/geomutils/src/mesh/GuTriangleMeshBV4.cpp",
        "physx/source/geomutils/src/mesh/GuTriangleMeshRTree.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactBoxBox.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactBoxConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactCapsuleBox.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactCapsuleCapsule.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactCapsuleConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactCapsuleHeightField.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactCapsuleMesh.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactConvexCommon.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactConvexConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactConvexHeightField.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactConvexMesh.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactGenBoxConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactGenSphereCapsule.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactPlaneBox.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactPlaneCapsule.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactPlaneConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSphereBox.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSphereCapsule.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSphereConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSphereHeightField.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSphereMesh.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSpherePlane.cpp",
        "physx/source/geomutils/src/pcm/GuPCMContactSphereSphere.cpp",
        "physx/source/geomutils/src/pcm/GuPCMShapeConvex.cpp",
        "physx/source/geomutils/src/pcm/GuPCMTriangleContactGen.cpp",
        "physx/source/geomutils/src/pcm/GuPersistentContactManifold.cpp",
        "physx/source/geomutils/src/sweep/GuSweepBoxBox.cpp",
        "physx/source/geomutils/src/sweep/GuSweepBoxSphere.cpp",
        "physx/source/geomutils/src/sweep/GuSweepBoxTriangle_FeatureBased.cpp",
        "physx/source/geomutils/src/sweep/GuSweepBoxTriangle_SAT.cpp",
        "physx/source/geomutils/src/sweep/GuSweepCapsuleBox.cpp",
        "physx/source/geomutils/src/sweep/GuSweepCapsuleCapsule.cpp",
        "physx/source/geomutils/src/sweep/GuSweepCapsuleTriangle.cpp",
        "physx/source/geomutils/src/sweep/GuSweepSphereCapsule.cpp",
        "physx/source/geomutils/src/sweep/GuSweepSphereSphere.cpp",
        "physx/source/geomutils/src/sweep/GuSweepSphereTriangle.cpp",
        "physx/source/geomutils/src/sweep/GuSweepTriangleUtils.cpp",
    ],
    hdrs = [
        "physx/include/collision/PxCollisionDefs.h",
        "physx/include/common/PxBase.h",
        "physx/include/common/PxCollection.h",
        "physx/include/common/PxCoreUtilityTypes.h",
        "physx/include/common/PxMetaData.h",
        "physx/include/common/PxMetaDataFlags.h",
        "physx/include/common/PxPhysXCommonConfig.h",
        "physx/include/common/PxPhysicsInsertionCallback.h",
        "physx/include/common/PxProfileZone.h",
        "physx/include/common/PxRenderBuffer.h",
        "physx/include/common/PxSerialFramework.h",
        "physx/include/common/PxSerializer.h",
        "physx/include/common/PxStringTable.h",
        "physx/include/common/PxTolerancesScale.h",
        "physx/include/common/PxTypeInfo.h",
        "physx/include/geometry/PxBVHStructure.h",
        "physx/include/geometry/PxBoxGeometry.h",
        "physx/include/geometry/PxCapsuleGeometry.h",
        "physx/include/geometry/PxConvexMesh.h",
        "physx/include/geometry/PxConvexMeshGeometry.h",
        "physx/include/geometry/PxGeometry.h",
        "physx/include/geometry/PxGeometryHelpers.h",
        "physx/include/geometry/PxGeometryQuery.h",
        "physx/include/geometry/PxHeightField.h",
        "physx/include/geometry/PxHeightFieldDesc.h",
        "physx/include/geometry/PxHeightFieldFlag.h",
        "physx/include/geometry/PxHeightFieldGeometry.h",
        "physx/include/geometry/PxHeightFieldSample.h",
        "physx/include/geometry/PxMeshQuery.h",
        "physx/include/geometry/PxMeshScale.h",
        "physx/include/geometry/PxPlaneGeometry.h",
        "physx/include/geometry/PxSimpleTriangleMesh.h",
        "physx/include/geometry/PxSphereGeometry.h",
        "physx/include/geometry/PxTriangle.h",
        "physx/include/geometry/PxTriangleMesh.h",
        "physx/include/geometry/PxTriangleMeshGeometry.h",
        "physx/include/geomutils/GuContactBuffer.h",
        "physx/include/geomutils/GuContactPoint.h",
        "physx/source/common/src/CmBitMap.h",
        "physx/source/common/src/CmBlockArray.h",
        "physx/source/common/src/CmBoxPruning.h",
        "physx/source/common/src/CmCollection.h",
        "physx/source/common/src/CmConeLimitHelper.h",
        "physx/source/common/src/CmFlushPool.h",
        "physx/source/common/src/CmIDPool.h",
        "physx/source/common/src/CmIO.h",
        "physx/source/common/src/CmMatrix34.h",
        "physx/source/common/src/CmPhysXCommon.h",
        "physx/source/common/src/CmPool.h",
        "physx/source/common/src/CmPreallocatingPool.h",
        "physx/source/common/src/CmPriorityQueue.h",
        "physx/source/common/src/CmPtrTable.h",
        "physx/source/common/src/CmQueue.h",
        "physx/source/common/src/CmRadixSort.h",
        "physx/source/common/src/CmRadixSortBuffered.h",
        "physx/source/common/src/CmRefCountable.h",
        "physx/source/common/src/CmRenderBuffer.h",
        "physx/source/common/src/CmRenderOutput.h",
        "physx/source/common/src/CmScaling.h",
        "physx/source/common/src/CmSpatialVector.h",
        "physx/source/common/src/CmTask.h",
        "physx/source/common/src/CmTaskPool.h",
        "physx/source/common/src/CmTmpMem.h",
        "physx/source/common/src/CmTransformUtils.h",
        "physx/source/common/src/CmUtils.h",
        "physx/source/common/src/CmVisualization.h",
        "physx/source/geomutils/include/GuAxes.h",
        "physx/source/geomutils/include/GuBox.h",
        "physx/source/geomutils/include/GuDistanceSegmentBox.h",
        "physx/source/geomutils/include/GuDistanceSegmentSegment.h",
        "physx/source/geomutils/include/GuIntersectionBoxBox.h",
        "physx/source/geomutils/include/GuIntersectionTriangleBox.h",
        "physx/source/geomutils/include/GuIntersectionTriangleBoxRef.h",
        "physx/source/geomutils/include/GuRaycastTests.h",
        "physx/source/geomutils/include/GuSIMDHelpers.h",
        "physx/source/geomutils/include/GuSegment.h",
        "physx/source/geomutils/src/GuAABBTreeBuild.h",
        "physx/source/geomutils/src/GuAABBTreeQuery.h",
        "physx/source/geomutils/src/GuBVHStructure.h",
        "physx/source/geomutils/src/GuBVHTestsSIMD.h",
        "physx/source/geomutils/src/GuBounds.h",
        "physx/source/geomutils/src/GuCapsule.h",
        "physx/source/geomutils/src/GuCenterExtents.h",
        "physx/source/geomutils/src/GuGeometryUnion.h",
        "physx/source/geomutils/src/GuInternal.h",
        "physx/source/geomutils/src/GuMTD.h",
        "physx/source/geomutils/src/GuMeshFactory.h",
        "physx/source/geomutils/src/GuOverlapTests.h",
        "physx/source/geomutils/src/GuSerialize.h",
        "physx/source/geomutils/src/GuSphere.h",
        "physx/source/geomutils/src/GuSweepMTD.h",
        "physx/source/geomutils/src/GuSweepSharedTests.h",
        "physx/source/geomutils/src/GuSweepTests.h",
        "physx/source/geomutils/src/ccd/GuCCDSweepConvexMesh.h",
        "physx/source/geomutils/src/common/GuBarycentricCoordinates.h",
        "physx/source/geomutils/src/common/GuBoxConversion.h",
        "physx/source/geomutils/src/common/GuEdgeCache.h",
        "physx/source/geomutils/src/common/GuEdgeListData.h",
        "physx/source/geomutils/src/common/GuSeparatingAxes.h",
        "physx/source/geomutils/src/contact/GuContactMethodImpl.h",
        "physx/source/geomutils/src/contact/GuContactPolygonPolygon.h",
        "physx/source/geomutils/src/contact/GuFeatureCode.h",
        "physx/source/geomutils/src/convex/GuBigConvexData.h",
        "physx/source/geomutils/src/convex/GuBigConvexData2.h",
        "physx/source/geomutils/src/convex/GuConvexEdgeFlags.h",
        "physx/source/geomutils/src/convex/GuConvexHelper.h",
        "physx/source/geomutils/src/convex/GuConvexMesh.h",
        "physx/source/geomutils/src/convex/GuConvexMeshData.h",
        "physx/source/geomutils/src/convex/GuConvexSupportTable.h",
        "physx/source/geomutils/src/convex/GuConvexUtilsInternal.h",
        "physx/source/geomutils/src/convex/GuCubeIndex.h",
        "physx/source/geomutils/src/convex/GuHillClimbing.h",
        "physx/source/geomutils/src/convex/GuShapeConvex.h",
        "physx/source/geomutils/src/distance/GuDistancePointBox.h",
        "physx/source/geomutils/src/distance/GuDistancePointSegment.h",
        "physx/source/geomutils/src/distance/GuDistancePointTriangle.h",
        "physx/source/geomutils/src/distance/GuDistancePointTriangleSIMD.h",
        "physx/source/geomutils/src/distance/GuDistanceSegmentSegmentSIMD.h",
        "physx/source/geomutils/src/distance/GuDistanceSegmentTriangle.h",
        "physx/source/geomutils/src/distance/GuDistanceSegmentTriangleSIMD.h",
        "physx/source/geomutils/src/gjk/GuEPA.h",
        "physx/source/geomutils/src/gjk/GuEPAFacet.h",
        "physx/source/geomutils/src/gjk/GuGJK.h",
        "physx/source/geomutils/src/gjk/GuGJKPenetration.h",
        "physx/source/geomutils/src/gjk/GuGJKRaycast.h",
        "physx/source/geomutils/src/gjk/GuGJKSimplex.h",
        "physx/source/geomutils/src/gjk/GuGJKTest.h",
        "physx/source/geomutils/src/gjk/GuGJKType.h",
        "physx/source/geomutils/src/gjk/GuGJKUtil.h",
        "physx/source/geomutils/src/gjk/GuVecBox.h",
        "physx/source/geomutils/src/gjk/GuVecCapsule.h",
        "physx/source/geomutils/src/gjk/GuVecConvex.h",
        "physx/source/geomutils/src/gjk/GuVecConvexHull.h",
        "physx/source/geomutils/src/gjk/GuVecConvexHullNoScale.h",
        "physx/source/geomutils/src/gjk/GuVecPlane.h",
        "physx/source/geomutils/src/gjk/GuVecSphere.h",
        "physx/source/geomutils/src/gjk/GuVecTriangle.h",
        "physx/source/geomutils/src/hf/GuEntityReport.h",
        "physx/source/geomutils/src/hf/GuHeightField.h",
        "physx/source/geomutils/src/hf/GuHeightFieldData.h",
        "physx/source/geomutils/src/hf/GuHeightFieldUtil.h",
        "physx/source/geomutils/src/intersection/GuIntersectionCapsuleTriangle.h",
        "physx/source/geomutils/src/intersection/GuIntersectionEdgeEdge.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRay.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRayBox.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRayBoxSIMD.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRayCapsule.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRayPlane.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRaySphere.h",
        "physx/source/geomutils/src/intersection/GuIntersectionRayTriangle.h",
        "physx/source/geomutils/src/intersection/GuIntersectionSphereBox.h",
        "physx/source/geomutils/src/mesh/GuBV32.h",
        "physx/source/geomutils/src/mesh/GuBV32Build.h",
        "physx/source/geomutils/src/mesh/GuBV4.h",
        "physx/source/geomutils/src/mesh/GuBV4Build.h",
        "physx/source/geomutils/src/mesh/GuBV4Settings.h",
        "physx/source/geomutils/src/mesh/GuBV4_AABBAABBSweepTest.h",
        "physx/source/geomutils/src/mesh/GuBV4_BoxBoxOverlapTest.h",
        "physx/source/geomutils/src/mesh/GuBV4_BoxOverlap_Internal.h",
        "physx/source/geomutils/src/mesh/GuBV4_BoxSweep_Internal.h",
        "physx/source/geomutils/src/mesh/GuBV4_BoxSweep_Params.h",
        "physx/source/geomutils/src/mesh/GuBV4_CapsuleSweep_Internal.h",
        "physx/source/geomutils/src/mesh/GuBV4_Common.h",
        "physx/source/geomutils/src/mesh/GuBV4_Internal.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamNoOrder_OBBOBB.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamNoOrder_SegmentAABB.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamNoOrder_SegmentAABB_Inflated.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamNoOrder_SphereAABB.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamOrdered_OBBOBB.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamOrdered_SegmentAABB.h",
        "physx/source/geomutils/src/mesh/GuBV4_ProcessStreamOrdered_SegmentAABB_Inflated.h",
        "physx/source/geomutils/src/mesh/GuBV4_Slabs.h",
        "physx/source/geomutils/src/mesh/GuBV4_Slabs_KajiyaNoOrder.h",
        "physx/source/geomutils/src/mesh/GuBV4_Slabs_KajiyaOrdered.h",
        "physx/source/geomutils/src/mesh/GuBV4_Slabs_SwizzledNoOrder.h",
        "physx/source/geomutils/src/mesh/GuBV4_Slabs_SwizzledOrdered.h",
        "physx/source/geomutils/src/mesh/GuBVConstants.h",
        "physx/source/geomutils/src/mesh/GuMeshData.h",
        "physx/source/geomutils/src/mesh/GuMidphaseInterface.h",
        "physx/source/geomutils/src/mesh/GuRTree.h",
        "physx/source/geomutils/src/mesh/GuSweepConvexTri.h",
        "physx/source/geomutils/src/mesh/GuSweepMesh.h",
        "physx/source/geomutils/src/mesh/GuTriangle32.h",
        "physx/source/geomutils/src/mesh/GuTriangleCache.h",
        "physx/source/geomutils/src/mesh/GuTriangleMesh.h",
        "physx/source/geomutils/src/mesh/GuTriangleMeshBV4.h",
        "physx/source/geomutils/src/mesh/GuTriangleMeshRTree.h",
        "physx/source/geomutils/src/mesh/GuTriangleVertexPointers.h",
        "physx/source/geomutils/src/pcm/GuPCMContactConvexCommon.h",
        "physx/source/geomutils/src/pcm/GuPCMContactGen.h",
        "physx/source/geomutils/src/pcm/GuPCMContactGenUtil.h",
        "physx/source/geomutils/src/pcm/GuPCMContactMeshCallback.h",
        "physx/source/geomutils/src/pcm/GuPCMShapeConvex.h",
        "physx/source/geomutils/src/pcm/GuPCMTriangleContactGen.h",
        "physx/source/geomutils/src/pcm/GuPersistentContactManifold.h",
        "physx/source/geomutils/src/sweep/GuSweepBoxBox.h",
        "physx/source/geomutils/src/sweep/GuSweepBoxSphere.h",
        "physx/source/geomutils/src/sweep/GuSweepBoxTriangle_FeatureBased.h",
        "physx/source/geomutils/src/sweep/GuSweepBoxTriangle_SAT.h",
        "physx/source/geomutils/src/sweep/GuSweepCapsuleBox.h",
        "physx/source/geomutils/src/sweep/GuSweepCapsuleCapsule.h",
        "physx/source/geomutils/src/sweep/GuSweepCapsuleTriangle.h",
        "physx/source/geomutils/src/sweep/GuSweepSphereCapsule.h",
        "physx/source/geomutils/src/sweep/GuSweepSphereSphere.h",
        "physx/source/geomutils/src/sweep/GuSweepSphereTriangle.h",
        "physx/source/geomutils/src/sweep/GuSweepTriangleUtils.h",
    ],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    includes = [
        "physx/include",
        "physx/include/common",
        "physx/include/geometry",
        "physx/include/geomutils",
        "physx/source",
        "physx/source/common/include",
        "physx/source/common/src",
        "physx/source/common/src/linux",
        "physx/source/foundation/include",
        "physx/source/geomutils/include",
        "physx/source/geomutils/src",
        "physx/source/geomutils/src/ccd",
        "physx/source/geomutils/src/common",
        "physx/source/geomutils/src/contact",
        "physx/source/geomutils/src/convex",
        "physx/source/geomutils/src/distance",
        "physx/source/geomutils/src/gjk",
        "physx/source/geomutils/src/hf",
        "physx/source/geomutils/src/intersection",
        "physx/source/geomutils/src/mesh",
        "physx/source/geomutils/src/pcm",
        "physx/source/geomutils/src/sweep",
        "physx/source/physxgpu/include",
        "pxshared/include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":PhysXFoundation",
    ],
)

cc_library(
    name = "PhysXLowLevel",
    srcs = [
        "physx/source/lowlevel/api/src/px_globals.cpp",
        "physx/source/lowlevel/common/src/collision/PxcContact.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcContactCache.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcContactMethodImpl.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcMaterialHeightField.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcMaterialMesh.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcMaterialMethodImpl.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcMaterialShape.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcNpBatch.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcNpCacheStreamPair.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcNpContactPrepShared.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcNpMemBlockPool.cpp",
        "physx/source/lowlevel/common/src/pipeline/PxcNpThreadContext.cpp",
        "physx/source/lowlevel/software/src/PxsCCD.cpp",
        "physx/source/lowlevel/software/src/PxsContactManager.cpp",
        "physx/source/lowlevel/software/src/PxsContext.cpp",
        "physx/source/lowlevel/software/src/PxsDefaultMemoryManager.cpp",
        "physx/source/lowlevel/software/src/PxsIslandSim.cpp",
        "physx/source/lowlevel/software/src/PxsMaterialCombiner.cpp",
        "physx/source/lowlevel/software/src/PxsNphaseImplementationContext.cpp",
        "physx/source/lowlevel/software/src/PxsSimpleIslandManager.cpp",
    ],
    hdrs = [
        # TODO(dembia): Where to put these?
        "physx/include/PxSceneDesc.h",
        "physx/include/PxFiltering.h",
        "physx/include/PxBroadPhase.h",
        "physx/include/PxMaterial.h",
        "physx/include/PxRigidDynamic.h",
        "physx/include/PxRigidActor.h",
        "physx/include/PxRigidBody.h",
        "physx/include/PxShape.h",
        "physx/include/PxActor.h",
        "physx/include/PxContactModifyCallback.h",
        "physx/source/lowlevel/software/include/PxsBodySim.h",
        "physx/source/lowlevel/software/include/PxsCCD.h",
        "physx/source/lowlevel/software/include/PxsContactManager.h",
        "physx/source/lowlevel/software/include/PxsContactManagerState.h",
        "physx/source/lowlevel/software/include/PxsContext.h",
        "physx/source/lowlevel/software/include/PxsDefaultMemoryManager.h",
        "physx/source/lowlevel/software/include/PxsHeapMemoryAllocator.h",
        "physx/source/lowlevel/software/include/PxsIncrementalConstraintPartitioning.h",
        "physx/source/lowlevel/software/include/PxsIslandManagerTypes.h",
        "physx/source/lowlevel/software/include/PxsIslandSim.h",
        "physx/source/lowlevel/software/include/PxsIslandNodeIndex.h",
        "physx/source/lowlevel/software/include/PxsKernelWrangler.h",
        "physx/source/lowlevel/software/include/PxsMaterialCombiner.h",
        "physx/source/lowlevel/software/include/PxsMemoryManager.h",
        "physx/source/lowlevel/software/include/PxsNphaseImplementationContext.h",
        "physx/source/lowlevel/software/include/PxsRigidBody.h",
        "physx/source/lowlevel/software/include/PxsShapeSim.h",
        "physx/source/lowlevel/software/include/PxsSimpleIslandManager.h",
        "physx/source/lowlevel/software/include/PxsSimulationController.h",
        "physx/source/lowlevel/software/include/PxsTransformCache.h",
        "physx/source/lowlevel/software/include/PxvNphaseImplementationContext.h",
        # TODO: Move collision to separate library?
        "physx/source/lowlevel/common/include/collision/PxcContactMethodImpl.h",
        "physx/source/lowlevel/api/include/PxsMaterialCore.h",
        "physx/source/lowlevel/api/include/PxsMaterialManager.h",
        "physx/source/lowlevel/api/include/PxvConfig.h",
        "physx/source/lowlevel/api/include/PxvDynamics.h",
        "physx/source/lowlevel/api/include/PxvGeometry.h",
        "physx/source/lowlevel/api/include/PxvGlobals.h",
        "physx/source/lowlevel/api/include/PxvManager.h",
        "physx/source/lowlevel/api/include/PxvSimStats.h",
        "physx/source/lowlevel/common/include/pipeline/PxcCCDStateStreamPair.h",
        "physx/source/lowlevel/common/include/pipeline/PxcConstraintBlockStream.h",
        "physx/source/lowlevel/common/include/pipeline/PxcContactCache.h",
        "physx/source/lowlevel/common/include/pipeline/PxcMaterialMethodImpl.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpBatch.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpCache.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpCacheStreamPair.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpContactPrepShared.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpMemBlockPool.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpThreadContext.h",
        "physx/source/lowlevel/common/include/pipeline/PxcNpWorkUnit.h",
        "physx/source/lowlevel/common/include/pipeline/PxcRigidBody.h",
        "physx/source/lowlevel/common/include/utils/PxcScratchAllocator.h",
        "physx/source/lowlevel/common/include/utils/PxcThreadCoherentCache.h",
    ],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    includes = [
        "physx/include",
        "physx/include/common",
        "physx/include/geometry",
        "physx/include/geomutils",
        "physx/source",
        "physx/source/common/include",
        "physx/source/common/src",
        "physx/source/common/src/linux",
        "physx/source/foundation/include",
        "physx/source/geomutils/include",
        "physx/source/geomutils/src",
        "physx/source/geomutils/src/ccd",
        "physx/source/geomutils/src/common",
        "physx/source/geomutils/src/contact",
        "physx/source/geomutils/src/convex",
        "physx/source/geomutils/src/distance",
        "physx/source/geomutils/src/gjk",
        "physx/source/geomutils/src/hf",
        "physx/source/geomutils/src/intersection",
        "physx/source/geomutils/src/mesh",
        "physx/source/geomutils/src/pcm",
        "physx/source/geomutils/src/sweep",
        "physx/source/lowlevel/api/include",
        "physx/source/lowlevel/common/include",
        "physx/source/lowlevel/common/include/collision",
        "physx/source/lowlevel/common/include/pipeline",
        "physx/source/lowlevel/common/include/utils",
        "physx/source/lowlevel/software/include",
        "physx/source/physx/src/buffering",
        "physx/source/physxgpu/include",
        "pxshared/include",
    ],
    deps = [
        ":PhysXFoundation",
        ":PhysXCommon",
        ":PhysXTask",
    ],
)

cc_library(
    name = "PhysXLowLevelDynamics",
    srcs = [
	"physx/source/lowleveldynamics/src/DyArticulation.cpp",
	"physx/source/lowleveldynamics/src/DyArticulationContactPrep.cpp",
	"physx/source/lowleveldynamics/src/DyArticulationContactPrepPF.cpp",
	"physx/source/lowleveldynamics/src/DyArticulationHelper.cpp",
	"physx/source/lowleveldynamics/src/DyArticulationScalar.cpp",
	"physx/source/lowleveldynamics/src/DyArticulationSIMD.cpp",
	"physx/source/lowleveldynamics/src/DyFeatherstoneArticulation.cpp",
	"physx/source/lowleveldynamics/src/DyFeatherstoneForwardDynamic.cpp",
	"physx/source/lowleveldynamics/src/DyFeatherstoneInverseDynamic.cpp",
	"physx/source/lowleveldynamics/src/DyConstraintPartition.cpp",
	"physx/source/lowleveldynamics/src/DyConstraintSetup.cpp",
	"physx/source/lowleveldynamics/src/DyConstraintSetupBlock.cpp",
	"physx/source/lowleveldynamics/src/DyContactPrep.cpp",
	"physx/source/lowleveldynamics/src/DyContactPrep4.cpp",
	"physx/source/lowleveldynamics/src/DyContactPrep4PF.cpp",
	"physx/source/lowleveldynamics/src/DyContactPrepPF.cpp",
	"physx/source/lowleveldynamics/src/DyDynamics.cpp",
	"physx/source/lowleveldynamics/src/DyFrictionCorrelation.cpp",
	"physx/source/lowleveldynamics/src/DyRigidBodyToSolverBody.cpp",
	"physx/source/lowleveldynamics/src/DySolverConstraints.cpp",
	"physx/source/lowleveldynamics/src/DySolverConstraintsBlock.cpp",
	"physx/source/lowleveldynamics/src/DySolverControl.cpp",
	"physx/source/lowleveldynamics/src/DySolverControlPF.cpp",
	"physx/source/lowleveldynamics/src/DySolverPFConstraints.cpp",
	"physx/source/lowleveldynamics/src/DySolverPFConstraintsBlock.cpp",
	"physx/source/lowleveldynamics/src/DyThreadContext.cpp",
	"physx/source/lowleveldynamics/src/DyThresholdTable.cpp",
	"physx/source/lowleveldynamics/src/DyTGSDynamics.cpp",
	"physx/source/lowleveldynamics/src/DyTGSPartition.cpp",
	"physx/source/lowleveldynamics/src/DyTGSContactPrep.cpp",
	"physx/source/lowleveldynamics/src/DyTGSContactPrepBlock.cpp",
        ],
    hdrs = [
	"physx/source/lowleveldynamics/src/DyArticulationContactPrep.h",
	"physx/source/lowleveldynamics/src/DyArticulationFnsDebug.h",
	"physx/source/lowleveldynamics/src/DyArticulationFnsScalar.h",
	"physx/source/lowleveldynamics/src/DyArticulationFnsSimd.h",
	"physx/source/lowleveldynamics/src/DyArticulationHelper.h",
	"physx/source/lowleveldynamics/src/DyArticulationPImpl.h",
	"physx/source/lowleveldynamics/src/DyArticulationReference.h",
	"physx/source/lowleveldynamics/src/DyArticulationScalar.h",
	"physx/source/lowleveldynamics/src/DyArticulationUtils.h",
	"physx/source/lowleveldynamics/src/DyFeatherstoneArticulationLink.h",
	"physx/source/lowleveldynamics/src/DyBodyCoreIntegrator.h",
	"physx/source/lowleveldynamics/src/DyConstraintPartition.h",
	"physx/source/lowleveldynamics/src/DyConstraintPrep.h",
	"physx/source/lowleveldynamics/src/DyContactPrep.h",
	"physx/source/lowleveldynamics/src/DyContactPrepShared.h",
	"physx/source/lowleveldynamics/src/DyContactReduction.h",
	"physx/source/lowleveldynamics/src/DyCorrelationBuffer.h",
	"physx/source/lowleveldynamics/src/DyDynamics.h",
	"physx/source/lowleveldynamics/src/DyFrictionPatch.h",
	"physx/source/lowleveldynamics/src/DyFrictionPatchStreamPair.h",
	"physx/source/lowleveldynamics/src/DySolverBody.h",
	"physx/source/lowleveldynamics/src/DySolverConstraint1D.h",
	"physx/source/lowleveldynamics/src/DySolverConstraint1D4.h",
	"physx/source/lowleveldynamics/src/DySolverConstraintDesc.h",
	"physx/source/lowleveldynamics/src/DySolverConstraintExtShared.h",
	"physx/source/lowleveldynamics/src/DySolverConstraintsShared.h",
	"physx/source/lowleveldynamics/src/DySolverConstraintTypes.h",
	"physx/source/lowleveldynamics/src/DySolverContact.h",
	"physx/source/lowleveldynamics/src/DySolverContact4.h",
	"physx/source/lowleveldynamics/src/DySolverContactPF.h",
	"physx/source/lowleveldynamics/src/DySolverContactPF4.h",
	"physx/source/lowleveldynamics/src/DySolverContext.h",
	"physx/source/lowleveldynamics/src/DySolverControl.h",
	"physx/source/lowleveldynamics/src/DySolverControlPF.h",
	"physx/source/lowleveldynamics/src/DySolverCore.h",
	"physx/source/lowleveldynamics/src/DySolverExt.h",
	"physx/source/lowleveldynamics/src/DySpatial.h",
	"physx/source/lowleveldynamics/src/DyThreadContext.h",
	"physx/source/lowleveldynamics/src/DyTGSPartition.h",
	"physx/source/lowleveldynamics/src/DyTGSDynamics.h",
	"physx/source/lowleveldynamics/src/DySolverConstraint1DStep.h",
	"physx/source/lowleveldynamics/include/DyArticulationCore.h",
	"physx/source/lowleveldynamics/include/DyVArticulation.h",
	"physx/source/lowleveldynamics/include/DyArticulation.h",
	"physx/source/lowleveldynamics/include/DyFeatherstoneArticulation.h",
	"physx/source/lowleveldynamics/include/DyFeatherstoneArticulationJointData.h",
	"physx/source/lowleveldynamics/include/DyFeatherstoneArticulationUtils.h",
	"physx/source/lowleveldynamics/include/DyConstraint.h",
	"physx/source/lowleveldynamics/include/DyConstraintWriteBack.h",
	"physx/source/lowleveldynamics/include/DyContext.h",
	"physx/source/lowleveldynamics/include/DySleepingConfigulation.h",
	"physx/source/lowleveldynamics/include/DyThresholdTable.h",
	"physx/source/lowleveldynamics/include/DyArticulationJointCore.h",
        ],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    deps = [
        # ":PhysXFoundation",
        ],
    )

cc_library(
    name = "PhysXSimulationController",
    srcs = [
        "physx/source/simulationcontroller/src/ScActorCore.cpp",
        "physx/source/simulationcontroller/src/ScActorSim.cpp",
        "physx/source/simulationcontroller/src/ScArticulationCore.cpp",
        "physx/source/simulationcontroller/src/ScArticulationJointCore.cpp",
        "physx/source/simulationcontroller/src/ScArticulationJointSim.cpp",
        "physx/source/simulationcontroller/src/ScArticulationSim.cpp",
        "physx/source/simulationcontroller/src/ScBodyCore.cpp",
        "physx/source/simulationcontroller/src/ScBodySim.cpp",
        "physx/source/simulationcontroller/src/ScConstraintCore.cpp",
        "physx/source/simulationcontroller/src/ScConstraintGroupNode.cpp",
        "physx/source/simulationcontroller/src/ScConstraintInteraction.cpp",
        "physx/source/simulationcontroller/src/ScConstraintProjectionManager.cpp",
        "physx/source/simulationcontroller/src/ScConstraintProjectionTree.cpp",
        "physx/source/simulationcontroller/src/ScConstraintSim.cpp",
        "physx/source/simulationcontroller/src/ScElementInteractionMarker.cpp",
        "physx/source/simulationcontroller/src/ScElementSim.cpp",
        "physx/source/simulationcontroller/src/ScInteraction.cpp",
        "physx/source/simulationcontroller/src/ScIterators.cpp",
        "physx/source/simulationcontroller/src/ScMetaData.cpp",
        "physx/source/simulationcontroller/src/ScNPhaseCore.cpp",
        "physx/source/simulationcontroller/src/ScPhysics.cpp",
        "physx/source/simulationcontroller/src/ScRigidCore.cpp",
        "physx/source/simulationcontroller/src/ScRigidSim.cpp",
        "physx/source/simulationcontroller/src/ScScene.cpp",
        "physx/source/simulationcontroller/src/ScShapeCore.cpp",
        "physx/source/simulationcontroller/src/ScShapeInteraction.cpp",
        "physx/source/simulationcontroller/src/ScShapeSim.cpp",
        "physx/source/simulationcontroller/src/ScSimStats.cpp",
        "physx/source/simulationcontroller/src/ScSimulationController.cpp",
        "physx/source/simulationcontroller/src/ScSqBoundsManager.cpp",
        "physx/source/simulationcontroller/src/ScStaticCore.cpp",
        "physx/source/simulationcontroller/src/ScTriggerInteraction.cpp",
    ],
    hdrs = [
        "physx/source/simulationcontroller/include/ScActorCore.h",
        "physx/source/simulationcontroller/include/ScArticulationCore.h",
        "physx/source/simulationcontroller/include/ScArticulationJointCore.h",
        "physx/source/simulationcontroller/include/ScBodyCore.h",
        "physx/source/simulationcontroller/include/ScConstraintCore.h",
        "physx/source/simulationcontroller/include/ScIterators.h",
        "physx/source/simulationcontroller/include/ScMaterialCore.h",
        "physx/source/simulationcontroller/include/ScPhysics.h",
        "physx/source/simulationcontroller/include/ScRigidCore.h",
        "physx/source/simulationcontroller/include/ScScene.h",
        "physx/source/simulationcontroller/include/ScShapeCore.h",
        "physx/source/simulationcontroller/include/ScStaticCore.h",
        "physx/source/simulationcontroller/src/ScActorPair.h",
        "physx/source/simulationcontroller/src/ScActorSim.h",
        "physx/source/simulationcontroller/src/ScArticulationJointSim.h",
        "physx/source/simulationcontroller/src/ScArticulationSim.h",
        "physx/source/simulationcontroller/src/ScBodySim.h",
        "physx/source/simulationcontroller/src/ScClient.h",
        "physx/source/simulationcontroller/src/ScConstraintGroupNode.h",
        "physx/source/simulationcontroller/src/ScConstraintInteraction.h",
        "physx/source/simulationcontroller/src/ScConstraintProjectionManager.h",
        "physx/source/simulationcontroller/src/ScConstraintProjectionTree.h",
        "physx/source/simulationcontroller/src/ScConstraintSim.h",
        "physx/source/simulationcontroller/src/ScContactReportBuffer.h",
        "physx/source/simulationcontroller/src/ScContactStream.h",
        "physx/source/simulationcontroller/src/ScElementInteractionMarker.h",
        "physx/source/simulationcontroller/src/ScElementSim.h",
        "physx/source/simulationcontroller/src/ScElementSimInteraction.h",
        "physx/source/simulationcontroller/src/ScInteraction.h",
        "physx/source/simulationcontroller/src/ScInteractionFlags.h",
        "physx/source/simulationcontroller/src/ScNPhaseCore.h",
        "physx/source/simulationcontroller/src/ScObjectIDTracker.h",
        "physx/source/simulationcontroller/src/ScRigidSim.h",
        "physx/source/simulationcontroller/src/ScShapeInteraction.h",
        "physx/source/simulationcontroller/src/ScShapeSim.h",
        "physx/source/simulationcontroller/src/ScSimStateData.h",
        "physx/source/simulationcontroller/src/ScSimStats.h",
        "physx/source/simulationcontroller/src/ScSimulationController.h",
        "physx/source/simulationcontroller/src/ScSqBoundsManager.h",
        "physx/source/simulationcontroller/src/ScStaticSim.h",
        "physx/source/simulationcontroller/src/ScTriggerInteraction.h",
        "physx/source/simulationcontroller/src/ScTriggerPairs.h",
    ],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    includes = [
        "physx/include",
        "physx/include/common",
        "physx/include/geometry",
        "physx/include/geomutils",
        "physx/source",
        "physx/source/common/include",
        "physx/source/common/src",
        "physx/source/common/src/linux",
        "physx/source/foundation/include",
        "physx/source/geomutils/include",
        "physx/source/geomutils/src",
        "physx/source/geomutils/src/ccd",
        "physx/source/geomutils/src/common",
        "physx/source/geomutils/src/contact",
        "physx/source/geomutils/src/convex",
        "physx/source/geomutils/src/distance",
        "physx/source/geomutils/src/gjk",
        "physx/source/geomutils/src/hf",
        "physx/source/geomutils/src/intersection",
        "physx/source/geomutils/src/mesh",
        "physx/source/geomutils/src/pcm",
        "physx/source/geomutils/src/sweep",
        "physx/source/physx/src/buffering",
        "physx/source/physxgpu/include",
        "physx/source/simulationcontroller/include",
        "pxshared/include",
    ],
    deps = [
        ":PhysXCommon",
        # # TODO PhysXPvdSDK
        ":PhysXFoundation",
        ":PhysXLowLevel",
    ],
)

cc_library(
    name = "PhysX",
    srcs = [
        "physx/source/immediatemode/src/NpImmediateMode.cpp",
        "physx/source/physx/src/NpActor.cpp",
        "physx/source/physx/src/NpAggregate.cpp",
        "physx/source/physx/src/NpArticulation.cpp",
        "physx/source/physx/src/NpArticulationJoint.cpp",
        "physx/source/physx/src/NpArticulationJointReducedCoordinate.cpp",
        "physx/source/physx/src/NpArticulationLink.cpp",
        "physx/source/physx/src/NpArticulationReducedCoordinate.cpp",
        "physx/source/physx/src/NpBatchQuery.cpp",
        "physx/source/physx/src/NpConstraint.cpp",
        "physx/source/physx/src/NpFactory.cpp",
        "physx/source/physx/src/NpMaterial.cpp",
        "physx/source/physx/src/NpMetaData.cpp",
        "physx/source/physx/src/NpPhysics.cpp",
        "physx/source/physx/src/NpPvdSceneQueryCollector.cpp",
        "physx/source/physx/src/NpReadCheck.cpp",
        "physx/source/physx/src/NpRigidDynamic.cpp",
        "physx/source/physx/src/NpRigidStatic.cpp",
        "physx/source/physx/src/NpScene.cpp",
        "physx/source/physx/src/NpSceneQueries.cpp",
        "physx/source/physx/src/NpSerializerAdapter.cpp",
        "physx/source/physx/src/NpShape.cpp",
        "physx/source/physx/src/NpShapeManager.cpp",
        "physx/source/physx/src/NpWriteCheck.cpp",
        "physx/source/physx/src/PvdMetaDataPvdBinding.cpp",
        "physx/source/physx/src/PvdPhysicsClient.cpp",
        "physx/source/physx/src/buffering/ScbActor.cpp",
        "physx/source/physx/src/buffering/ScbAggregate.cpp",
        "physx/source/physx/src/buffering/ScbBase.cpp",
        "physx/source/physx/src/buffering/ScbMetaData.cpp",
        "physx/source/physx/src/buffering/ScbScene.cpp",
        "physx/source/physx/src/buffering/ScbScenePvdClient.cpp",
        "physx/source/physx/src/buffering/ScbShape.cpp",
        "physx/source/physxmetadata/core/src/PxAutoGeneratedMetaDataObjects.cpp",
        "physx/source/physxmetadata/core/src/PxMetaDataObjects.cpp",
    ],
    hdrs = [
        "physx/include/PxActor.h",
        "physx/include/PxAggregate.h",
        "physx/include/PxArticulation.h",
        "physx/include/PxArticulationBase.h",
        "physx/include/PxArticulationJoint.h",
        "physx/include/PxArticulationJointReducedCoordinate.h",
        "physx/include/PxArticulationLink.h",
        "physx/include/PxArticulationReducedCoordinate.h",
        "physx/include/PxBatchQuery.h",
        "physx/include/PxBatchQueryDesc.h",
        "physx/include/PxBroadPhase.h",
        "physx/include/PxClient.h",
        "physx/include/PxConstraint.h",
        "physx/include/PxConstraintDesc.h",
        "physx/include/PxContact.h",
        "physx/include/PxContactModifyCallback.h",
        "physx/include/PxDeletionListener.h",
        "physx/include/PxFiltering.h",
        "physx/include/PxForceMode.h",
        "physx/include/PxImmediateMode.h",
        "physx/include/PxLockedData.h",
        "physx/include/PxMaterial.h",
        "physx/include/PxPhysXConfig.h",
        "physx/include/PxPhysics.h",
        "physx/include/PxPhysicsAPI.h",
        "physx/include/PxPhysicsSerialization.h",
        "physx/include/PxPhysicsVersion.h",
        "physx/include/PxPruningStructure.h",
        "physx/include/PxQueryFiltering.h",
        "physx/include/PxQueryReport.h",
        "physx/include/PxRigidActor.h",
        "physx/include/PxRigidBody.h",
        "physx/include/PxRigidDynamic.h",
        "physx/include/PxRigidStatic.h",
        "physx/include/PxScene.h",
        "physx/include/PxSceneDesc.h",
        "physx/include/PxSceneLock.h",
        "physx/include/PxShape.h",
        "physx/include/PxSimulationEventCallback.h",
        "physx/include/PxSimulationStatistics.h",
        "physx/include/PxVisualizationParameter.h",
        "physx/include/pvd/PxPvd.h",
        "physx/include/pvd/PxPvdSceneClient.h",
        "physx/include/pvd/PxPvdTransport.h",
        "physx/include/solver/PxSolverDefs.h",
        "physx/source/physx/src/NpActor.h",
        "physx/source/physx/src/NpActorTemplate.h",
        "physx/source/physx/src/NpAggregate.h",
        "physx/source/physx/src/NpArticulation.h",
        "physx/source/physx/src/NpArticulationJoint.h",
        "physx/source/physx/src/NpArticulationJointReducedCoordinate.h",
        "physx/source/physx/src/NpArticulationLink.h",
        "physx/source/physx/src/NpArticulationReducedCoordinate.h",
        "physx/source/physx/src/NpArticulationTemplate.h",
        "physx/source/physx/src/NpBatchQuery.h",
        "physx/source/physx/src/NpCast.h",
        "physx/source/physx/src/NpConnector.h",
        "physx/source/physx/src/NpConstraint.h",
        "physx/source/physx/src/NpFactory.h",
        "physx/source/physx/src/NpMaterial.h",
        "physx/source/physx/src/NpMaterialManager.h",
        "physx/source/physx/src/NpPhysics.h",
        "physx/source/physx/src/NpPhysicsInsertionCallback.h",
        "physx/source/physx/src/NpPtrTableStorageManager.h",
        "physx/source/physx/src/NpPvdSceneQueryCollector.h",
        "physx/source/physx/src/NpQueryShared.h",
        "physx/source/physx/src/NpReadCheck.h",
        "physx/source/physx/src/NpRigidActorTemplate.h",
        "physx/source/physx/src/NpRigidActorTemplateInternal.h",
        "physx/source/physx/src/NpRigidBodyTemplate.h",
        "physx/source/physx/src/NpRigidDynamic.h",
        "physx/source/physx/src/NpRigidStatic.h",
        "physx/source/physx/src/NpScene.h",
        "physx/source/physx/src/NpSceneAccessor.h",
        "physx/source/physx/src/NpSceneQueries.h",
        "physx/source/physx/src/NpShape.h",
        "physx/source/physx/src/NpShapeManager.h",
        "physx/source/physx/src/NpWriteCheck.h",
        "physx/source/physx/src/PvdMetaDataBindingData.h",
        "physx/source/physx/src/PvdMetaDataPvdBinding.h",
        "physx/source/physx/src/PvdPhysicsClient.h",
        "physx/source/physx/src/PvdTypeNames.h",
        "physx/source/physx/src/buffering/ScbActor.h",
        "physx/source/physx/src/buffering/ScbAggregate.h",
        "physx/source/physx/src/buffering/ScbArticulation.h",
        "physx/source/physx/src/buffering/ScbArticulationJoint.h",
        "physx/source/physx/src/buffering/ScbBase.h",
        "physx/source/physx/src/buffering/ScbBody.h",
        "physx/source/physx/src/buffering/ScbConstraint.h",
        "physx/source/physx/src/buffering/ScbDefs.h",
        "physx/source/physx/src/buffering/ScbNpDeps.h",
        "physx/source/physx/src/buffering/ScbRigidObject.h",
        "physx/source/physx/src/buffering/ScbRigidStatic.h",
        "physx/source/physx/src/buffering/ScbScene.h",
        "physx/source/physx/src/buffering/ScbSceneBuffer.h",
        "physx/source/physx/src/buffering/ScbScenePvdClient.h",
        "physx/source/physx/src/buffering/ScbShape.h",
        "physx/source/physx/src/buffering/ScbType.h",
        "physx/source/physxmetadata/core/include/PvdMetaDataDefineProperties.h",
        "physx/source/physxmetadata/core/include/PvdMetaDataExtensions.h",
        "physx/source/physxmetadata/core/include/PvdMetaDataPropertyVisitor.h",
        "physx/source/physxmetadata/core/include/PxAutoGeneratedMetaDataObjectNames.h",
        "physx/source/physxmetadata/core/include/PxAutoGeneratedMetaDataObjects.h",
        "physx/source/physxmetadata/core/include/PxMetaDataCompare.h",
        "physx/source/physxmetadata/core/include/PxMetaDataCppPrefix.h",
        "physx/source/physxmetadata/core/include/PxMetaDataObjects.h",
        "physx/source/physxmetadata/core/include/RepXMetaDataPropertyVisitor.h",
    ],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    includes = [
        "physx/include",
        "physx/include/common",
        "physx/include/geometry",
        "physx/include/geomutils",
        "physx/source",
        "physx/source/common/include",
        "physx/source/common/src",
        "physx/source/common/src/linux",
        "physx/source/foundation/include",
        "physx/source/geomutils/include",
        "physx/source/geomutils/src",
        "physx/source/geomutils/src/ccd",
        "physx/source/geomutils/src/common",
        "physx/source/geomutils/src/contact",
        "physx/source/geomutils/src/convex",
        "physx/source/geomutils/src/distance",
        "physx/source/geomutils/src/gjk",
        "physx/source/geomutils/src/hf",
        "physx/source/geomutils/src/intersection",
        "physx/source/geomutils/src/mesh",
        "physx/source/geomutils/src/pcm",
        "physx/source/geomutils/src/sweep",
        "physx/source/physx/src/buffering",
        "physx/source/physxgpu/include",
        "pxshared/include",
    ],
    deps = [
        ":PhysXCommon",
        # TODO PhysXPvdSDK
        ":PhysXSimulationController",
        ":PhysXFoundation",
    ],
)

cc_library(
    name = "PhysXVehicle",
    srcs = [
        "physx/source/physxvehicle/src/PxVehicleComponents.cpp",
        "physx/source/physxvehicle/src/PxVehicleDrive.cpp",
        "physx/source/physxvehicle/src/PxVehicleDrive4W.cpp",
        "physx/source/physxvehicle/src/PxVehicleDriveNW.cpp",
        "physx/source/physxvehicle/src/PxVehicleDriveTank.cpp",
        "physx/source/physxvehicle/src/PxVehicleMetaData.cpp",
        "physx/source/physxvehicle/src/PxVehicleNoDrive.cpp",
        "physx/source/physxvehicle/src/PxVehicleSDK.cpp",
        "physx/source/physxvehicle/src/PxVehicleSerialization.cpp",
        "physx/source/physxvehicle/src/PxVehicleSuspWheelTire4.cpp",
        "physx/source/physxvehicle/src/PxVehicleTireFriction.cpp",
        "physx/source/physxvehicle/src/PxVehicleUpdate.cpp",
        "physx/source/physxvehicle/src/PxVehicleWheels.cpp",
        "physx/source/physxvehicle/src/VehicleUtilControl.cpp",
        "physx/source/physxvehicle/src/VehicleUtilSetup.cpp",
        "physx/source/physxvehicle/src/VehicleUtilTelemetry.cpp",
        "physx/source/physxvehicle/src/physxmetadata/src/PxVehicleAutoGeneratedMetaDataObjects.cpp",
        "physx/source/physxvehicle/src/physxmetadata/src/PxVehicleMetaDataObjects.cpp",
    ],
    hdrs = [
        "physx/include/vehicle/PxVehicleComponents.h",
        "physx/include/vehicle/PxVehicleDrive.h",
        "physx/include/vehicle/PxVehicleDrive4W.h",
        "physx/include/vehicle/PxVehicleDriveNW.h",
        "physx/include/vehicle/PxVehicleDriveTank.h",
        "physx/include/vehicle/PxVehicleNoDrive.h",
        "physx/include/vehicle/PxVehicleSDK.h",
        "physx/include/vehicle/PxVehicleShaders.h",
        "physx/include/vehicle/PxVehicleTireFriction.h",
        "physx/include/vehicle/PxVehicleUpdate.h",
        "physx/include/vehicle/PxVehicleUtil.h",
        "physx/include/vehicle/PxVehicleUtilControl.h",
        "physx/include/vehicle/PxVehicleUtilSetup.h",
        "physx/include/vehicle/PxVehicleUtilTelemetry.h",
        "physx/include/vehicle/PxVehicleWheels.h",
        "physx/source/physxvehicle/src/PxVehicleDefaults.h",
        "physx/source/physxvehicle/src/PxVehicleLinearMath.h",
        "physx/source/physxvehicle/src/PxVehicleSerialization.h",
        "physx/source/physxvehicle/src/PxVehicleSuspLimitConstraintShader.h",
        "physx/source/physxvehicle/src/PxVehicleSuspWheelTire4.h",
        "physx/source/physxvehicle/src/physxmetadata/include/PxVehicleAutoGeneratedMetaDataObjectNames.h",
        "physx/source/physxvehicle/src/physxmetadata/include/PxVehicleAutoGeneratedMetaDataObjects.h",
        "physx/source/physxvehicle/src/physxmetadata/include/PxVehicleMetaDataObjects.h",
    ],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    includes = [
        "physx/include",
        "physx/include/common",
        "physx/include/geometry",
        "physx/include/geomutils",
        "physx/include/vehicle",
        "physx/source",
        "physx/source/common/include",
        "physx/source/common/src",
        "physx/source/common/src/linux",
        "physx/source/foundation/include",
        "physx/source/geomutils/include",
        "physx/source/geomutils/src",
        "physx/source/geomutils/src/ccd",
        "physx/source/geomutils/src/common",
        "physx/source/geomutils/src/contact",
        "physx/source/geomutils/src/convex",
        "physx/source/geomutils/src/distance",
        "physx/source/geomutils/src/gjk",
        "physx/source/geomutils/src/hf",
        "physx/source/geomutils/src/intersection",
        "physx/source/geomutils/src/mesh",
        "physx/source/geomutils/src/pcm",
        "physx/source/geomutils/src/sweep",
        "physx/source/physxgpu/include",
        "physx/source/physxvehicle/src/physxmetadata/include",
        "pxshared/include",
    ],
    deps = [
        ":PhysX",
        ":PhysXCommon",
        ":PhysXFoundation",
        ":PhysXTask",
    ],
)

# cc_library(
#     name = "PhysXCommon",
#     srcs = glob(["physx/source/common/src/*.cpp"]),
#     hdrs =
#         glob(["physx/include/*.h"]) + glob([
#             "physx/include/common/*.h",
#         ]) + glob([
#             "physx/source/common/src/*.h",
#         ]) + glob([
#             "physx/source/foundation/include/*.h",
#         ]) + glob([
#             "physx/source/foundation/include/unix/*.h",
#         ]) + glob([
#             "physx/source/geomutils/include/*.h",
#         ]) +
#         # TODO: Move these to a separate (header-only) library?
#         glob([
#             "pxshared/include/foundation/*.h",
#         ]) + glob([
#             "pxshared/include/foundation/unix/*.h",
#         ]),
#     # srcs = [
#     #     "physx/source/common/src/CmBoxPruning.cpp",
#     #     ],
#     # glob(["physx/source/common/src/*.cpp"]),
#     defines = [
#         "PX_BUILD_NUMBER=0",
#         "PX_CHECKED=1",  # TODO, use optimized.
#         "PX_NVTX=0",  # TODO what is this?
#         "PX_PHYSX_STATIC_LIB",
#         "PX_SUPPORT_PVD=0",
#         "NDEBUG",
#     ],
#     includes = [
#         "physx/include",
#         "physx/include/common",
#         "physx/include/geometry",
#         "physx/include/geomutils",
#         "physx/source",
#         "physx/source/common/include",
#         "physx/source/common/src",
#         "physx/source/common/src/linux",
#         "physx/source/foundation/include",
#         "physx/source/geomutils/include",
#         "physx/source/geomutils/src",
#         "physx/source/geomutils/src/ccd",
#         "physx/source/geomutils/src/common",
#         "physx/source/geomutils/src/contact",
#         "physx/source/geomutils/src/convex",
#         "physx/source/geomutils/src/distance",
#         "physx/source/geomutils/src/gjk",
#         "physx/source/geomutils/src/hf",
#         "physx/source/geomutils/src/intersection",
#         "physx/source/geomutils/src/mesh",
#         "physx/source/geomutils/src/pcm",
#         "physx/source/geomutils/src/sweep",
#         "physx/source/physxgpu/include",
#         "pxshared/include",
#     ],
#     visibility = ["//visibility:public"],
#     deps = [
#         ":PhysXFoundation",
#     ],
# )

cc_binary(
    name = "testing",
    srcs = [":testing.cc"],
    defines = [
        "PX_BUILD_NUMBER=0",
        "PX_CHECKED=1",  # TODO, use optimized.
        "PX_NVTX=0",  # TODO what is this?
        "PX_PHYSX_STATIC_LIB",
        "PX_SUPPORT_PVD=0",
        "NDEBUG",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":PhysXCommon",
        ":PhysXFoundation",
        ":PhysXVehicle",
    ],
    # includes are relative to where the rule is
    # copts are relative to workspace.
    # includes = [
    #     "pxshared/include",
    #     ],
)
