NVIDIA(R) PhysX(R) SDK 3.4 API Reference: PxPlane Class Reference
Main Page Class Hierarchy Compound List Compound Members
PxPlane Class Reference
[Foundation]
Representation of a plane.
#include <PxPlane.h>
Public Member Functions
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane ()
Constructor.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane (float nx, float ny, float nz, float distance)
Constructor from a normal and a distance.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane (const PxVec3 &normal, float distance)
Constructor from a normal and a distance.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane (const PxVec3 &point, const PxVec3 &normal)
Constructor from a point on the plane and a normal.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane (const PxVec3 &p0, const PxVec3 &p1, const PxVec3 &p2)
Constructor from three points.
PX_CUDA_CALLABLE PX_INLINE bool operator== (const PxPlane &p) const
returns true if the two planes are exactly equal
PX_CUDA_CALLABLE
PX_FORCE_INLINE float distance (const PxVec3 &p) const
PX_CUDA_CALLABLE
PX_FORCE_INLINE bool contains (const PxVec3 &p) const
PX_CUDA_CALLABLE
PX_FORCE_INLINE PxVec3 project (const PxVec3 &p) const
projects p into the plane
PX_CUDA_CALLABLE
PX_FORCE_INLINE PxVec3 pointInPlane () const
find an arbitrary point in the plane
PX_CUDA_CALLABLE
PX_FORCE_INLINE void normalize ()
equivalent plane with unit normal
Public Attributes
PxVec3 n
The normal to the plane.
float d
The distance from the origin.
Detailed Description
Representation of a plane.
Plane equation used: n.dot(v) + d = 0
Constructor & Destructor Documentation
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane::PxPlane () [inline]
Constructor.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane::PxPlane (float nx, float ny, float nz, float distance) [inline]
Constructor from a normal and a distance.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane::PxPlane (const PxVec3 & normal, float distance) [inline]
Constructor from a normal and a distance.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane::PxPlane (const PxVec3 & point, const PxVec3 & normal) [inline]
Constructor from a point on the plane and a normal.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxPlane::PxPlane (const PxVec3 & p0, const PxVec3 & p1, const PxVec3 & p2) [inline]
Constructor from three points.
References PxVec3::dot().
Member Function Documentation
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxPlane::contains (const PxVec3 & p) const [inline]
References PxAbs().
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxPlane::distance (const PxVec3 & p) const [inline]
References PxVec3::dot().
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxPlane::normalize () [inline]
equivalent plane with unit normal
PX_CUDA_CALLABLE PX_INLINE bool PxPlane::operator== (const PxPlane & p) const [inline]
returns true if the two planes are exactly equal
References d, and n.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxPlane::pointInPlane () const [inline]
find an arbitrary point in the plane
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxPlane::project (const PxVec3 & p) const [inline]
projects p into the plane
Member Data Documentation
float PxPlane::d
The distance from the origin.
Referenced by PxTransform::inverseTransform(), operator==(), and PxTransform::transform().
PxVec3 PxPlane::n
The normal to the plane.
Referenced by PxTransform::inverseTransform(), operator==(), and PxTransform::transform().
The documentation for this class was generated from the following file:
PxPlane.h
Copyright © 2008-2018 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com