NVIDIA(R) PhysX(R) SDK 3.4 API Reference: Cooking
Main Page Class Hierarchy Compound List Compound Members
Cooking
Classes
struct PxMeshCookingHint
Enumeration for mesh cooking hints.
struct PxBVH33MidphaseDesc
Structure describing parameters affecting BVH33 midphase mesh structure.
struct PxBVH34MidphaseDesc
Structure describing parameters affecting BVH34 midphase mesh structure.
struct PxConvexFlag
Flags which describe the format and behavior of a convex mesh.
class PxConvexMeshDesc
Descriptor class for PxConvexMesh.
struct PxPlatform
struct PxConvexMeshCookingResult
Result from convex cooking.
struct PxConvexMeshCookingType
Enumeration for convex mesh cooking algorithms.
struct PxTriangleMeshCookingResult
Result from triangle mesh cooking.
struct PxMeshPreprocessingFlag
Enum for the set of mesh pre-processing parameters.
struct PxCookingParams
Structure describing parameters affecting mesh cooking.
class PxCooking
class PxMidphaseDesc
Structure describing parameters affecting midphase mesh structure.
class PxTriangleMeshDesc
Descriptor class for PxTriangleMesh.
class PxClothMeshDesc
Descriptor class for a cloth mesh.
Typedefs
typedef PxFlags
< PxConvexFlag::Enum, PxU16 > PxConvexFlags
collection of set bits defined in PxConvexFlag.
typedef PxFlags
< PxMeshPreprocessingFlag::Enum,
PxU32 > PxMeshPreprocessingFlags
Functions
PX_DEPRECATED PX_FORCE_INLINE PxU32 PxGetGaussMapVertexLimitForPlatform (PxPlatform::Enum targetPlatform)
PX_C_EXPORT
PX_PHYSX_COOKING_API
physx::PxCooking *PX_CALL_CONV PxCreateCooking (physx::PxU32 version, physx::PxFoundation &foundation, const physx::PxCookingParams &params)
Create an instance of the cooking interface.
PX_INLINE PxConvexMeshDesc::PxConvexMeshDesc ()
constructor sets to default.
PX_INLINE void PxConvexMeshDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxConvexMeshDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxTriangleMeshDesc::PxTriangleMeshDesc ()
Constructor sets to default.
PX_INLINE void PxTriangleMeshDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxTriangleMeshDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxClothMeshDesc::PxClothMeshDesc ()
constructor sets to default.
PX_INLINE void PxClothMeshDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxClothMeshDesc::isValid () const
Returns true if the descriptor is valid.
Typedef Documentation
typedef PxFlags<PxConvexFlag::Enum,PxU16> PxConvexFlags
collection of set bits defined in PxConvexFlag.
See also:
PxConvexFlag
typedef PxFlags<PxMeshPreprocessingFlag::Enum,PxU32> PxMeshPreprocessingFlags
Function Documentation
PX_INLINE bool PxClothMeshDesc::isValid () const [inherited]
Returns true if the descriptor is valid.
Returns:
True if the current settings are valid
References PxBoundedData::count, PxStridedData::data, PxMeshFlag::e16_BIT_INDICES, PxClothMeshDesc::flags, PxClothMeshDesc::invMasses, PxClothMeshDesc::points, PxClothMeshDesc::quads, PxStridedData::stride, and PxClothMeshDesc::triangles.
PX_INLINE bool PxTriangleMeshDesc::isValid () const [inherited]
Returns true if the descriptor is valid.
Returns:
true if the current settings are valid
Reimplemented from PxSimpleTriangleMesh.
References PxBoundedData::count, PxTypedStridedData< TDataType >::data, PxStridedData::data, PxTriangleMeshDesc::materialIndices, PxSimpleTriangleMesh::points, PxTypedStridedData< TDataType >::stride, and PxSimpleTriangleMesh::triangles.
PX_INLINE bool PxConvexMeshDesc::isValid () const [inherited]
Returns true if the descriptor is valid.
Returns:
True if the current settings are valid
References PxBoundedData::count, PxStridedData::data, PxConvexFlag::e16_BIT_INDICES, PxConvexFlag::eCOMPUTE_CONVEX, PxConvexFlag::ePLANE_SHIFTING, PxConvexMeshDesc::flags, PxConvexMeshDesc::indices, PxConvexMeshDesc::points, PxConvexMeshDesc::polygons, PxConvexMeshDesc::quantizedCount, PxStridedData::stride, and PxConvexMeshDesc::vertexLimit.
PX_INLINE PxClothMeshDesc::PxClothMeshDesc () [inherited]
constructor sets to default.
Referenced by PxClothMeshDesc::setToDefault().
PX_INLINE PxConvexMeshDesc::PxConvexMeshDesc () [inherited]
constructor sets to default.
Referenced by PxConvexMeshDesc::setToDefault().
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCooking* PX_CALL_CONV PxCreateCooking (physx::PxU32 version, physx::PxFoundation & foundation, const physx::PxCookingParams & params)
Create an instance of the cooking interface.
Note that the foundation object is handled as an application-wide singleton in statically linked executables and a DLL-wide singleton in dynamically linked executables. Therefore, if you are using the runtime SDK in the same executable as cooking, you should pass the Physics's copy of foundation (acquired with PxPhysics::getFoundation()) to the cooker. This will also ensure correct handling of memory for objects passed from the cooker to the SDK.
To use cooking in standalone mode, create an instance of the Foundation object with PxCreateCookingFoundation. You should pass the same foundation object to all instances of the cooking interface.
Parameters:
[in] version the SDK version number
[in] foundation the foundation object associated with this instance of the cooking interface.
[in] params the parameters for this instance of the cooking interface
Returns:
true on success.
PX_DEPRECATED PX_FORCE_INLINE PxU32 PxGetGaussMapVertexLimitForPlatform (PxPlatform::Enum targetPlatform)
References PxPlatform::eARM, PxPlatform::ePC, and PX_ASSERT_WITH_MESSAGE.
Referenced by PxCookingParams::PxCookingParams().
PX_INLINE PxTriangleMeshDesc::PxTriangleMeshDesc () [inherited]
Constructor sets to default.
References PxTriangleMeshDesc::setToDefault().
Referenced by PxTriangleMeshDesc::setToDefault().
PX_INLINE void PxClothMeshDesc::setToDefault () [inherited]
(re)sets the structure to the default.
References PxClothMeshDesc::PxClothMeshDesc().
PX_INLINE void PxTriangleMeshDesc::setToDefault () [inherited]
(re)sets the structure to the default.
Reimplemented from PxSimpleTriangleMesh.
References PxTriangleMeshDesc::PxTriangleMeshDesc().
Referenced by PxTriangleMeshDesc::PxTriangleMeshDesc().
PX_INLINE void PxConvexMeshDesc::setToDefault () [inherited]
(re)sets the structure to the default.
References PxConvexMeshDesc::PxConvexMeshDesc().
Copyright © 2008-2018 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com