NVIDIA(R) PhysX(R) SDK 3.4 API Reference: particles (deprecated)
Main Page Class Hierarchy Compound List Compound Members
particles (deprecated)
Classes
class PxParticleBase
The particle base class represents the shared module for particle based simulation. This class can't be instantiated. (deprecated).
struct PxParticleBaseFlag
ParticleBase flags (deprecated).
class PxParticleCreationData
Descriptor-like user-side class describing buffers for particle creation. (deprecated).
struct PxParticleFlag
class PxParticleFluid
The particle fluid class represents the main module for particle based fluid simulation. (deprecated) SPH (Smoothed Particle Hydrodynamics) is used to animate the particles. This class inherits the properties of the PxParticleBase class and adds particle-particle interactions.
class PxParticleFluidReadData
Data layout descriptor for reading fluid particle data from the SDK. (deprecated).
struct PxParticleReadDataFlag
class PxParticleReadData
Data layout descriptor for reading particle data from the SDK. (deprecated).
class PxParticleSystem
The particle system class represents the main module for particle based simulation. (deprecated).
Typedefs
typedef PX_DEPRECATED PxFlags
< PxParticleBaseFlag::Enum,
PxU16 > PxParticleBaseFlags
collection of set bits defined in PxParticleBaseFlag. (deprecated)
typedef PX_DEPRECATED PxFlags
< PxParticleReadDataFlag::Enum,
PxU16 > PxParticleReadDataFlags
collection of set bits defined in PxParticleReadDataFlag. (deprecated)
typedef PX_DEPRECATED PxFlags
< PxParticleFlag::Enum, PxU16 > PxParticleFlags
collection of set bits defined in PxParticleFlag. (deprecated)
Functions
PX_INLINE PxParticleCreationData::PxParticleCreationData ()
Constructor sets to default.
PX_INLINE void PxParticleCreationData::setToDefault ()
(Re)sets the structure to the default.
PX_INLINE bool PxParticleCreationData::isValid () const
Returns true if the current settings are valid.
Detailed Description
Typedef Documentation
typedef PX_DEPRECATED PxFlags<PxParticleBaseFlag::Enum, PxU16> PxParticleBaseFlags
collection of set bits defined in PxParticleBaseFlag. (deprecated)
Deprecated:
The PhysX particle feature has been deprecated in PhysX version 3.4
See also:
PxParticleBaseFlag
typedef PX_DEPRECATED PxFlags<PxParticleFlag::Enum, PxU16> PxParticleFlags
collection of set bits defined in PxParticleFlag. (deprecated)
Deprecated:
The PhysX particle feature has been deprecated in PhysX version 3.4
See also:
PxParticleFlag
typedef PX_DEPRECATED PxFlags<PxParticleReadDataFlag::Enum, PxU16> PxParticleReadDataFlags
collection of set bits defined in PxParticleReadDataFlag. (deprecated)
Deprecated:
The PhysX particle feature has been deprecated in PhysX version 3.4
See also:
PxParticleReadDataFlag
Function Documentation
PX_INLINE bool PxParticleCreationData::isValid () const [inherited]
Returns true if the current settings are valid.
References PxParticleCreationData::indexBuffer, PxParticleCreationData::numParticles, PxParticleCreationData::positionBuffer, and PxStrideIterator< T >::ptr().
PX_INLINE PxParticleCreationData::PxParticleCreationData () [inherited]
Constructor sets to default.
References PxParticleCreationData::flagBuffer, PxParticleCreationData::indexBuffer, PxParticleCreationData::positionBuffer, PxParticleCreationData::restOffsetBuffer, and PxParticleCreationData::velocityBuffer.
Referenced by PxParticleCreationData::setToDefault().
PX_INLINE void PxParticleCreationData::setToDefault () [inherited]
(Re)sets the structure to the default.
References PxParticleCreationData::PxParticleCreationData().
Copyright © 2008-2018 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com