# Makefile generated by XPJ for OSX64
-include Makefile.custom
ProjectName = SimulationController
SimulationController_custom_cflags := -isysroot $(APPLE_OSX_SDK_CURRENT_VERSION)
SimulationController_custom_lflags := -isysroot $(APPLE_OSX_SDK_CURRENT_VERSION)
SimulationController_cppfiles   += ./../../SimulationController/src/ScActorCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScActorSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScArticulationCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScArticulationJointCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScArticulationJointSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScArticulationSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScBodyCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScBodyCoreKinematic.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScBodySim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScConstraintCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScConstraintGroupNode.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScConstraintInteraction.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScConstraintProjectionManager.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScConstraintProjectionTree.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScConstraintSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScElementInteractionMarker.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScElementSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScInteraction.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScIterators.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScMaterialCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScMetaData.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScNPhaseCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScPhysics.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScRigidCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScRigidSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScScene.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScShapeCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScShapeInteraction.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScShapeSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScSimStats.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScSimulationController.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScSqBoundsManager.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScStaticCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScStaticSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/ScTriggerInteraction.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/particles/ScParticleBodyInteraction.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/particles/ScParticlePacketShape.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/particles/ScParticleSystemCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/particles/ScParticleSystemSim.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/cloth/ScClothCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/cloth/ScClothFabricCore.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/cloth/ScClothShape.cpp
SimulationController_cppfiles   += ./../../SimulationController/src/cloth/ScClothSim.cpp

SimulationController_cpp_debug_dep    = $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SimulationController_cppfiles)))))
SimulationController_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SimulationController_ccfiles)))))
SimulationController_c_debug_dep      = $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SimulationController_cfiles)))))
SimulationController_debug_dep      = $(SimulationController_cpp_debug_dep) $(SimulationController_cc_debug_dep) $(SimulationController_c_debug_dep)
-include $(SimulationController_debug_dep)
SimulationController_cpp_checked_dep    = $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SimulationController_cppfiles)))))
SimulationController_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SimulationController_ccfiles)))))
SimulationController_c_checked_dep      = $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SimulationController_cfiles)))))
SimulationController_checked_dep      = $(SimulationController_cpp_checked_dep) $(SimulationController_cc_checked_dep) $(SimulationController_c_checked_dep)
-include $(SimulationController_checked_dep)
SimulationController_cpp_profile_dep    = $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SimulationController_cppfiles)))))
SimulationController_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SimulationController_ccfiles)))))
SimulationController_c_profile_dep      = $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SimulationController_cfiles)))))
SimulationController_profile_dep      = $(SimulationController_cpp_profile_dep) $(SimulationController_cc_profile_dep) $(SimulationController_c_profile_dep)
-include $(SimulationController_profile_dep)
SimulationController_cpp_release_dep    = $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SimulationController_cppfiles)))))
SimulationController_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SimulationController_ccfiles)))))
SimulationController_c_release_dep      = $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SimulationController_cfiles)))))
SimulationController_release_dep      = $(SimulationController_cpp_release_dep) $(SimulationController_cc_release_dep) $(SimulationController_c_release_dep)
-include $(SimulationController_release_dep)
SimulationController_debug_hpaths    := 
SimulationController_debug_hpaths    += ./../../Common/include
SimulationController_debug_hpaths    += ./../../../../PxShared/include
SimulationController_debug_hpaths    += ./../../../../PxShared/src/foundation/include
SimulationController_debug_hpaths    += ./../../../../PxShared/src/fastxml/include
SimulationController_debug_hpaths    += ./../../../../PxShared/src/pvd/include
SimulationController_debug_hpaths    += ./../../../Include/common
SimulationController_debug_hpaths    += ./../../../Include/geometry
SimulationController_debug_hpaths    += ./../../../Include/GeomUtils
SimulationController_debug_hpaths    += ./../../../Include/pvd
SimulationController_debug_hpaths    += ./../../../Include/particles
SimulationController_debug_hpaths    += ./../../../Include/cloth
SimulationController_debug_hpaths    += ./../../../Include
SimulationController_debug_hpaths    += ./../../Common/src
SimulationController_debug_hpaths    += ./../../Common/src/unix
SimulationController_debug_hpaths    += ./../../GeomUtils/headers
SimulationController_debug_hpaths    += ./../../GeomUtils/src
SimulationController_debug_hpaths    += ./../../GeomUtils/src/contact
SimulationController_debug_hpaths    += ./../../GeomUtils/src/common
SimulationController_debug_hpaths    += ./../../GeomUtils/src/convex
SimulationController_debug_hpaths    += ./../../GeomUtils/src/distance
SimulationController_debug_hpaths    += ./../../GeomUtils/src/sweep
SimulationController_debug_hpaths    += ./../../GeomUtils/src/gjk
SimulationController_debug_hpaths    += ./../../GeomUtils/src/intersection
SimulationController_debug_hpaths    += ./../../GeomUtils/src/mesh
SimulationController_debug_hpaths    += ./../../GeomUtils/src/hf
SimulationController_debug_hpaths    += ./../../GeomUtils/src/pcm
SimulationController_debug_hpaths    += ./../../GeomUtils/src/ccd
SimulationController_debug_hpaths    += ./../../SimulationController/include
SimulationController_debug_hpaths    += ./../../SimulationController/src
SimulationController_debug_hpaths    += ./../../SimulationController/src/particles
SimulationController_debug_hpaths    += ./../../SimulationController/src/cloth
SimulationController_debug_hpaths    += ./../../LowLevel/unix/include
SimulationController_debug_hpaths    += ./../../LowLevel/API/include
SimulationController_debug_hpaths    += ./../../LowLevel/software/include
SimulationController_debug_hpaths    += ./../../LowLevel/common/include/math
SimulationController_debug_hpaths    += ./../../LowLevel/common/include/utils
SimulationController_debug_hpaths    += ./../../LowLevel/common/include/collision
SimulationController_debug_hpaths    += ./../../LowLevel/common/include/pipeline
SimulationController_debug_hpaths    += ./../../LowLevelCloth/include
SimulationController_debug_hpaths    += ./../../LowLevelAABB/include
SimulationController_debug_hpaths    += ./../../LowLevelDynamics/include
SimulationController_debug_hpaths    += ./../../LowLevelParticles/include
SimulationController_debug_lpaths    := 
SimulationController_debug_defines   := $(SimulationController_custom_defines)
SimulationController_debug_defines   += PX_PHYSX_STATIC_LIB
SimulationController_debug_defines   += _DEBUG
SimulationController_debug_defines   += PX_DEBUG=1
SimulationController_debug_defines   += PX_CHECKED=1
SimulationController_debug_defines   += PX_SUPPORT_PVD=1
SimulationController_debug_libraries := 
SimulationController_debug_common_cflags	:= $(SimulationController_custom_cflags)
SimulationController_debug_common_cflags    += -MMD
SimulationController_debug_common_cflags    += $(addprefix -D, $(SimulationController_debug_defines))
SimulationController_debug_common_cflags    += $(addprefix -I, $(SimulationController_debug_hpaths))
SimulationController_debug_cflags	:= $(SimulationController_debug_common_cflags)
SimulationController_debug_cflags  += -arch x86_64
SimulationController_debug_cflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_debug_cflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_debug_cflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_debug_cflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_debug_cflags  += -Wno-c++11-extensions
SimulationController_debug_cflags  += -g3 -gdwarf-2 -O0
SimulationController_debug_cppflags	:= $(SimulationController_debug_common_cflags)
SimulationController_debug_cppflags  += -arch x86_64
SimulationController_debug_cppflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_debug_cppflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_debug_cppflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_debug_cppflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_debug_cppflags  += -Wno-c++11-extensions
SimulationController_debug_cppflags  += -g3 -gdwarf-2 -O0
SimulationController_debug_lflags    := $(SimulationController_custom_lflags)
SimulationController_debug_lflags    += $(addprefix -L, $(SimulationController_debug_lpaths))
SimulationController_debug_lflags  += $(addprefix -l, $(SimulationController_debug_libraries))
SimulationController_debug_lflags  += -arch x86_64
SimulationController_debug_lflags  += -stdlib=libc++
SimulationController_debug_objsdir  = $(OBJS_DIR)/SimulationController_debug
SimulationController_debug_cpp_o    = $(addprefix $(SimulationController_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SimulationController_cppfiles)))))
SimulationController_debug_cc_o    = $(addprefix $(SimulationController_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SimulationController_ccfiles)))))
SimulationController_debug_c_o      = $(addprefix $(SimulationController_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SimulationController_cfiles)))))
SimulationController_debug_obj      = $(SimulationController_debug_cpp_o) $(SimulationController_debug_cc_o) $(SimulationController_debug_c_o)
SimulationController_debug_bin      := ./../../../Lib/osx64/libSimulationControllerDEBUG.a

clean_SimulationController_debug: 
	@$(ECHO) clean SimulationController debug
	@$(RMDIR) $(SimulationController_debug_objsdir)
	@$(RMDIR) $(SimulationController_debug_bin)
	@$(RMDIR) $(DEPSDIR)/SimulationController/debug

build_SimulationController_debug: postbuild_SimulationController_debug
postbuild_SimulationController_debug: mainbuild_SimulationController_debug
mainbuild_SimulationController_debug: prebuild_SimulationController_debug $(SimulationController_debug_bin)
prebuild_SimulationController_debug:

$(SimulationController_debug_bin): $(SimulationController_debug_obj) 
	mkdir -p `dirname ./../../../Lib/osx64/libSimulationControllerDEBUG.a`
	@$(AR) rcs $(SimulationController_debug_bin) $(SimulationController_debug_obj)
	$(ECHO) building $@ complete!

SimulationController_debug_DEPDIR = $(dir $(@))/$(*F)
$(SimulationController_debug_cpp_o): $(SimulationController_debug_objsdir)/%.o:
	$(ECHO) SimulationController: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cppfiles))))))
	cp $(SimulationController_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  rm -f $(SimulationController_debug_DEPDIR).d

$(SimulationController_debug_cc_o): $(SimulationController_debug_objsdir)/%.o:
	$(ECHO) SimulationController: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_ccfiles))))))
	cp $(SimulationController_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_ccfiles))))).debug.P; \
	  rm -f $(SimulationController_debug_DEPDIR).d

$(SimulationController_debug_c_o): $(SimulationController_debug_objsdir)/%.o:
	$(ECHO) SimulationController: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SimulationController_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cfiles))))))
	cp $(SimulationController_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_debug_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  rm -f $(SimulationController_debug_DEPDIR).d

SimulationController_checked_hpaths    := 
SimulationController_checked_hpaths    += ./../../Common/include
SimulationController_checked_hpaths    += ./../../../../PxShared/include
SimulationController_checked_hpaths    += ./../../../../PxShared/src/foundation/include
SimulationController_checked_hpaths    += ./../../../../PxShared/src/fastxml/include
SimulationController_checked_hpaths    += ./../../../../PxShared/src/pvd/include
SimulationController_checked_hpaths    += ./../../../Include/common
SimulationController_checked_hpaths    += ./../../../Include/geometry
SimulationController_checked_hpaths    += ./../../../Include/GeomUtils
SimulationController_checked_hpaths    += ./../../../Include/pvd
SimulationController_checked_hpaths    += ./../../../Include/particles
SimulationController_checked_hpaths    += ./../../../Include/cloth
SimulationController_checked_hpaths    += ./../../../Include
SimulationController_checked_hpaths    += ./../../Common/src
SimulationController_checked_hpaths    += ./../../Common/src/unix
SimulationController_checked_hpaths    += ./../../GeomUtils/headers
SimulationController_checked_hpaths    += ./../../GeomUtils/src
SimulationController_checked_hpaths    += ./../../GeomUtils/src/contact
SimulationController_checked_hpaths    += ./../../GeomUtils/src/common
SimulationController_checked_hpaths    += ./../../GeomUtils/src/convex
SimulationController_checked_hpaths    += ./../../GeomUtils/src/distance
SimulationController_checked_hpaths    += ./../../GeomUtils/src/sweep
SimulationController_checked_hpaths    += ./../../GeomUtils/src/gjk
SimulationController_checked_hpaths    += ./../../GeomUtils/src/intersection
SimulationController_checked_hpaths    += ./../../GeomUtils/src/mesh
SimulationController_checked_hpaths    += ./../../GeomUtils/src/hf
SimulationController_checked_hpaths    += ./../../GeomUtils/src/pcm
SimulationController_checked_hpaths    += ./../../GeomUtils/src/ccd
SimulationController_checked_hpaths    += ./../../SimulationController/include
SimulationController_checked_hpaths    += ./../../SimulationController/src
SimulationController_checked_hpaths    += ./../../SimulationController/src/particles
SimulationController_checked_hpaths    += ./../../SimulationController/src/cloth
SimulationController_checked_hpaths    += ./../../LowLevel/unix/include
SimulationController_checked_hpaths    += ./../../LowLevel/API/include
SimulationController_checked_hpaths    += ./../../LowLevel/software/include
SimulationController_checked_hpaths    += ./../../LowLevel/common/include/math
SimulationController_checked_hpaths    += ./../../LowLevel/common/include/utils
SimulationController_checked_hpaths    += ./../../LowLevel/common/include/collision
SimulationController_checked_hpaths    += ./../../LowLevel/common/include/pipeline
SimulationController_checked_hpaths    += ./../../LowLevelCloth/include
SimulationController_checked_hpaths    += ./../../LowLevelAABB/include
SimulationController_checked_hpaths    += ./../../LowLevelDynamics/include
SimulationController_checked_hpaths    += ./../../LowLevelParticles/include
SimulationController_checked_lpaths    := 
SimulationController_checked_defines   := $(SimulationController_custom_defines)
SimulationController_checked_defines   += PX_PHYSX_STATIC_LIB
SimulationController_checked_defines   += NDEBUG
SimulationController_checked_defines   += PX_CHECKED=1
SimulationController_checked_defines   += PX_SUPPORT_PVD=1
SimulationController_checked_libraries := 
SimulationController_checked_common_cflags	:= $(SimulationController_custom_cflags)
SimulationController_checked_common_cflags    += -MMD
SimulationController_checked_common_cflags    += $(addprefix -D, $(SimulationController_checked_defines))
SimulationController_checked_common_cflags    += $(addprefix -I, $(SimulationController_checked_hpaths))
SimulationController_checked_cflags	:= $(SimulationController_checked_common_cflags)
SimulationController_checked_cflags  += -arch x86_64
SimulationController_checked_cflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_checked_cflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_checked_cflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_checked_cflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_checked_cflags  += -Wno-c++11-extensions
SimulationController_checked_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SimulationController_checked_cppflags	:= $(SimulationController_checked_common_cflags)
SimulationController_checked_cppflags  += -arch x86_64
SimulationController_checked_cppflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_checked_cppflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_checked_cppflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_checked_cppflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_checked_cppflags  += -Wno-c++11-extensions
SimulationController_checked_cppflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SimulationController_checked_lflags    := $(SimulationController_custom_lflags)
SimulationController_checked_lflags    += $(addprefix -L, $(SimulationController_checked_lpaths))
SimulationController_checked_lflags  += $(addprefix -l, $(SimulationController_checked_libraries))
SimulationController_checked_lflags  += -arch x86_64
SimulationController_checked_lflags  += -stdlib=libc++
SimulationController_checked_objsdir  = $(OBJS_DIR)/SimulationController_checked
SimulationController_checked_cpp_o    = $(addprefix $(SimulationController_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SimulationController_cppfiles)))))
SimulationController_checked_cc_o    = $(addprefix $(SimulationController_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SimulationController_ccfiles)))))
SimulationController_checked_c_o      = $(addprefix $(SimulationController_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SimulationController_cfiles)))))
SimulationController_checked_obj      = $(SimulationController_checked_cpp_o) $(SimulationController_checked_cc_o) $(SimulationController_checked_c_o)
SimulationController_checked_bin      := ./../../../Lib/osx64/libSimulationControllerCHECKED.a

clean_SimulationController_checked: 
	@$(ECHO) clean SimulationController checked
	@$(RMDIR) $(SimulationController_checked_objsdir)
	@$(RMDIR) $(SimulationController_checked_bin)
	@$(RMDIR) $(DEPSDIR)/SimulationController/checked

build_SimulationController_checked: postbuild_SimulationController_checked
postbuild_SimulationController_checked: mainbuild_SimulationController_checked
mainbuild_SimulationController_checked: prebuild_SimulationController_checked $(SimulationController_checked_bin)
prebuild_SimulationController_checked:

$(SimulationController_checked_bin): $(SimulationController_checked_obj) 
	mkdir -p `dirname ./../../../Lib/osx64/libSimulationControllerCHECKED.a`
	@$(AR) rcs $(SimulationController_checked_bin) $(SimulationController_checked_obj)
	$(ECHO) building $@ complete!

SimulationController_checked_DEPDIR = $(dir $(@))/$(*F)
$(SimulationController_checked_cpp_o): $(SimulationController_checked_objsdir)/%.o:
	$(ECHO) SimulationController: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cppfiles))))))
	cp $(SimulationController_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  rm -f $(SimulationController_checked_DEPDIR).d

$(SimulationController_checked_cc_o): $(SimulationController_checked_objsdir)/%.o:
	$(ECHO) SimulationController: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_ccfiles))))))
	cp $(SimulationController_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_ccfiles))))).checked.P; \
	  rm -f $(SimulationController_checked_DEPDIR).d

$(SimulationController_checked_c_o): $(SimulationController_checked_objsdir)/%.o:
	$(ECHO) SimulationController: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SimulationController_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cfiles))))))
	cp $(SimulationController_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_checked_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  rm -f $(SimulationController_checked_DEPDIR).d

SimulationController_profile_hpaths    := 
SimulationController_profile_hpaths    += ./../../Common/include
SimulationController_profile_hpaths    += ./../../../../PxShared/include
SimulationController_profile_hpaths    += ./../../../../PxShared/src/foundation/include
SimulationController_profile_hpaths    += ./../../../../PxShared/src/fastxml/include
SimulationController_profile_hpaths    += ./../../../../PxShared/src/pvd/include
SimulationController_profile_hpaths    += ./../../../Include/common
SimulationController_profile_hpaths    += ./../../../Include/geometry
SimulationController_profile_hpaths    += ./../../../Include/GeomUtils
SimulationController_profile_hpaths    += ./../../../Include/pvd
SimulationController_profile_hpaths    += ./../../../Include/particles
SimulationController_profile_hpaths    += ./../../../Include/cloth
SimulationController_profile_hpaths    += ./../../../Include
SimulationController_profile_hpaths    += ./../../Common/src
SimulationController_profile_hpaths    += ./../../Common/src/unix
SimulationController_profile_hpaths    += ./../../GeomUtils/headers
SimulationController_profile_hpaths    += ./../../GeomUtils/src
SimulationController_profile_hpaths    += ./../../GeomUtils/src/contact
SimulationController_profile_hpaths    += ./../../GeomUtils/src/common
SimulationController_profile_hpaths    += ./../../GeomUtils/src/convex
SimulationController_profile_hpaths    += ./../../GeomUtils/src/distance
SimulationController_profile_hpaths    += ./../../GeomUtils/src/sweep
SimulationController_profile_hpaths    += ./../../GeomUtils/src/gjk
SimulationController_profile_hpaths    += ./../../GeomUtils/src/intersection
SimulationController_profile_hpaths    += ./../../GeomUtils/src/mesh
SimulationController_profile_hpaths    += ./../../GeomUtils/src/hf
SimulationController_profile_hpaths    += ./../../GeomUtils/src/pcm
SimulationController_profile_hpaths    += ./../../GeomUtils/src/ccd
SimulationController_profile_hpaths    += ./../../SimulationController/include
SimulationController_profile_hpaths    += ./../../SimulationController/src
SimulationController_profile_hpaths    += ./../../SimulationController/src/particles
SimulationController_profile_hpaths    += ./../../SimulationController/src/cloth
SimulationController_profile_hpaths    += ./../../LowLevel/unix/include
SimulationController_profile_hpaths    += ./../../LowLevel/API/include
SimulationController_profile_hpaths    += ./../../LowLevel/software/include
SimulationController_profile_hpaths    += ./../../LowLevel/common/include/math
SimulationController_profile_hpaths    += ./../../LowLevel/common/include/utils
SimulationController_profile_hpaths    += ./../../LowLevel/common/include/collision
SimulationController_profile_hpaths    += ./../../LowLevel/common/include/pipeline
SimulationController_profile_hpaths    += ./../../LowLevelCloth/include
SimulationController_profile_hpaths    += ./../../LowLevelAABB/include
SimulationController_profile_hpaths    += ./../../LowLevelDynamics/include
SimulationController_profile_hpaths    += ./../../LowLevelParticles/include
SimulationController_profile_lpaths    := 
SimulationController_profile_defines   := $(SimulationController_custom_defines)
SimulationController_profile_defines   += PX_PHYSX_STATIC_LIB
SimulationController_profile_defines   += NDEBUG
SimulationController_profile_defines   += PX_PROFILE=1
SimulationController_profile_defines   += PX_SUPPORT_PVD=1
SimulationController_profile_libraries := 
SimulationController_profile_common_cflags	:= $(SimulationController_custom_cflags)
SimulationController_profile_common_cflags    += -MMD
SimulationController_profile_common_cflags    += $(addprefix -D, $(SimulationController_profile_defines))
SimulationController_profile_common_cflags    += $(addprefix -I, $(SimulationController_profile_hpaths))
SimulationController_profile_cflags	:= $(SimulationController_profile_common_cflags)
SimulationController_profile_cflags  += -arch x86_64
SimulationController_profile_cflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_profile_cflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_profile_cflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_profile_cflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_profile_cflags  += -Wno-c++11-extensions
SimulationController_profile_cflags  += -O3 -fno-strict-aliasing
SimulationController_profile_cppflags	:= $(SimulationController_profile_common_cflags)
SimulationController_profile_cppflags  += -arch x86_64
SimulationController_profile_cppflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_profile_cppflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_profile_cppflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_profile_cppflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_profile_cppflags  += -Wno-c++11-extensions
SimulationController_profile_cppflags  += -O3 -fno-strict-aliasing
SimulationController_profile_lflags    := $(SimulationController_custom_lflags)
SimulationController_profile_lflags    += $(addprefix -L, $(SimulationController_profile_lpaths))
SimulationController_profile_lflags  += $(addprefix -l, $(SimulationController_profile_libraries))
SimulationController_profile_lflags  += -arch x86_64
SimulationController_profile_lflags  += -stdlib=libc++
SimulationController_profile_objsdir  = $(OBJS_DIR)/SimulationController_profile
SimulationController_profile_cpp_o    = $(addprefix $(SimulationController_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SimulationController_cppfiles)))))
SimulationController_profile_cc_o    = $(addprefix $(SimulationController_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SimulationController_ccfiles)))))
SimulationController_profile_c_o      = $(addprefix $(SimulationController_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SimulationController_cfiles)))))
SimulationController_profile_obj      = $(SimulationController_profile_cpp_o) $(SimulationController_profile_cc_o) $(SimulationController_profile_c_o)
SimulationController_profile_bin      := ./../../../Lib/osx64/libSimulationControllerPROFILE.a

clean_SimulationController_profile: 
	@$(ECHO) clean SimulationController profile
	@$(RMDIR) $(SimulationController_profile_objsdir)
	@$(RMDIR) $(SimulationController_profile_bin)
	@$(RMDIR) $(DEPSDIR)/SimulationController/profile

build_SimulationController_profile: postbuild_SimulationController_profile
postbuild_SimulationController_profile: mainbuild_SimulationController_profile
mainbuild_SimulationController_profile: prebuild_SimulationController_profile $(SimulationController_profile_bin)
prebuild_SimulationController_profile:

$(SimulationController_profile_bin): $(SimulationController_profile_obj) 
	mkdir -p `dirname ./../../../Lib/osx64/libSimulationControllerPROFILE.a`
	@$(AR) rcs $(SimulationController_profile_bin) $(SimulationController_profile_obj)
	$(ECHO) building $@ complete!

SimulationController_profile_DEPDIR = $(dir $(@))/$(*F)
$(SimulationController_profile_cpp_o): $(SimulationController_profile_objsdir)/%.o:
	$(ECHO) SimulationController: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cppfiles))))))
	cp $(SimulationController_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  rm -f $(SimulationController_profile_DEPDIR).d

$(SimulationController_profile_cc_o): $(SimulationController_profile_objsdir)/%.o:
	$(ECHO) SimulationController: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_ccfiles))))))
	cp $(SimulationController_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_ccfiles))))).profile.P; \
	  rm -f $(SimulationController_profile_DEPDIR).d

$(SimulationController_profile_c_o): $(SimulationController_profile_objsdir)/%.o:
	$(ECHO) SimulationController: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SimulationController_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cfiles))))))
	cp $(SimulationController_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_profile_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  rm -f $(SimulationController_profile_DEPDIR).d

SimulationController_release_hpaths    := 
SimulationController_release_hpaths    += ./../../Common/include
SimulationController_release_hpaths    += ./../../../../PxShared/include
SimulationController_release_hpaths    += ./../../../../PxShared/src/foundation/include
SimulationController_release_hpaths    += ./../../../../PxShared/src/fastxml/include
SimulationController_release_hpaths    += ./../../../../PxShared/src/pvd/include
SimulationController_release_hpaths    += ./../../../Include/common
SimulationController_release_hpaths    += ./../../../Include/geometry
SimulationController_release_hpaths    += ./../../../Include/GeomUtils
SimulationController_release_hpaths    += ./../../../Include/pvd
SimulationController_release_hpaths    += ./../../../Include/particles
SimulationController_release_hpaths    += ./../../../Include/cloth
SimulationController_release_hpaths    += ./../../../Include
SimulationController_release_hpaths    += ./../../Common/src
SimulationController_release_hpaths    += ./../../Common/src/unix
SimulationController_release_hpaths    += ./../../GeomUtils/headers
SimulationController_release_hpaths    += ./../../GeomUtils/src
SimulationController_release_hpaths    += ./../../GeomUtils/src/contact
SimulationController_release_hpaths    += ./../../GeomUtils/src/common
SimulationController_release_hpaths    += ./../../GeomUtils/src/convex
SimulationController_release_hpaths    += ./../../GeomUtils/src/distance
SimulationController_release_hpaths    += ./../../GeomUtils/src/sweep
SimulationController_release_hpaths    += ./../../GeomUtils/src/gjk
SimulationController_release_hpaths    += ./../../GeomUtils/src/intersection
SimulationController_release_hpaths    += ./../../GeomUtils/src/mesh
SimulationController_release_hpaths    += ./../../GeomUtils/src/hf
SimulationController_release_hpaths    += ./../../GeomUtils/src/pcm
SimulationController_release_hpaths    += ./../../GeomUtils/src/ccd
SimulationController_release_hpaths    += ./../../SimulationController/include
SimulationController_release_hpaths    += ./../../SimulationController/src
SimulationController_release_hpaths    += ./../../SimulationController/src/particles
SimulationController_release_hpaths    += ./../../SimulationController/src/cloth
SimulationController_release_hpaths    += ./../../LowLevel/unix/include
SimulationController_release_hpaths    += ./../../LowLevel/API/include
SimulationController_release_hpaths    += ./../../LowLevel/software/include
SimulationController_release_hpaths    += ./../../LowLevel/common/include/math
SimulationController_release_hpaths    += ./../../LowLevel/common/include/utils
SimulationController_release_hpaths    += ./../../LowLevel/common/include/collision
SimulationController_release_hpaths    += ./../../LowLevel/common/include/pipeline
SimulationController_release_hpaths    += ./../../LowLevelCloth/include
SimulationController_release_hpaths    += ./../../LowLevelAABB/include
SimulationController_release_hpaths    += ./../../LowLevelDynamics/include
SimulationController_release_hpaths    += ./../../LowLevelParticles/include
SimulationController_release_lpaths    := 
SimulationController_release_defines   := $(SimulationController_custom_defines)
SimulationController_release_defines   += PX_PHYSX_STATIC_LIB
SimulationController_release_defines   += NDEBUG
SimulationController_release_defines   += PX_SUPPORT_PVD=0
SimulationController_release_libraries := 
SimulationController_release_common_cflags	:= $(SimulationController_custom_cflags)
SimulationController_release_common_cflags    += -MMD
SimulationController_release_common_cflags    += $(addprefix -D, $(SimulationController_release_defines))
SimulationController_release_common_cflags    += $(addprefix -I, $(SimulationController_release_hpaths))
SimulationController_release_cflags	:= $(SimulationController_release_common_cflags)
SimulationController_release_cflags  += -arch x86_64
SimulationController_release_cflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_release_cflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_release_cflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_release_cflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_release_cflags  += -Wno-c++11-extensions
SimulationController_release_cflags  += -O3 -fno-strict-aliasing
SimulationController_release_cppflags	:= $(SimulationController_release_common_cflags)
SimulationController_release_cppflags  += -arch x86_64
SimulationController_release_cppflags  += -pipe -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.9 -msse2 -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Werror
SimulationController_release_cppflags  += -Wall -Wextra -fstrict-aliasing -Wstrict-aliasing=2 -pedantic -Weverything -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command -Wno-float-equal -Wno-padded -Wno-weak-vtables -Wno-zero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-deprecated -Wno-c++98-compat-pedantic
SimulationController_release_cppflags  += -Wno-cast-align -Wno-conversion -Wno-missing-variable-declarations -Wno-shift-sign-overflow
SimulationController_release_cppflags  += -Wno-exit-time-destructors -Wno-global-constructors -Wno-missing-prototypes -Wno-unreachable-code -Wno-unused-macros -Wno-used-but-marked-unused -Wno-weak-template-vtables -Wno-invalid-offsetof
SimulationController_release_cppflags  += -Wno-c++11-extensions
SimulationController_release_cppflags  += -O3 -fno-strict-aliasing
SimulationController_release_lflags    := $(SimulationController_custom_lflags)
SimulationController_release_lflags    += $(addprefix -L, $(SimulationController_release_lpaths))
SimulationController_release_lflags  += $(addprefix -l, $(SimulationController_release_libraries))
SimulationController_release_lflags  += -arch x86_64
SimulationController_release_lflags  += -stdlib=libc++
SimulationController_release_objsdir  = $(OBJS_DIR)/SimulationController_release
SimulationController_release_cpp_o    = $(addprefix $(SimulationController_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SimulationController_cppfiles)))))
SimulationController_release_cc_o    = $(addprefix $(SimulationController_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SimulationController_ccfiles)))))
SimulationController_release_c_o      = $(addprefix $(SimulationController_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SimulationController_cfiles)))))
SimulationController_release_obj      = $(SimulationController_release_cpp_o) $(SimulationController_release_cc_o) $(SimulationController_release_c_o)
SimulationController_release_bin      := ./../../../Lib/osx64/libSimulationController.a

clean_SimulationController_release: 
	@$(ECHO) clean SimulationController release
	@$(RMDIR) $(SimulationController_release_objsdir)
	@$(RMDIR) $(SimulationController_release_bin)
	@$(RMDIR) $(DEPSDIR)/SimulationController/release

build_SimulationController_release: postbuild_SimulationController_release
postbuild_SimulationController_release: mainbuild_SimulationController_release
mainbuild_SimulationController_release: prebuild_SimulationController_release $(SimulationController_release_bin)
prebuild_SimulationController_release:

$(SimulationController_release_bin): $(SimulationController_release_obj) 
	mkdir -p `dirname ./../../../Lib/osx64/libSimulationController.a`
	@$(AR) rcs $(SimulationController_release_bin) $(SimulationController_release_obj)
	$(ECHO) building $@ complete!

SimulationController_release_DEPDIR = $(dir $(@))/$(*F)
$(SimulationController_release_cpp_o): $(SimulationController_release_objsdir)/%.o:
	$(ECHO) SimulationController: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cppfiles))))))
	cp $(SimulationController_release_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cppfiles))))).P; \
	  rm -f $(SimulationController_release_DEPDIR).d

$(SimulationController_release_cc_o): $(SimulationController_release_objsdir)/%.o:
	$(ECHO) SimulationController: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SimulationController_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_ccfiles))))))
	cp $(SimulationController_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_ccfiles))))).release.P; \
	  rm -f $(SimulationController_release_DEPDIR).d

$(SimulationController_release_c_o): $(SimulationController_release_objsdir)/%.o:
	$(ECHO) SimulationController: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SimulationController_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cfiles))))))
	cp $(SimulationController_release_DEPDIR).d $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SimulationController_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SimulationController/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SimulationController_release_objsdir),, $@))), $(SimulationController_cfiles))))).P; \
	  rm -f $(SimulationController_release_DEPDIR).d

clean_SimulationController:  clean_SimulationController_debug clean_SimulationController_checked clean_SimulationController_profile clean_SimulationController_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
