# Makefile generated by XPJ for ANDROID16
-include Makefile.custom
ProjectName = SnippetTriangleMeshCreate
SnippetTriangleMeshCreate_cppfiles   += ./../../SnippetCommon/ClassicMain.cpp
SnippetTriangleMeshCreate_cppfiles   += ./../../SnippetTriangleMeshCreate/SnippetTriangleMeshCreate.cpp

SnippetTriangleMeshCreate_cpp_debug_dep    = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_c_debug_dep      = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_debug_dep      = $(SnippetTriangleMeshCreate_cpp_debug_dep) $(SnippetTriangleMeshCreate_cc_debug_dep) $(SnippetTriangleMeshCreate_c_debug_dep)
-include $(SnippetTriangleMeshCreate_debug_dep)
SnippetTriangleMeshCreate_cpp_checked_dep    = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_c_checked_dep      = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_checked_dep      = $(SnippetTriangleMeshCreate_cpp_checked_dep) $(SnippetTriangleMeshCreate_cc_checked_dep) $(SnippetTriangleMeshCreate_c_checked_dep)
-include $(SnippetTriangleMeshCreate_checked_dep)
SnippetTriangleMeshCreate_cpp_profile_dep    = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_c_profile_dep      = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_profile_dep      = $(SnippetTriangleMeshCreate_cpp_profile_dep) $(SnippetTriangleMeshCreate_cc_profile_dep) $(SnippetTriangleMeshCreate_c_profile_dep)
-include $(SnippetTriangleMeshCreate_profile_dep)
SnippetTriangleMeshCreate_cpp_release_dep    = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_c_release_dep      = $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_release_dep      = $(SnippetTriangleMeshCreate_cpp_release_dep) $(SnippetTriangleMeshCreate_cc_release_dep) $(SnippetTriangleMeshCreate_c_release_dep)
-include $(SnippetTriangleMeshCreate_release_dep)
SnippetTriangleMeshCreate_debug_hpaths    := 
SnippetTriangleMeshCreate_debug_hpaths    += ./../../../Include
SnippetTriangleMeshCreate_debug_hpaths    += ./../../../../PxShared/include
SnippetTriangleMeshCreate_debug_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetTriangleMeshCreate_debug_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetTriangleMeshCreate_debug_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetTriangleMeshCreate_debug_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetTriangleMeshCreate_debug_lpaths    := 
SnippetTriangleMeshCreate_debug_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetTriangleMeshCreate_debug_lpaths    += ./../../../Lib/android16
SnippetTriangleMeshCreate_debug_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_debug_lpaths    += ./../../../../PxShared/lib/android16
SnippetTriangleMeshCreate_debug_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_debug_defines   := $(SnippetTriangleMeshCreate_custom_defines)
SnippetTriangleMeshCreate_debug_defines   += ANDROID
SnippetTriangleMeshCreate_debug_defines   += GLES2
SnippetTriangleMeshCreate_debug_defines   += __STDC_LIMIT_MACROS
SnippetTriangleMeshCreate_debug_defines   += __ARM_ARCH_5__
SnippetTriangleMeshCreate_debug_defines   += __ARM_ARCH_5T__
SnippetTriangleMeshCreate_debug_defines   += __ARM_ARCH_5E__
SnippetTriangleMeshCreate_debug_defines   += __ARM_ARCH_5TE__
SnippetTriangleMeshCreate_debug_defines   += _DEBUG
SnippetTriangleMeshCreate_debug_defines   += PX_DEBUG=1
SnippetTriangleMeshCreate_debug_defines   += PX_CHECKED=1
SnippetTriangleMeshCreate_debug_defines   += PX_SUPPORT_PVD=1
SnippetTriangleMeshCreate_debug_defines   += PX_NVTX=1
SnippetTriangleMeshCreate_debug_defines   += PHYSX_PROFILE_SDK
SnippetTriangleMeshCreate_debug_libraries := 
SnippetTriangleMeshCreate_debug_libraries += SnippetUtilsDEBUG
SnippetTriangleMeshCreate_debug_libraries += log
SnippetTriangleMeshCreate_debug_libraries += gnustl_static
SnippetTriangleMeshCreate_debug_libraries += supc++
SnippetTriangleMeshCreate_debug_libraries += m
SnippetTriangleMeshCreate_debug_libraries += c
SnippetTriangleMeshCreate_debug_libraries += nvToolsExt
SnippetTriangleMeshCreate_debug_libraries += PhysX3CommonDEBUG
SnippetTriangleMeshCreate_debug_libraries += PhysX3DEBUG
SnippetTriangleMeshCreate_debug_libraries += PhysX3VehicleDEBUG
SnippetTriangleMeshCreate_debug_libraries += PhysX3CookingDEBUG
SnippetTriangleMeshCreate_debug_libraries += PhysX3ExtensionsDEBUG
SnippetTriangleMeshCreate_debug_libraries += PhysX3CharacterKinematicDEBUG
SnippetTriangleMeshCreate_debug_libraries += SnippetUtilsDEBUG
SnippetTriangleMeshCreate_debug_libraries += PxFoundationDEBUG
SnippetTriangleMeshCreate_debug_libraries += PsFastXmlDEBUG
SnippetTriangleMeshCreate_debug_libraries += PxPvdSDKDEBUG
SnippetTriangleMeshCreate_debug_common_cflags	:= $(SnippetTriangleMeshCreate_custom_cflags)
SnippetTriangleMeshCreate_debug_common_cflags    += -MMD
SnippetTriangleMeshCreate_debug_common_cflags    += $(addprefix -D, $(SnippetTriangleMeshCreate_debug_defines))
SnippetTriangleMeshCreate_debug_common_cflags    += $(addprefix -I, $(SnippetTriangleMeshCreate_debug_hpaths))
SnippetTriangleMeshCreate_debug_common_cflags  += -Werror
SnippetTriangleMeshCreate_debug_common_cflags  += -fpic -fno-exceptions
SnippetTriangleMeshCreate_debug_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_debug_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetTriangleMeshCreate_debug_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetTriangleMeshCreate_debug_common_cflags  += -Wno-maybe-uninitialized
SnippetTriangleMeshCreate_debug_common_cflags  += -Wno-pedantic
SnippetTriangleMeshCreate_debug_common_cflags  += -fPIE
SnippetTriangleMeshCreate_debug_common_cflags  += -g3 -gdwarf-2
SnippetTriangleMeshCreate_debug_cflags	:= $(SnippetTriangleMeshCreate_debug_common_cflags)
SnippetTriangleMeshCreate_debug_cppflags	:= $(SnippetTriangleMeshCreate_debug_common_cflags)
SnippetTriangleMeshCreate_debug_cppflags  += -fno-rtti
SnippetTriangleMeshCreate_debug_lflags    := $(SnippetTriangleMeshCreate_custom_lflags)
SnippetTriangleMeshCreate_debug_lflags    += $(addprefix -L, $(SnippetTriangleMeshCreate_debug_lpaths))
SnippetTriangleMeshCreate_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetTriangleMeshCreate_debug_libraries)) -Wl,--end-group
SnippetTriangleMeshCreate_debug_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_debug_lflags  += -Wl,--no-undefined
SnippetTriangleMeshCreate_debug_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetTriangleMeshCreate_debug_lflags  += -pie
SnippetTriangleMeshCreate_debug_objsdir  = $(OBJS_DIR)/SnippetTriangleMeshCreate_debug
SnippetTriangleMeshCreate_debug_cpp_o    = $(addprefix $(SnippetTriangleMeshCreate_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_debug_cc_o    = $(addprefix $(SnippetTriangleMeshCreate_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_debug_c_o      = $(addprefix $(SnippetTriangleMeshCreate_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_debug_obj      = $(SnippetTriangleMeshCreate_debug_cpp_o) $(SnippetTriangleMeshCreate_debug_cc_o) $(SnippetTriangleMeshCreate_debug_c_o)
SnippetTriangleMeshCreate_debug_bin      := ./../../../Bin/android16/SnippetTriangleMeshCreateDEBUG

clean_SnippetTriangleMeshCreate_debug: 
	@$(ECHO) clean SnippetTriangleMeshCreate debug
	@$(RMDIR) $(SnippetTriangleMeshCreate_debug_objsdir)
	@$(RMDIR) $(SnippetTriangleMeshCreate_debug_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetTriangleMeshCreate/debug

build_SnippetTriangleMeshCreate_debug: postbuild_SnippetTriangleMeshCreate_debug
postbuild_SnippetTriangleMeshCreate_debug: mainbuild_SnippetTriangleMeshCreate_debug
mainbuild_SnippetTriangleMeshCreate_debug: prebuild_SnippetTriangleMeshCreate_debug $(SnippetTriangleMeshCreate_debug_bin)
prebuild_SnippetTriangleMeshCreate_debug:

$(SnippetTriangleMeshCreate_debug_bin): $(SnippetTriangleMeshCreate_debug_obj) build_SnippetUtils_debug 
	mkdir -p `dirname ./../../../Bin/android16/SnippetTriangleMeshCreateDEBUG`
	$(CCLD) $(SnippetTriangleMeshCreate_debug_obj) $(SnippetTriangleMeshCreate_debug_lflags) -o $(SnippetTriangleMeshCreate_debug_bin) 
	$(ECHO) building $@ complete!

SnippetTriangleMeshCreate_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetTriangleMeshCreate_debug_cpp_o): $(SnippetTriangleMeshCreate_debug_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))))
	cp $(SnippetTriangleMeshCreate_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_debug_DEPDIR).d

$(SnippetTriangleMeshCreate_debug_cc_o): $(SnippetTriangleMeshCreate_debug_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))))
	cp $(SnippetTriangleMeshCreate_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).debug.P; \
	  rm -f $(SnippetTriangleMeshCreate_debug_DEPDIR).d

$(SnippetTriangleMeshCreate_debug_c_o): $(SnippetTriangleMeshCreate_debug_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetTriangleMeshCreate_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))))
	cp $(SnippetTriangleMeshCreate_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_debug_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_debug_DEPDIR).d

SnippetTriangleMeshCreate_checked_hpaths    := 
SnippetTriangleMeshCreate_checked_hpaths    += ./../../../Include
SnippetTriangleMeshCreate_checked_hpaths    += ./../../../../PxShared/include
SnippetTriangleMeshCreate_checked_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetTriangleMeshCreate_checked_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetTriangleMeshCreate_checked_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetTriangleMeshCreate_checked_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetTriangleMeshCreate_checked_lpaths    := 
SnippetTriangleMeshCreate_checked_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetTriangleMeshCreate_checked_lpaths    += ./../../../Lib/android16
SnippetTriangleMeshCreate_checked_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_checked_lpaths    += ./../../../../PxShared/lib/android16
SnippetTriangleMeshCreate_checked_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_checked_defines   := $(SnippetTriangleMeshCreate_custom_defines)
SnippetTriangleMeshCreate_checked_defines   += ANDROID
SnippetTriangleMeshCreate_checked_defines   += GLES2
SnippetTriangleMeshCreate_checked_defines   += __STDC_LIMIT_MACROS
SnippetTriangleMeshCreate_checked_defines   += __ARM_ARCH_5__
SnippetTriangleMeshCreate_checked_defines   += __ARM_ARCH_5T__
SnippetTriangleMeshCreate_checked_defines   += __ARM_ARCH_5E__
SnippetTriangleMeshCreate_checked_defines   += __ARM_ARCH_5TE__
SnippetTriangleMeshCreate_checked_defines   += NDEBUG
SnippetTriangleMeshCreate_checked_defines   += PX_CHECKED=1
SnippetTriangleMeshCreate_checked_defines   += PX_SUPPORT_PVD=1
SnippetTriangleMeshCreate_checked_defines   += PX_NVTX=1
SnippetTriangleMeshCreate_checked_defines   += PHYSX_PROFILE_SDK
SnippetTriangleMeshCreate_checked_libraries := 
SnippetTriangleMeshCreate_checked_libraries += SnippetUtilsCHECKED
SnippetTriangleMeshCreate_checked_libraries += log
SnippetTriangleMeshCreate_checked_libraries += gnustl_static
SnippetTriangleMeshCreate_checked_libraries += supc++
SnippetTriangleMeshCreate_checked_libraries += m
SnippetTriangleMeshCreate_checked_libraries += c
SnippetTriangleMeshCreate_checked_libraries += nvToolsExt
SnippetTriangleMeshCreate_checked_libraries += PhysX3CommonCHECKED
SnippetTriangleMeshCreate_checked_libraries += PhysX3CHECKED
SnippetTriangleMeshCreate_checked_libraries += PhysX3VehicleCHECKED
SnippetTriangleMeshCreate_checked_libraries += PhysX3CookingCHECKED
SnippetTriangleMeshCreate_checked_libraries += PhysX3ExtensionsCHECKED
SnippetTriangleMeshCreate_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetTriangleMeshCreate_checked_libraries += SnippetUtilsCHECKED
SnippetTriangleMeshCreate_checked_libraries += PxFoundationCHECKED
SnippetTriangleMeshCreate_checked_libraries += PsFastXmlCHECKED
SnippetTriangleMeshCreate_checked_libraries += PxPvdSDKCHECKED
SnippetTriangleMeshCreate_checked_common_cflags	:= $(SnippetTriangleMeshCreate_custom_cflags)
SnippetTriangleMeshCreate_checked_common_cflags    += -MMD
SnippetTriangleMeshCreate_checked_common_cflags    += $(addprefix -D, $(SnippetTriangleMeshCreate_checked_defines))
SnippetTriangleMeshCreate_checked_common_cflags    += $(addprefix -I, $(SnippetTriangleMeshCreate_checked_hpaths))
SnippetTriangleMeshCreate_checked_common_cflags  += -Werror
SnippetTriangleMeshCreate_checked_common_cflags  += -fpic -fno-exceptions
SnippetTriangleMeshCreate_checked_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_checked_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetTriangleMeshCreate_checked_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetTriangleMeshCreate_checked_common_cflags  += -Wno-maybe-uninitialized
SnippetTriangleMeshCreate_checked_common_cflags  += -Wno-pedantic
SnippetTriangleMeshCreate_checked_common_cflags  += -fPIE
SnippetTriangleMeshCreate_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetTriangleMeshCreate_checked_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetTriangleMeshCreate_checked_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetTriangleMeshCreate_checked_cflags	:= $(SnippetTriangleMeshCreate_checked_common_cflags)
SnippetTriangleMeshCreate_checked_cppflags	:= $(SnippetTriangleMeshCreate_checked_common_cflags)
SnippetTriangleMeshCreate_checked_cppflags  += -fno-rtti
SnippetTriangleMeshCreate_checked_lflags    := $(SnippetTriangleMeshCreate_custom_lflags)
SnippetTriangleMeshCreate_checked_lflags    += $(addprefix -L, $(SnippetTriangleMeshCreate_checked_lpaths))
SnippetTriangleMeshCreate_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetTriangleMeshCreate_checked_libraries)) -Wl,--end-group
SnippetTriangleMeshCreate_checked_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_checked_lflags  += -Wl,--no-undefined
SnippetTriangleMeshCreate_checked_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetTriangleMeshCreate_checked_lflags  += -pie
SnippetTriangleMeshCreate_checked_objsdir  = $(OBJS_DIR)/SnippetTriangleMeshCreate_checked
SnippetTriangleMeshCreate_checked_cpp_o    = $(addprefix $(SnippetTriangleMeshCreate_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_checked_cc_o    = $(addprefix $(SnippetTriangleMeshCreate_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_checked_c_o      = $(addprefix $(SnippetTriangleMeshCreate_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_checked_obj      = $(SnippetTriangleMeshCreate_checked_cpp_o) $(SnippetTriangleMeshCreate_checked_cc_o) $(SnippetTriangleMeshCreate_checked_c_o)
SnippetTriangleMeshCreate_checked_bin      := ./../../../Bin/android16/SnippetTriangleMeshCreateCHECKED

clean_SnippetTriangleMeshCreate_checked: 
	@$(ECHO) clean SnippetTriangleMeshCreate checked
	@$(RMDIR) $(SnippetTriangleMeshCreate_checked_objsdir)
	@$(RMDIR) $(SnippetTriangleMeshCreate_checked_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetTriangleMeshCreate/checked

build_SnippetTriangleMeshCreate_checked: postbuild_SnippetTriangleMeshCreate_checked
postbuild_SnippetTriangleMeshCreate_checked: mainbuild_SnippetTriangleMeshCreate_checked
mainbuild_SnippetTriangleMeshCreate_checked: prebuild_SnippetTriangleMeshCreate_checked $(SnippetTriangleMeshCreate_checked_bin)
prebuild_SnippetTriangleMeshCreate_checked:

$(SnippetTriangleMeshCreate_checked_bin): $(SnippetTriangleMeshCreate_checked_obj) build_SnippetUtils_checked 
	mkdir -p `dirname ./../../../Bin/android16/SnippetTriangleMeshCreateCHECKED`
	$(CCLD) $(SnippetTriangleMeshCreate_checked_obj) $(SnippetTriangleMeshCreate_checked_lflags) -o $(SnippetTriangleMeshCreate_checked_bin) 
	$(ECHO) building $@ complete!

SnippetTriangleMeshCreate_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetTriangleMeshCreate_checked_cpp_o): $(SnippetTriangleMeshCreate_checked_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))))
	cp $(SnippetTriangleMeshCreate_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_checked_DEPDIR).d

$(SnippetTriangleMeshCreate_checked_cc_o): $(SnippetTriangleMeshCreate_checked_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))))
	cp $(SnippetTriangleMeshCreate_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).checked.P; \
	  rm -f $(SnippetTriangleMeshCreate_checked_DEPDIR).d

$(SnippetTriangleMeshCreate_checked_c_o): $(SnippetTriangleMeshCreate_checked_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetTriangleMeshCreate_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))))
	cp $(SnippetTriangleMeshCreate_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_checked_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_checked_DEPDIR).d

SnippetTriangleMeshCreate_profile_hpaths    := 
SnippetTriangleMeshCreate_profile_hpaths    += ./../../../Include
SnippetTriangleMeshCreate_profile_hpaths    += ./../../../../PxShared/include
SnippetTriangleMeshCreate_profile_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetTriangleMeshCreate_profile_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetTriangleMeshCreate_profile_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetTriangleMeshCreate_profile_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetTriangleMeshCreate_profile_lpaths    := 
SnippetTriangleMeshCreate_profile_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetTriangleMeshCreate_profile_lpaths    += ./../../../Lib/android16
SnippetTriangleMeshCreate_profile_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_profile_lpaths    += ./../../../../PxShared/lib/android16
SnippetTriangleMeshCreate_profile_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_profile_defines   := $(SnippetTriangleMeshCreate_custom_defines)
SnippetTriangleMeshCreate_profile_defines   += ANDROID
SnippetTriangleMeshCreate_profile_defines   += GLES2
SnippetTriangleMeshCreate_profile_defines   += __STDC_LIMIT_MACROS
SnippetTriangleMeshCreate_profile_defines   += __ARM_ARCH_5__
SnippetTriangleMeshCreate_profile_defines   += __ARM_ARCH_5T__
SnippetTriangleMeshCreate_profile_defines   += __ARM_ARCH_5E__
SnippetTriangleMeshCreate_profile_defines   += __ARM_ARCH_5TE__
SnippetTriangleMeshCreate_profile_defines   += NDEBUG
SnippetTriangleMeshCreate_profile_defines   += PX_PROFILE=1
SnippetTriangleMeshCreate_profile_defines   += PX_SUPPORT_PVD=1
SnippetTriangleMeshCreate_profile_defines   += PX_NVTX=1
SnippetTriangleMeshCreate_profile_defines   += PHYSX_PROFILE_SDK
SnippetTriangleMeshCreate_profile_libraries := 
SnippetTriangleMeshCreate_profile_libraries += SnippetUtilsPROFILE
SnippetTriangleMeshCreate_profile_libraries += log
SnippetTriangleMeshCreate_profile_libraries += gnustl_static
SnippetTriangleMeshCreate_profile_libraries += supc++
SnippetTriangleMeshCreate_profile_libraries += m
SnippetTriangleMeshCreate_profile_libraries += c
SnippetTriangleMeshCreate_profile_libraries += nvToolsExt
SnippetTriangleMeshCreate_profile_libraries += PhysX3CommonPROFILE
SnippetTriangleMeshCreate_profile_libraries += PhysX3PROFILE
SnippetTriangleMeshCreate_profile_libraries += PhysX3VehiclePROFILE
SnippetTriangleMeshCreate_profile_libraries += PhysX3CookingPROFILE
SnippetTriangleMeshCreate_profile_libraries += PhysX3ExtensionsPROFILE
SnippetTriangleMeshCreate_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetTriangleMeshCreate_profile_libraries += SnippetUtilsPROFILE
SnippetTriangleMeshCreate_profile_libraries += PxFoundationPROFILE
SnippetTriangleMeshCreate_profile_libraries += PsFastXmlPROFILE
SnippetTriangleMeshCreate_profile_libraries += PxPvdSDKPROFILE
SnippetTriangleMeshCreate_profile_common_cflags	:= $(SnippetTriangleMeshCreate_custom_cflags)
SnippetTriangleMeshCreate_profile_common_cflags    += -MMD
SnippetTriangleMeshCreate_profile_common_cflags    += $(addprefix -D, $(SnippetTriangleMeshCreate_profile_defines))
SnippetTriangleMeshCreate_profile_common_cflags    += $(addprefix -I, $(SnippetTriangleMeshCreate_profile_hpaths))
SnippetTriangleMeshCreate_profile_common_cflags  += -Werror
SnippetTriangleMeshCreate_profile_common_cflags  += -fpic -fno-exceptions
SnippetTriangleMeshCreate_profile_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_profile_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetTriangleMeshCreate_profile_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetTriangleMeshCreate_profile_common_cflags  += -Wno-maybe-uninitialized
SnippetTriangleMeshCreate_profile_common_cflags  += -Wno-pedantic
SnippetTriangleMeshCreate_profile_common_cflags  += -fPIE
SnippetTriangleMeshCreate_profile_common_cflags  += -O3 -fno-strict-aliasing
SnippetTriangleMeshCreate_profile_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetTriangleMeshCreate_profile_common_cflags  += -fno-omit-frame-pointer -funswitch-loops -finline-limit=300
SnippetTriangleMeshCreate_profile_cflags	:= $(SnippetTriangleMeshCreate_profile_common_cflags)
SnippetTriangleMeshCreate_profile_cppflags	:= $(SnippetTriangleMeshCreate_profile_common_cflags)
SnippetTriangleMeshCreate_profile_cppflags  += -fno-rtti
SnippetTriangleMeshCreate_profile_lflags    := $(SnippetTriangleMeshCreate_custom_lflags)
SnippetTriangleMeshCreate_profile_lflags    += $(addprefix -L, $(SnippetTriangleMeshCreate_profile_lpaths))
SnippetTriangleMeshCreate_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetTriangleMeshCreate_profile_libraries)) -Wl,--end-group
SnippetTriangleMeshCreate_profile_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_profile_lflags  += -Wl,--no-undefined
SnippetTriangleMeshCreate_profile_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetTriangleMeshCreate_profile_lflags  += -pie
SnippetTriangleMeshCreate_profile_objsdir  = $(OBJS_DIR)/SnippetTriangleMeshCreate_profile
SnippetTriangleMeshCreate_profile_cpp_o    = $(addprefix $(SnippetTriangleMeshCreate_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_profile_cc_o    = $(addprefix $(SnippetTriangleMeshCreate_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_profile_c_o      = $(addprefix $(SnippetTriangleMeshCreate_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_profile_obj      = $(SnippetTriangleMeshCreate_profile_cpp_o) $(SnippetTriangleMeshCreate_profile_cc_o) $(SnippetTriangleMeshCreate_profile_c_o)
SnippetTriangleMeshCreate_profile_bin      := ./../../../Bin/android16/SnippetTriangleMeshCreatePROFILE

clean_SnippetTriangleMeshCreate_profile: 
	@$(ECHO) clean SnippetTriangleMeshCreate profile
	@$(RMDIR) $(SnippetTriangleMeshCreate_profile_objsdir)
	@$(RMDIR) $(SnippetTriangleMeshCreate_profile_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetTriangleMeshCreate/profile

build_SnippetTriangleMeshCreate_profile: postbuild_SnippetTriangleMeshCreate_profile
postbuild_SnippetTriangleMeshCreate_profile: mainbuild_SnippetTriangleMeshCreate_profile
mainbuild_SnippetTriangleMeshCreate_profile: prebuild_SnippetTriangleMeshCreate_profile $(SnippetTriangleMeshCreate_profile_bin)
prebuild_SnippetTriangleMeshCreate_profile:

$(SnippetTriangleMeshCreate_profile_bin): $(SnippetTriangleMeshCreate_profile_obj) build_SnippetUtils_profile 
	mkdir -p `dirname ./../../../Bin/android16/SnippetTriangleMeshCreatePROFILE`
	$(CCLD) $(SnippetTriangleMeshCreate_profile_obj) $(SnippetTriangleMeshCreate_profile_lflags) -o $(SnippetTriangleMeshCreate_profile_bin) 
	$(ECHO) building $@ complete!

SnippetTriangleMeshCreate_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetTriangleMeshCreate_profile_cpp_o): $(SnippetTriangleMeshCreate_profile_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))))
	cp $(SnippetTriangleMeshCreate_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_profile_DEPDIR).d

$(SnippetTriangleMeshCreate_profile_cc_o): $(SnippetTriangleMeshCreate_profile_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))))
	cp $(SnippetTriangleMeshCreate_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).profile.P; \
	  rm -f $(SnippetTriangleMeshCreate_profile_DEPDIR).d

$(SnippetTriangleMeshCreate_profile_c_o): $(SnippetTriangleMeshCreate_profile_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetTriangleMeshCreate_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))))
	cp $(SnippetTriangleMeshCreate_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_profile_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_profile_DEPDIR).d

SnippetTriangleMeshCreate_release_hpaths    := 
SnippetTriangleMeshCreate_release_hpaths    += ./../../../Include
SnippetTriangleMeshCreate_release_hpaths    += ./../../../../PxShared/include
SnippetTriangleMeshCreate_release_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetTriangleMeshCreate_release_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetTriangleMeshCreate_release_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetTriangleMeshCreate_release_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetTriangleMeshCreate_release_lpaths    := 
SnippetTriangleMeshCreate_release_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetTriangleMeshCreate_release_lpaths    += ./../../../Lib/android16
SnippetTriangleMeshCreate_release_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_release_lpaths    += ./../../../../PxShared/lib/android16
SnippetTriangleMeshCreate_release_lpaths    += ./../../lib/android16
SnippetTriangleMeshCreate_release_defines   := $(SnippetTriangleMeshCreate_custom_defines)
SnippetTriangleMeshCreate_release_defines   += ANDROID
SnippetTriangleMeshCreate_release_defines   += GLES2
SnippetTriangleMeshCreate_release_defines   += __STDC_LIMIT_MACROS
SnippetTriangleMeshCreate_release_defines   += __ARM_ARCH_5__
SnippetTriangleMeshCreate_release_defines   += __ARM_ARCH_5T__
SnippetTriangleMeshCreate_release_defines   += __ARM_ARCH_5E__
SnippetTriangleMeshCreate_release_defines   += __ARM_ARCH_5TE__
SnippetTriangleMeshCreate_release_defines   += NDEBUG
SnippetTriangleMeshCreate_release_defines   += PX_SUPPORT_PVD=0
SnippetTriangleMeshCreate_release_defines   += PHYSX_PROFILE_SDK
SnippetTriangleMeshCreate_release_libraries := 
SnippetTriangleMeshCreate_release_libraries += SnippetUtils
SnippetTriangleMeshCreate_release_libraries += log
SnippetTriangleMeshCreate_release_libraries += gnustl_static
SnippetTriangleMeshCreate_release_libraries += supc++
SnippetTriangleMeshCreate_release_libraries += m
SnippetTriangleMeshCreate_release_libraries += c
SnippetTriangleMeshCreate_release_libraries += nvToolsExt
SnippetTriangleMeshCreate_release_libraries += PhysX3Common
SnippetTriangleMeshCreate_release_libraries += PhysX3
SnippetTriangleMeshCreate_release_libraries += PhysX3Vehicle
SnippetTriangleMeshCreate_release_libraries += PhysX3Cooking
SnippetTriangleMeshCreate_release_libraries += PhysX3Extensions
SnippetTriangleMeshCreate_release_libraries += PhysX3CharacterKinematic
SnippetTriangleMeshCreate_release_libraries += SnippetUtils
SnippetTriangleMeshCreate_release_libraries += PxFoundation
SnippetTriangleMeshCreate_release_libraries += PsFastXml
SnippetTriangleMeshCreate_release_libraries += PxPvdSDK
SnippetTriangleMeshCreate_release_common_cflags	:= $(SnippetTriangleMeshCreate_custom_cflags)
SnippetTriangleMeshCreate_release_common_cflags    += -MMD
SnippetTriangleMeshCreate_release_common_cflags    += $(addprefix -D, $(SnippetTriangleMeshCreate_release_defines))
SnippetTriangleMeshCreate_release_common_cflags    += $(addprefix -I, $(SnippetTriangleMeshCreate_release_hpaths))
SnippetTriangleMeshCreate_release_common_cflags  += -Werror
SnippetTriangleMeshCreate_release_common_cflags  += -fpic -fno-exceptions
SnippetTriangleMeshCreate_release_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_release_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetTriangleMeshCreate_release_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetTriangleMeshCreate_release_common_cflags  += -Wno-maybe-uninitialized
SnippetTriangleMeshCreate_release_common_cflags  += -Wno-pedantic
SnippetTriangleMeshCreate_release_common_cflags  += -fPIE
SnippetTriangleMeshCreate_release_common_cflags  += -O3 -fno-strict-aliasing
SnippetTriangleMeshCreate_release_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetTriangleMeshCreate_release_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetTriangleMeshCreate_release_cflags	:= $(SnippetTriangleMeshCreate_release_common_cflags)
SnippetTriangleMeshCreate_release_cppflags	:= $(SnippetTriangleMeshCreate_release_common_cflags)
SnippetTriangleMeshCreate_release_cppflags  += -fno-rtti
SnippetTriangleMeshCreate_release_lflags    := $(SnippetTriangleMeshCreate_custom_lflags)
SnippetTriangleMeshCreate_release_lflags    += $(addprefix -L, $(SnippetTriangleMeshCreate_release_lpaths))
SnippetTriangleMeshCreate_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetTriangleMeshCreate_release_libraries)) -Wl,--end-group
SnippetTriangleMeshCreate_release_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetTriangleMeshCreate_release_lflags  += -Wl,--no-undefined
SnippetTriangleMeshCreate_release_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetTriangleMeshCreate_release_lflags  += -pie
SnippetTriangleMeshCreate_release_objsdir  = $(OBJS_DIR)/SnippetTriangleMeshCreate_release
SnippetTriangleMeshCreate_release_cpp_o    = $(addprefix $(SnippetTriangleMeshCreate_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetTriangleMeshCreate_cppfiles)))))
SnippetTriangleMeshCreate_release_cc_o    = $(addprefix $(SnippetTriangleMeshCreate_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetTriangleMeshCreate_ccfiles)))))
SnippetTriangleMeshCreate_release_c_o      = $(addprefix $(SnippetTriangleMeshCreate_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetTriangleMeshCreate_cfiles)))))
SnippetTriangleMeshCreate_release_obj      = $(SnippetTriangleMeshCreate_release_cpp_o) $(SnippetTriangleMeshCreate_release_cc_o) $(SnippetTriangleMeshCreate_release_c_o)
SnippetTriangleMeshCreate_release_bin      := ./../../../Bin/android16/SnippetTriangleMeshCreate

clean_SnippetTriangleMeshCreate_release: 
	@$(ECHO) clean SnippetTriangleMeshCreate release
	@$(RMDIR) $(SnippetTriangleMeshCreate_release_objsdir)
	@$(RMDIR) $(SnippetTriangleMeshCreate_release_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetTriangleMeshCreate/release

build_SnippetTriangleMeshCreate_release: postbuild_SnippetTriangleMeshCreate_release
postbuild_SnippetTriangleMeshCreate_release: mainbuild_SnippetTriangleMeshCreate_release
mainbuild_SnippetTriangleMeshCreate_release: prebuild_SnippetTriangleMeshCreate_release $(SnippetTriangleMeshCreate_release_bin)
prebuild_SnippetTriangleMeshCreate_release:

$(SnippetTriangleMeshCreate_release_bin): $(SnippetTriangleMeshCreate_release_obj) build_SnippetUtils_release 
	mkdir -p `dirname ./../../../Bin/android16/SnippetTriangleMeshCreate`
	$(CCLD) $(SnippetTriangleMeshCreate_release_obj) $(SnippetTriangleMeshCreate_release_lflags) -o $(SnippetTriangleMeshCreate_release_bin) 
	$(ECHO) building $@ complete!

SnippetTriangleMeshCreate_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetTriangleMeshCreate_release_cpp_o): $(SnippetTriangleMeshCreate_release_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))))
	cp $(SnippetTriangleMeshCreate_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cppfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_release_DEPDIR).d

$(SnippetTriangleMeshCreate_release_cc_o): $(SnippetTriangleMeshCreate_release_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetTriangleMeshCreate_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))))
	cp $(SnippetTriangleMeshCreate_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_ccfiles))))).release.P; \
	  rm -f $(SnippetTriangleMeshCreate_release_DEPDIR).d

$(SnippetTriangleMeshCreate_release_c_o): $(SnippetTriangleMeshCreate_release_objsdir)/%.o:
	$(ECHO) SnippetTriangleMeshCreate: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetTriangleMeshCreate_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))))
	cp $(SnippetTriangleMeshCreate_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetTriangleMeshCreate_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetTriangleMeshCreate/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetTriangleMeshCreate_release_objsdir),, $@))), $(SnippetTriangleMeshCreate_cfiles))))).P; \
	  rm -f $(SnippetTriangleMeshCreate_release_DEPDIR).d

clean_SnippetTriangleMeshCreate:  clean_SnippetTriangleMeshCreate_debug clean_SnippetTriangleMeshCreate_checked clean_SnippetTriangleMeshCreate_profile clean_SnippetTriangleMeshCreate_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
