# Makefile generated by XPJ for ANDROID16
-include Makefile.custom
ProjectName = SnippetDeformableMesh
SnippetDeformableMesh_cppfiles   += ./../../SnippetCommon/ClassicMain.cpp
SnippetDeformableMesh_cppfiles   += ./../../SnippetDeformableMesh/SnippetDeformableMesh.cpp
SnippetDeformableMesh_cppfiles   += ./../../SnippetDeformableMesh/SnippetDeformableMeshRender.cpp

SnippetDeformableMesh_cpp_debug_dep    = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_c_debug_dep      = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_debug_dep      = $(SnippetDeformableMesh_cpp_debug_dep) $(SnippetDeformableMesh_cc_debug_dep) $(SnippetDeformableMesh_c_debug_dep)
-include $(SnippetDeformableMesh_debug_dep)
SnippetDeformableMesh_cpp_checked_dep    = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_c_checked_dep      = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_checked_dep      = $(SnippetDeformableMesh_cpp_checked_dep) $(SnippetDeformableMesh_cc_checked_dep) $(SnippetDeformableMesh_c_checked_dep)
-include $(SnippetDeformableMesh_checked_dep)
SnippetDeformableMesh_cpp_profile_dep    = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_c_profile_dep      = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_profile_dep      = $(SnippetDeformableMesh_cpp_profile_dep) $(SnippetDeformableMesh_cc_profile_dep) $(SnippetDeformableMesh_c_profile_dep)
-include $(SnippetDeformableMesh_profile_dep)
SnippetDeformableMesh_cpp_release_dep    = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_c_release_dep      = $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_release_dep      = $(SnippetDeformableMesh_cpp_release_dep) $(SnippetDeformableMesh_cc_release_dep) $(SnippetDeformableMesh_c_release_dep)
-include $(SnippetDeformableMesh_release_dep)
SnippetDeformableMesh_debug_hpaths    := 
SnippetDeformableMesh_debug_hpaths    += ./../../../Include
SnippetDeformableMesh_debug_hpaths    += ./../../../../PxShared/include
SnippetDeformableMesh_debug_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetDeformableMesh_debug_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetDeformableMesh_debug_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetDeformableMesh_debug_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetDeformableMesh_debug_lpaths    := 
SnippetDeformableMesh_debug_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetDeformableMesh_debug_lpaths    += ./../../../Lib/android16
SnippetDeformableMesh_debug_lpaths    += ./../../lib/android16
SnippetDeformableMesh_debug_lpaths    += ./../../../../PxShared/lib/android16
SnippetDeformableMesh_debug_lpaths    += ./../../lib/android16
SnippetDeformableMesh_debug_defines   := $(SnippetDeformableMesh_custom_defines)
SnippetDeformableMesh_debug_defines   += ANDROID
SnippetDeformableMesh_debug_defines   += GLES2
SnippetDeformableMesh_debug_defines   += __STDC_LIMIT_MACROS
SnippetDeformableMesh_debug_defines   += __ARM_ARCH_5__
SnippetDeformableMesh_debug_defines   += __ARM_ARCH_5T__
SnippetDeformableMesh_debug_defines   += __ARM_ARCH_5E__
SnippetDeformableMesh_debug_defines   += __ARM_ARCH_5TE__
SnippetDeformableMesh_debug_defines   += _DEBUG
SnippetDeformableMesh_debug_defines   += PX_DEBUG=1
SnippetDeformableMesh_debug_defines   += PX_CHECKED=1
SnippetDeformableMesh_debug_defines   += PX_SUPPORT_PVD=1
SnippetDeformableMesh_debug_defines   += PX_NVTX=1
SnippetDeformableMesh_debug_defines   += PHYSX_PROFILE_SDK
SnippetDeformableMesh_debug_libraries := 
SnippetDeformableMesh_debug_libraries += SnippetUtilsDEBUG
SnippetDeformableMesh_debug_libraries += log
SnippetDeformableMesh_debug_libraries += gnustl_static
SnippetDeformableMesh_debug_libraries += supc++
SnippetDeformableMesh_debug_libraries += m
SnippetDeformableMesh_debug_libraries += c
SnippetDeformableMesh_debug_libraries += nvToolsExt
SnippetDeformableMesh_debug_libraries += PhysX3CommonDEBUG
SnippetDeformableMesh_debug_libraries += PhysX3DEBUG
SnippetDeformableMesh_debug_libraries += PhysX3VehicleDEBUG
SnippetDeformableMesh_debug_libraries += PhysX3CookingDEBUG
SnippetDeformableMesh_debug_libraries += PhysX3ExtensionsDEBUG
SnippetDeformableMesh_debug_libraries += PhysX3CharacterKinematicDEBUG
SnippetDeformableMesh_debug_libraries += SnippetUtilsDEBUG
SnippetDeformableMesh_debug_libraries += PxFoundationDEBUG
SnippetDeformableMesh_debug_libraries += PsFastXmlDEBUG
SnippetDeformableMesh_debug_libraries += PxPvdSDKDEBUG
SnippetDeformableMesh_debug_common_cflags	:= $(SnippetDeformableMesh_custom_cflags)
SnippetDeformableMesh_debug_common_cflags    += -MMD
SnippetDeformableMesh_debug_common_cflags    += $(addprefix -D, $(SnippetDeformableMesh_debug_defines))
SnippetDeformableMesh_debug_common_cflags    += $(addprefix -I, $(SnippetDeformableMesh_debug_hpaths))
SnippetDeformableMesh_debug_common_cflags  += -Werror
SnippetDeformableMesh_debug_common_cflags  += -fpic -fno-exceptions
SnippetDeformableMesh_debug_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_debug_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetDeformableMesh_debug_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetDeformableMesh_debug_common_cflags  += -Wno-maybe-uninitialized
SnippetDeformableMesh_debug_common_cflags  += -Wno-pedantic
SnippetDeformableMesh_debug_common_cflags  += -fPIE
SnippetDeformableMesh_debug_common_cflags  += -g3 -gdwarf-2
SnippetDeformableMesh_debug_cflags	:= $(SnippetDeformableMesh_debug_common_cflags)
SnippetDeformableMesh_debug_cppflags	:= $(SnippetDeformableMesh_debug_common_cflags)
SnippetDeformableMesh_debug_cppflags  += -fno-rtti
SnippetDeformableMesh_debug_lflags    := $(SnippetDeformableMesh_custom_lflags)
SnippetDeformableMesh_debug_lflags    += $(addprefix -L, $(SnippetDeformableMesh_debug_lpaths))
SnippetDeformableMesh_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetDeformableMesh_debug_libraries)) -Wl,--end-group
SnippetDeformableMesh_debug_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_debug_lflags  += -Wl,--no-undefined
SnippetDeformableMesh_debug_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetDeformableMesh_debug_lflags  += -pie
SnippetDeformableMesh_debug_objsdir  = $(OBJS_DIR)/SnippetDeformableMesh_debug
SnippetDeformableMesh_debug_cpp_o    = $(addprefix $(SnippetDeformableMesh_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_debug_cc_o    = $(addprefix $(SnippetDeformableMesh_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_debug_c_o      = $(addprefix $(SnippetDeformableMesh_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_debug_obj      = $(SnippetDeformableMesh_debug_cpp_o) $(SnippetDeformableMesh_debug_cc_o) $(SnippetDeformableMesh_debug_c_o)
SnippetDeformableMesh_debug_bin      := ./../../../Bin/android16/SnippetDeformableMeshDEBUG

clean_SnippetDeformableMesh_debug: 
	@$(ECHO) clean SnippetDeformableMesh debug
	@$(RMDIR) $(SnippetDeformableMesh_debug_objsdir)
	@$(RMDIR) $(SnippetDeformableMesh_debug_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetDeformableMesh/debug

build_SnippetDeformableMesh_debug: postbuild_SnippetDeformableMesh_debug
postbuild_SnippetDeformableMesh_debug: mainbuild_SnippetDeformableMesh_debug
mainbuild_SnippetDeformableMesh_debug: prebuild_SnippetDeformableMesh_debug $(SnippetDeformableMesh_debug_bin)
prebuild_SnippetDeformableMesh_debug:

$(SnippetDeformableMesh_debug_bin): $(SnippetDeformableMesh_debug_obj) build_SnippetUtils_debug 
	mkdir -p `dirname ./../../../Bin/android16/SnippetDeformableMeshDEBUG`
	$(CCLD) $(SnippetDeformableMesh_debug_obj) $(SnippetDeformableMesh_debug_lflags) -o $(SnippetDeformableMesh_debug_bin) 
	$(ECHO) building $@ complete!

SnippetDeformableMesh_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetDeformableMesh_debug_cpp_o): $(SnippetDeformableMesh_debug_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))))
	cp $(SnippetDeformableMesh_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_debug_DEPDIR).d

$(SnippetDeformableMesh_debug_cc_o): $(SnippetDeformableMesh_debug_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))))
	cp $(SnippetDeformableMesh_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).debug.P; \
	  rm -f $(SnippetDeformableMesh_debug_DEPDIR).d

$(SnippetDeformableMesh_debug_c_o): $(SnippetDeformableMesh_debug_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetDeformableMesh_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))))
	cp $(SnippetDeformableMesh_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_debug_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_debug_DEPDIR).d

SnippetDeformableMesh_checked_hpaths    := 
SnippetDeformableMesh_checked_hpaths    += ./../../../Include
SnippetDeformableMesh_checked_hpaths    += ./../../../../PxShared/include
SnippetDeformableMesh_checked_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetDeformableMesh_checked_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetDeformableMesh_checked_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetDeformableMesh_checked_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetDeformableMesh_checked_lpaths    := 
SnippetDeformableMesh_checked_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetDeformableMesh_checked_lpaths    += ./../../../Lib/android16
SnippetDeformableMesh_checked_lpaths    += ./../../lib/android16
SnippetDeformableMesh_checked_lpaths    += ./../../../../PxShared/lib/android16
SnippetDeformableMesh_checked_lpaths    += ./../../lib/android16
SnippetDeformableMesh_checked_defines   := $(SnippetDeformableMesh_custom_defines)
SnippetDeformableMesh_checked_defines   += ANDROID
SnippetDeformableMesh_checked_defines   += GLES2
SnippetDeformableMesh_checked_defines   += __STDC_LIMIT_MACROS
SnippetDeformableMesh_checked_defines   += __ARM_ARCH_5__
SnippetDeformableMesh_checked_defines   += __ARM_ARCH_5T__
SnippetDeformableMesh_checked_defines   += __ARM_ARCH_5E__
SnippetDeformableMesh_checked_defines   += __ARM_ARCH_5TE__
SnippetDeformableMesh_checked_defines   += NDEBUG
SnippetDeformableMesh_checked_defines   += PX_CHECKED=1
SnippetDeformableMesh_checked_defines   += PX_SUPPORT_PVD=1
SnippetDeformableMesh_checked_defines   += PX_NVTX=1
SnippetDeformableMesh_checked_defines   += PHYSX_PROFILE_SDK
SnippetDeformableMesh_checked_libraries := 
SnippetDeformableMesh_checked_libraries += SnippetUtilsCHECKED
SnippetDeformableMesh_checked_libraries += log
SnippetDeformableMesh_checked_libraries += gnustl_static
SnippetDeformableMesh_checked_libraries += supc++
SnippetDeformableMesh_checked_libraries += m
SnippetDeformableMesh_checked_libraries += c
SnippetDeformableMesh_checked_libraries += nvToolsExt
SnippetDeformableMesh_checked_libraries += PhysX3CommonCHECKED
SnippetDeformableMesh_checked_libraries += PhysX3CHECKED
SnippetDeformableMesh_checked_libraries += PhysX3VehicleCHECKED
SnippetDeformableMesh_checked_libraries += PhysX3CookingCHECKED
SnippetDeformableMesh_checked_libraries += PhysX3ExtensionsCHECKED
SnippetDeformableMesh_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetDeformableMesh_checked_libraries += SnippetUtilsCHECKED
SnippetDeformableMesh_checked_libraries += PxFoundationCHECKED
SnippetDeformableMesh_checked_libraries += PsFastXmlCHECKED
SnippetDeformableMesh_checked_libraries += PxPvdSDKCHECKED
SnippetDeformableMesh_checked_common_cflags	:= $(SnippetDeformableMesh_custom_cflags)
SnippetDeformableMesh_checked_common_cflags    += -MMD
SnippetDeformableMesh_checked_common_cflags    += $(addprefix -D, $(SnippetDeformableMesh_checked_defines))
SnippetDeformableMesh_checked_common_cflags    += $(addprefix -I, $(SnippetDeformableMesh_checked_hpaths))
SnippetDeformableMesh_checked_common_cflags  += -Werror
SnippetDeformableMesh_checked_common_cflags  += -fpic -fno-exceptions
SnippetDeformableMesh_checked_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_checked_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetDeformableMesh_checked_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetDeformableMesh_checked_common_cflags  += -Wno-maybe-uninitialized
SnippetDeformableMesh_checked_common_cflags  += -Wno-pedantic
SnippetDeformableMesh_checked_common_cflags  += -fPIE
SnippetDeformableMesh_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetDeformableMesh_checked_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetDeformableMesh_checked_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetDeformableMesh_checked_cflags	:= $(SnippetDeformableMesh_checked_common_cflags)
SnippetDeformableMesh_checked_cppflags	:= $(SnippetDeformableMesh_checked_common_cflags)
SnippetDeformableMesh_checked_cppflags  += -fno-rtti
SnippetDeformableMesh_checked_lflags    := $(SnippetDeformableMesh_custom_lflags)
SnippetDeformableMesh_checked_lflags    += $(addprefix -L, $(SnippetDeformableMesh_checked_lpaths))
SnippetDeformableMesh_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetDeformableMesh_checked_libraries)) -Wl,--end-group
SnippetDeformableMesh_checked_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_checked_lflags  += -Wl,--no-undefined
SnippetDeformableMesh_checked_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetDeformableMesh_checked_lflags  += -pie
SnippetDeformableMesh_checked_objsdir  = $(OBJS_DIR)/SnippetDeformableMesh_checked
SnippetDeformableMesh_checked_cpp_o    = $(addprefix $(SnippetDeformableMesh_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_checked_cc_o    = $(addprefix $(SnippetDeformableMesh_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_checked_c_o      = $(addprefix $(SnippetDeformableMesh_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_checked_obj      = $(SnippetDeformableMesh_checked_cpp_o) $(SnippetDeformableMesh_checked_cc_o) $(SnippetDeformableMesh_checked_c_o)
SnippetDeformableMesh_checked_bin      := ./../../../Bin/android16/SnippetDeformableMeshCHECKED

clean_SnippetDeformableMesh_checked: 
	@$(ECHO) clean SnippetDeformableMesh checked
	@$(RMDIR) $(SnippetDeformableMesh_checked_objsdir)
	@$(RMDIR) $(SnippetDeformableMesh_checked_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetDeformableMesh/checked

build_SnippetDeformableMesh_checked: postbuild_SnippetDeformableMesh_checked
postbuild_SnippetDeformableMesh_checked: mainbuild_SnippetDeformableMesh_checked
mainbuild_SnippetDeformableMesh_checked: prebuild_SnippetDeformableMesh_checked $(SnippetDeformableMesh_checked_bin)
prebuild_SnippetDeformableMesh_checked:

$(SnippetDeformableMesh_checked_bin): $(SnippetDeformableMesh_checked_obj) build_SnippetUtils_checked 
	mkdir -p `dirname ./../../../Bin/android16/SnippetDeformableMeshCHECKED`
	$(CCLD) $(SnippetDeformableMesh_checked_obj) $(SnippetDeformableMesh_checked_lflags) -o $(SnippetDeformableMesh_checked_bin) 
	$(ECHO) building $@ complete!

SnippetDeformableMesh_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetDeformableMesh_checked_cpp_o): $(SnippetDeformableMesh_checked_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))))
	cp $(SnippetDeformableMesh_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_checked_DEPDIR).d

$(SnippetDeformableMesh_checked_cc_o): $(SnippetDeformableMesh_checked_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))))
	cp $(SnippetDeformableMesh_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).checked.P; \
	  rm -f $(SnippetDeformableMesh_checked_DEPDIR).d

$(SnippetDeformableMesh_checked_c_o): $(SnippetDeformableMesh_checked_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetDeformableMesh_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))))
	cp $(SnippetDeformableMesh_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_checked_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_checked_DEPDIR).d

SnippetDeformableMesh_profile_hpaths    := 
SnippetDeformableMesh_profile_hpaths    += ./../../../Include
SnippetDeformableMesh_profile_hpaths    += ./../../../../PxShared/include
SnippetDeformableMesh_profile_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetDeformableMesh_profile_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetDeformableMesh_profile_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetDeformableMesh_profile_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetDeformableMesh_profile_lpaths    := 
SnippetDeformableMesh_profile_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetDeformableMesh_profile_lpaths    += ./../../../Lib/android16
SnippetDeformableMesh_profile_lpaths    += ./../../lib/android16
SnippetDeformableMesh_profile_lpaths    += ./../../../../PxShared/lib/android16
SnippetDeformableMesh_profile_lpaths    += ./../../lib/android16
SnippetDeformableMesh_profile_defines   := $(SnippetDeformableMesh_custom_defines)
SnippetDeformableMesh_profile_defines   += ANDROID
SnippetDeformableMesh_profile_defines   += GLES2
SnippetDeformableMesh_profile_defines   += __STDC_LIMIT_MACROS
SnippetDeformableMesh_profile_defines   += __ARM_ARCH_5__
SnippetDeformableMesh_profile_defines   += __ARM_ARCH_5T__
SnippetDeformableMesh_profile_defines   += __ARM_ARCH_5E__
SnippetDeformableMesh_profile_defines   += __ARM_ARCH_5TE__
SnippetDeformableMesh_profile_defines   += NDEBUG
SnippetDeformableMesh_profile_defines   += PX_PROFILE=1
SnippetDeformableMesh_profile_defines   += PX_SUPPORT_PVD=1
SnippetDeformableMesh_profile_defines   += PX_NVTX=1
SnippetDeformableMesh_profile_defines   += PHYSX_PROFILE_SDK
SnippetDeformableMesh_profile_libraries := 
SnippetDeformableMesh_profile_libraries += SnippetUtilsPROFILE
SnippetDeformableMesh_profile_libraries += log
SnippetDeformableMesh_profile_libraries += gnustl_static
SnippetDeformableMesh_profile_libraries += supc++
SnippetDeformableMesh_profile_libraries += m
SnippetDeformableMesh_profile_libraries += c
SnippetDeformableMesh_profile_libraries += nvToolsExt
SnippetDeformableMesh_profile_libraries += PhysX3CommonPROFILE
SnippetDeformableMesh_profile_libraries += PhysX3PROFILE
SnippetDeformableMesh_profile_libraries += PhysX3VehiclePROFILE
SnippetDeformableMesh_profile_libraries += PhysX3CookingPROFILE
SnippetDeformableMesh_profile_libraries += PhysX3ExtensionsPROFILE
SnippetDeformableMesh_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetDeformableMesh_profile_libraries += SnippetUtilsPROFILE
SnippetDeformableMesh_profile_libraries += PxFoundationPROFILE
SnippetDeformableMesh_profile_libraries += PsFastXmlPROFILE
SnippetDeformableMesh_profile_libraries += PxPvdSDKPROFILE
SnippetDeformableMesh_profile_common_cflags	:= $(SnippetDeformableMesh_custom_cflags)
SnippetDeformableMesh_profile_common_cflags    += -MMD
SnippetDeformableMesh_profile_common_cflags    += $(addprefix -D, $(SnippetDeformableMesh_profile_defines))
SnippetDeformableMesh_profile_common_cflags    += $(addprefix -I, $(SnippetDeformableMesh_profile_hpaths))
SnippetDeformableMesh_profile_common_cflags  += -Werror
SnippetDeformableMesh_profile_common_cflags  += -fpic -fno-exceptions
SnippetDeformableMesh_profile_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_profile_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetDeformableMesh_profile_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetDeformableMesh_profile_common_cflags  += -Wno-maybe-uninitialized
SnippetDeformableMesh_profile_common_cflags  += -Wno-pedantic
SnippetDeformableMesh_profile_common_cflags  += -fPIE
SnippetDeformableMesh_profile_common_cflags  += -O3 -fno-strict-aliasing
SnippetDeformableMesh_profile_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetDeformableMesh_profile_common_cflags  += -fno-omit-frame-pointer -funswitch-loops -finline-limit=300
SnippetDeformableMesh_profile_cflags	:= $(SnippetDeformableMesh_profile_common_cflags)
SnippetDeformableMesh_profile_cppflags	:= $(SnippetDeformableMesh_profile_common_cflags)
SnippetDeformableMesh_profile_cppflags  += -fno-rtti
SnippetDeformableMesh_profile_lflags    := $(SnippetDeformableMesh_custom_lflags)
SnippetDeformableMesh_profile_lflags    += $(addprefix -L, $(SnippetDeformableMesh_profile_lpaths))
SnippetDeformableMesh_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetDeformableMesh_profile_libraries)) -Wl,--end-group
SnippetDeformableMesh_profile_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_profile_lflags  += -Wl,--no-undefined
SnippetDeformableMesh_profile_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetDeformableMesh_profile_lflags  += -pie
SnippetDeformableMesh_profile_objsdir  = $(OBJS_DIR)/SnippetDeformableMesh_profile
SnippetDeformableMesh_profile_cpp_o    = $(addprefix $(SnippetDeformableMesh_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_profile_cc_o    = $(addprefix $(SnippetDeformableMesh_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_profile_c_o      = $(addprefix $(SnippetDeformableMesh_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_profile_obj      = $(SnippetDeformableMesh_profile_cpp_o) $(SnippetDeformableMesh_profile_cc_o) $(SnippetDeformableMesh_profile_c_o)
SnippetDeformableMesh_profile_bin      := ./../../../Bin/android16/SnippetDeformableMeshPROFILE

clean_SnippetDeformableMesh_profile: 
	@$(ECHO) clean SnippetDeformableMesh profile
	@$(RMDIR) $(SnippetDeformableMesh_profile_objsdir)
	@$(RMDIR) $(SnippetDeformableMesh_profile_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetDeformableMesh/profile

build_SnippetDeformableMesh_profile: postbuild_SnippetDeformableMesh_profile
postbuild_SnippetDeformableMesh_profile: mainbuild_SnippetDeformableMesh_profile
mainbuild_SnippetDeformableMesh_profile: prebuild_SnippetDeformableMesh_profile $(SnippetDeformableMesh_profile_bin)
prebuild_SnippetDeformableMesh_profile:

$(SnippetDeformableMesh_profile_bin): $(SnippetDeformableMesh_profile_obj) build_SnippetUtils_profile 
	mkdir -p `dirname ./../../../Bin/android16/SnippetDeformableMeshPROFILE`
	$(CCLD) $(SnippetDeformableMesh_profile_obj) $(SnippetDeformableMesh_profile_lflags) -o $(SnippetDeformableMesh_profile_bin) 
	$(ECHO) building $@ complete!

SnippetDeformableMesh_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetDeformableMesh_profile_cpp_o): $(SnippetDeformableMesh_profile_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))))
	cp $(SnippetDeformableMesh_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_profile_DEPDIR).d

$(SnippetDeformableMesh_profile_cc_o): $(SnippetDeformableMesh_profile_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))))
	cp $(SnippetDeformableMesh_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).profile.P; \
	  rm -f $(SnippetDeformableMesh_profile_DEPDIR).d

$(SnippetDeformableMesh_profile_c_o): $(SnippetDeformableMesh_profile_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetDeformableMesh_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))))
	cp $(SnippetDeformableMesh_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_profile_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_profile_DEPDIR).d

SnippetDeformableMesh_release_hpaths    := 
SnippetDeformableMesh_release_hpaths    += ./../../../Include
SnippetDeformableMesh_release_hpaths    += ./../../../../PxShared/include
SnippetDeformableMesh_release_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetDeformableMesh_release_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetDeformableMesh_release_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetDeformableMesh_release_hpaths    += ./../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetDeformableMesh_release_lpaths    := 
SnippetDeformableMesh_release_lpaths    += ./../../../../Externals/nvToolsExt/1/lib/armv7
SnippetDeformableMesh_release_lpaths    += ./../../../Lib/android16
SnippetDeformableMesh_release_lpaths    += ./../../lib/android16
SnippetDeformableMesh_release_lpaths    += ./../../../../PxShared/lib/android16
SnippetDeformableMesh_release_lpaths    += ./../../lib/android16
SnippetDeformableMesh_release_defines   := $(SnippetDeformableMesh_custom_defines)
SnippetDeformableMesh_release_defines   += ANDROID
SnippetDeformableMesh_release_defines   += GLES2
SnippetDeformableMesh_release_defines   += __STDC_LIMIT_MACROS
SnippetDeformableMesh_release_defines   += __ARM_ARCH_5__
SnippetDeformableMesh_release_defines   += __ARM_ARCH_5T__
SnippetDeformableMesh_release_defines   += __ARM_ARCH_5E__
SnippetDeformableMesh_release_defines   += __ARM_ARCH_5TE__
SnippetDeformableMesh_release_defines   += NDEBUG
SnippetDeformableMesh_release_defines   += PX_SUPPORT_PVD=0
SnippetDeformableMesh_release_defines   += PHYSX_PROFILE_SDK
SnippetDeformableMesh_release_libraries := 
SnippetDeformableMesh_release_libraries += SnippetUtils
SnippetDeformableMesh_release_libraries += log
SnippetDeformableMesh_release_libraries += gnustl_static
SnippetDeformableMesh_release_libraries += supc++
SnippetDeformableMesh_release_libraries += m
SnippetDeformableMesh_release_libraries += c
SnippetDeformableMesh_release_libraries += nvToolsExt
SnippetDeformableMesh_release_libraries += PhysX3Common
SnippetDeformableMesh_release_libraries += PhysX3
SnippetDeformableMesh_release_libraries += PhysX3Vehicle
SnippetDeformableMesh_release_libraries += PhysX3Cooking
SnippetDeformableMesh_release_libraries += PhysX3Extensions
SnippetDeformableMesh_release_libraries += PhysX3CharacterKinematic
SnippetDeformableMesh_release_libraries += SnippetUtils
SnippetDeformableMesh_release_libraries += PxFoundation
SnippetDeformableMesh_release_libraries += PsFastXml
SnippetDeformableMesh_release_libraries += PxPvdSDK
SnippetDeformableMesh_release_common_cflags	:= $(SnippetDeformableMesh_custom_cflags)
SnippetDeformableMesh_release_common_cflags    += -MMD
SnippetDeformableMesh_release_common_cflags    += $(addprefix -D, $(SnippetDeformableMesh_release_defines))
SnippetDeformableMesh_release_common_cflags    += $(addprefix -I, $(SnippetDeformableMesh_release_hpaths))
SnippetDeformableMesh_release_common_cflags  += -Werror
SnippetDeformableMesh_release_common_cflags  += -fpic -fno-exceptions
SnippetDeformableMesh_release_common_cflags  += -isysroot ../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_release_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetDeformableMesh_release_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetDeformableMesh_release_common_cflags  += -Wno-maybe-uninitialized
SnippetDeformableMesh_release_common_cflags  += -Wno-pedantic
SnippetDeformableMesh_release_common_cflags  += -fPIE
SnippetDeformableMesh_release_common_cflags  += -O3 -fno-strict-aliasing
SnippetDeformableMesh_release_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetDeformableMesh_release_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetDeformableMesh_release_cflags	:= $(SnippetDeformableMesh_release_common_cflags)
SnippetDeformableMesh_release_cppflags	:= $(SnippetDeformableMesh_release_common_cflags)
SnippetDeformableMesh_release_cppflags  += -fno-rtti
SnippetDeformableMesh_release_lflags    := $(SnippetDeformableMesh_custom_lflags)
SnippetDeformableMesh_release_lflags    += $(addprefix -L, $(SnippetDeformableMesh_release_lpaths))
SnippetDeformableMesh_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetDeformableMesh_release_libraries)) -Wl,--end-group
SnippetDeformableMesh_release_lflags  += --sysroot=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetDeformableMesh_release_lflags  += -Wl,--no-undefined
SnippetDeformableMesh_release_lflags  += -Wl,-z,noexecstack -L../../../../Externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../../Externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetDeformableMesh_release_lflags  += -pie
SnippetDeformableMesh_release_objsdir  = $(OBJS_DIR)/SnippetDeformableMesh_release
SnippetDeformableMesh_release_cpp_o    = $(addprefix $(SnippetDeformableMesh_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetDeformableMesh_cppfiles)))))
SnippetDeformableMesh_release_cc_o    = $(addprefix $(SnippetDeformableMesh_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetDeformableMesh_ccfiles)))))
SnippetDeformableMesh_release_c_o      = $(addprefix $(SnippetDeformableMesh_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetDeformableMesh_cfiles)))))
SnippetDeformableMesh_release_obj      = $(SnippetDeformableMesh_release_cpp_o) $(SnippetDeformableMesh_release_cc_o) $(SnippetDeformableMesh_release_c_o)
SnippetDeformableMesh_release_bin      := ./../../../Bin/android16/SnippetDeformableMesh

clean_SnippetDeformableMesh_release: 
	@$(ECHO) clean SnippetDeformableMesh release
	@$(RMDIR) $(SnippetDeformableMesh_release_objsdir)
	@$(RMDIR) $(SnippetDeformableMesh_release_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetDeformableMesh/release

build_SnippetDeformableMesh_release: postbuild_SnippetDeformableMesh_release
postbuild_SnippetDeformableMesh_release: mainbuild_SnippetDeformableMesh_release
mainbuild_SnippetDeformableMesh_release: prebuild_SnippetDeformableMesh_release $(SnippetDeformableMesh_release_bin)
prebuild_SnippetDeformableMesh_release:

$(SnippetDeformableMesh_release_bin): $(SnippetDeformableMesh_release_obj) build_SnippetUtils_release 
	mkdir -p `dirname ./../../../Bin/android16/SnippetDeformableMesh`
	$(CCLD) $(SnippetDeformableMesh_release_obj) $(SnippetDeformableMesh_release_lflags) -o $(SnippetDeformableMesh_release_bin) 
	$(ECHO) building $@ complete!

SnippetDeformableMesh_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetDeformableMesh_release_cpp_o): $(SnippetDeformableMesh_release_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))))
	cp $(SnippetDeformableMesh_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cppfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_release_DEPDIR).d

$(SnippetDeformableMesh_release_cc_o): $(SnippetDeformableMesh_release_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetDeformableMesh_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))))
	cp $(SnippetDeformableMesh_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_ccfiles))))).release.P; \
	  rm -f $(SnippetDeformableMesh_release_DEPDIR).d

$(SnippetDeformableMesh_release_c_o): $(SnippetDeformableMesh_release_objsdir)/%.o:
	$(ECHO) SnippetDeformableMesh: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetDeformableMesh_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))))
	cp $(SnippetDeformableMesh_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetDeformableMesh_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetDeformableMesh/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetDeformableMesh_release_objsdir),, $@))), $(SnippetDeformableMesh_cfiles))))).P; \
	  rm -f $(SnippetDeformableMesh_release_DEPDIR).d

clean_SnippetDeformableMesh:  clean_SnippetDeformableMesh_debug clean_SnippetDeformableMesh_checked clean_SnippetDeformableMesh_profile clean_SnippetDeformableMesh_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
