# Makefile generated by XPJ for LINUX64
-include Makefile.custom
ProjectName = SnippetVehicleScale
SnippetVehicleScale_cppfiles   += ./../../SnippetCommon/ClassicMain.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleScale/SnippetVehicleScale.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleScale/SnippetVehicleScaleRender.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicle4WCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleFilterShader.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleNoDriveCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleSceneQuery.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleTankCreate.cpp
SnippetVehicleScale_cppfiles   += ./../../SnippetVehicleCommon/SnippetVehicleTireFriction.cpp

SnippetVehicleScale_cpp_debug_dep    = $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_c_debug_dep      = $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_debug_dep      = $(SnippetVehicleScale_cpp_debug_dep) $(SnippetVehicleScale_cc_debug_dep) $(SnippetVehicleScale_c_debug_dep)
-include $(SnippetVehicleScale_debug_dep)
SnippetVehicleScale_cpp_checked_dep    = $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_c_checked_dep      = $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_checked_dep      = $(SnippetVehicleScale_cpp_checked_dep) $(SnippetVehicleScale_cc_checked_dep) $(SnippetVehicleScale_c_checked_dep)
-include $(SnippetVehicleScale_checked_dep)
SnippetVehicleScale_cpp_profile_dep    = $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_c_profile_dep      = $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_profile_dep      = $(SnippetVehicleScale_cpp_profile_dep) $(SnippetVehicleScale_cc_profile_dep) $(SnippetVehicleScale_c_profile_dep)
-include $(SnippetVehicleScale_profile_dep)
SnippetVehicleScale_cpp_release_dep    = $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_c_release_dep      = $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_release_dep      = $(SnippetVehicleScale_cpp_release_dep) $(SnippetVehicleScale_cc_release_dep) $(SnippetVehicleScale_c_release_dep)
-include $(SnippetVehicleScale_release_dep)
SnippetVehicleScale_debug_hpaths    := 
SnippetVehicleScale_debug_hpaths    += ./../../../Include
SnippetVehicleScale_debug_hpaths    += ./../../../../PxShared/include
SnippetVehicleScale_debug_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetVehicleScale_debug_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetVehicleScale_debug_lpaths    := 
SnippetVehicleScale_debug_lpaths    += ./../../../Lib/linux64
SnippetVehicleScale_debug_lpaths    += ./../../lib/linux64
SnippetVehicleScale_debug_lpaths    += ./../../../Bin/linux64
SnippetVehicleScale_debug_lpaths    += ./../../../../PxShared/lib/linux64
SnippetVehicleScale_debug_lpaths    += ./../../../../PxShared/bin/linux64
SnippetVehicleScale_debug_lpaths    += ./../../lib/linux64
SnippetVehicleScale_debug_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_debug_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_debug_defines   += RENDER_SNIPPET
SnippetVehicleScale_debug_defines   += _DEBUG
SnippetVehicleScale_debug_defines   += PX_DEBUG=1
SnippetVehicleScale_debug_defines   += PX_CHECKED=1
SnippetVehicleScale_debug_defines   += PX_SUPPORT_PVD=1
SnippetVehicleScale_debug_libraries := 
SnippetVehicleScale_debug_libraries += SnippetRenderDEBUG
SnippetVehicleScale_debug_libraries += SnippetUtilsDEBUG
SnippetVehicleScale_debug_libraries += PhysX3DEBUG_x64
SnippetVehicleScale_debug_libraries += PhysX3CookingDEBUG_x64
SnippetVehicleScale_debug_libraries += PhysX3CharacterKinematicDEBUG_x64
SnippetVehicleScale_debug_libraries += PhysX3ExtensionsDEBUG
SnippetVehicleScale_debug_libraries += PhysX3VehicleDEBUG
SnippetVehicleScale_debug_libraries += PxPvdSDKDEBUG_x64
SnippetVehicleScale_debug_libraries += PhysX3CommonDEBUG_x64
SnippetVehicleScale_debug_libraries += PxFoundationDEBUG_x64
SnippetVehicleScale_debug_libraries += PxTaskDEBUG
SnippetVehicleScale_debug_libraries += PsFastXmlDEBUG
SnippetVehicleScale_debug_libraries += SnippetUtilsDEBUG
SnippetVehicleScale_debug_libraries += SnippetRenderDEBUG
SnippetVehicleScale_debug_libraries += GL
SnippetVehicleScale_debug_libraries += GLU
SnippetVehicleScale_debug_libraries += glut
SnippetVehicleScale_debug_libraries += X11
SnippetVehicleScale_debug_libraries += rt
SnippetVehicleScale_debug_libraries += pthread
SnippetVehicleScale_debug_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_debug_common_cflags    += -MMD
SnippetVehicleScale_debug_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_debug_defines))
SnippetVehicleScale_debug_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_debug_hpaths))
SnippetVehicleScale_debug_common_cflags  += -m64
SnippetVehicleScale_debug_common_cflags  += -Werror -m64 -fPIC -msse2 -mfpmath=sse -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetVehicleScale_debug_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetVehicleScale_debug_common_cflags  += -Wno-uninitialized
SnippetVehicleScale_debug_common_cflags  += -g3 -gdwarf-2
SnippetVehicleScale_debug_cflags	:= $(SnippetVehicleScale_debug_common_cflags)
SnippetVehicleScale_debug_cppflags	:= $(SnippetVehicleScale_debug_common_cflags)
SnippetVehicleScale_debug_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_debug_lflags    += $(addprefix -L, $(SnippetVehicleScale_debug_lpaths))
SnippetVehicleScale_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_debug_libraries)) -Wl,--end-group
SnippetVehicleScale_debug_lflags  += -lrt
SnippetVehicleScale_debug_lflags  += -Wl,-rpath ./
SnippetVehicleScale_debug_lflags  += -m64
SnippetVehicleScale_debug_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_debug
SnippetVehicleScale_debug_cpp_o    = $(addprefix $(SnippetVehicleScale_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_debug_cc_o    = $(addprefix $(SnippetVehicleScale_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_debug_c_o      = $(addprefix $(SnippetVehicleScale_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_debug_obj      = $(SnippetVehicleScale_debug_cpp_o) $(SnippetVehicleScale_debug_cc_o) $(SnippetVehicleScale_debug_c_o)
SnippetVehicleScale_debug_bin      := ./../../../Bin/linux64/SnippetVehicleScaleDEBUG

clean_SnippetVehicleScale_debug: 
	@$(ECHO) clean SnippetVehicleScale debug
	@$(RMDIR) $(SnippetVehicleScale_debug_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_debug_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetVehicleScale/debug

build_SnippetVehicleScale_debug: postbuild_SnippetVehicleScale_debug
postbuild_SnippetVehicleScale_debug: mainbuild_SnippetVehicleScale_debug
	@cp -u "../../../../PxShared/bin/linux64/libPxFoundationDEBUG_x64.so" "../../../Bin/linux64/libPxFoundationDEBUG_x64.so"; cp -u "../../../../PxShared/bin/linux64/libPxPvdSDKDEBUG_x64.so" "../../../Bin/linux64/libPxPvdSDKDEBUG_x64.so"
mainbuild_SnippetVehicleScale_debug: prebuild_SnippetVehicleScale_debug $(SnippetVehicleScale_debug_bin)
prebuild_SnippetVehicleScale_debug:

$(SnippetVehicleScale_debug_bin): $(SnippetVehicleScale_debug_obj) build_SnippetRender_debug build_SnippetUtils_debug 
	mkdir -p `dirname ./../../../Bin/linux64/SnippetVehicleScaleDEBUG`
	$(CCLD) $(SnippetVehicleScale_debug_obj) $(SnippetVehicleScale_debug_lflags) -o $(SnippetVehicleScale_debug_bin) 
	$(ECHO) building $@ complete!

SnippetVehicleScale_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_debug_cpp_o): $(SnippetVehicleScale_debug_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	cp $(SnippetVehicleScale_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  rm -f $(SnippetVehicleScale_debug_DEPDIR).d

$(SnippetVehicleScale_debug_cc_o): $(SnippetVehicleScale_debug_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))))
	cp $(SnippetVehicleScale_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).debug.P; \
	  rm -f $(SnippetVehicleScale_debug_DEPDIR).d

$(SnippetVehicleScale_debug_c_o): $(SnippetVehicleScale_debug_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetVehicleScale_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	cp $(SnippetVehicleScale_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_debug_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  rm -f $(SnippetVehicleScale_debug_DEPDIR).d

SnippetVehicleScale_checked_hpaths    := 
SnippetVehicleScale_checked_hpaths    += ./../../../Include
SnippetVehicleScale_checked_hpaths    += ./../../../../PxShared/include
SnippetVehicleScale_checked_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetVehicleScale_checked_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetVehicleScale_checked_lpaths    := 
SnippetVehicleScale_checked_lpaths    += ./../../../Lib/linux64
SnippetVehicleScale_checked_lpaths    += ./../../lib/linux64
SnippetVehicleScale_checked_lpaths    += ./../../../Bin/linux64
SnippetVehicleScale_checked_lpaths    += ./../../../../PxShared/lib/linux64
SnippetVehicleScale_checked_lpaths    += ./../../../../PxShared/bin/linux64
SnippetVehicleScale_checked_lpaths    += ./../../lib/linux64
SnippetVehicleScale_checked_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_checked_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_checked_defines   += RENDER_SNIPPET
SnippetVehicleScale_checked_defines   += NDEBUG
SnippetVehicleScale_checked_defines   += PX_CHECKED=1
SnippetVehicleScale_checked_defines   += PX_SUPPORT_PVD=1
SnippetVehicleScale_checked_libraries := 
SnippetVehicleScale_checked_libraries += SnippetRenderCHECKED
SnippetVehicleScale_checked_libraries += SnippetUtilsCHECKED
SnippetVehicleScale_checked_libraries += PhysX3CHECKED_x64
SnippetVehicleScale_checked_libraries += PhysX3CookingCHECKED_x64
SnippetVehicleScale_checked_libraries += PhysX3CharacterKinematicCHECKED_x64
SnippetVehicleScale_checked_libraries += PhysX3ExtensionsCHECKED
SnippetVehicleScale_checked_libraries += PhysX3VehicleCHECKED
SnippetVehicleScale_checked_libraries += PxPvdSDKCHECKED_x64
SnippetVehicleScale_checked_libraries += PhysX3CommonCHECKED_x64
SnippetVehicleScale_checked_libraries += PxFoundationCHECKED_x64
SnippetVehicleScale_checked_libraries += PxTaskCHECKED
SnippetVehicleScale_checked_libraries += PsFastXmlCHECKED
SnippetVehicleScale_checked_libraries += SnippetUtilsCHECKED
SnippetVehicleScale_checked_libraries += SnippetRenderCHECKED
SnippetVehicleScale_checked_libraries += GL
SnippetVehicleScale_checked_libraries += GLU
SnippetVehicleScale_checked_libraries += glut
SnippetVehicleScale_checked_libraries += X11
SnippetVehicleScale_checked_libraries += rt
SnippetVehicleScale_checked_libraries += pthread
SnippetVehicleScale_checked_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_checked_common_cflags    += -MMD
SnippetVehicleScale_checked_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_checked_defines))
SnippetVehicleScale_checked_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_checked_hpaths))
SnippetVehicleScale_checked_common_cflags  += -m64
SnippetVehicleScale_checked_common_cflags  += -Werror -m64 -fPIC -msse2 -mfpmath=sse -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetVehicleScale_checked_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetVehicleScale_checked_common_cflags  += -Wno-uninitialized
SnippetVehicleScale_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetVehicleScale_checked_cflags	:= $(SnippetVehicleScale_checked_common_cflags)
SnippetVehicleScale_checked_cppflags	:= $(SnippetVehicleScale_checked_common_cflags)
SnippetVehicleScale_checked_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_checked_lflags    += $(addprefix -L, $(SnippetVehicleScale_checked_lpaths))
SnippetVehicleScale_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_checked_libraries)) -Wl,--end-group
SnippetVehicleScale_checked_lflags  += -lrt
SnippetVehicleScale_checked_lflags  += -Wl,-rpath ./
SnippetVehicleScale_checked_lflags  += -m64
SnippetVehicleScale_checked_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_checked
SnippetVehicleScale_checked_cpp_o    = $(addprefix $(SnippetVehicleScale_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_checked_cc_o    = $(addprefix $(SnippetVehicleScale_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_checked_c_o      = $(addprefix $(SnippetVehicleScale_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_checked_obj      = $(SnippetVehicleScale_checked_cpp_o) $(SnippetVehicleScale_checked_cc_o) $(SnippetVehicleScale_checked_c_o)
SnippetVehicleScale_checked_bin      := ./../../../Bin/linux64/SnippetVehicleScaleCHECKED

clean_SnippetVehicleScale_checked: 
	@$(ECHO) clean SnippetVehicleScale checked
	@$(RMDIR) $(SnippetVehicleScale_checked_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_checked_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetVehicleScale/checked

build_SnippetVehicleScale_checked: postbuild_SnippetVehicleScale_checked
postbuild_SnippetVehicleScale_checked: mainbuild_SnippetVehicleScale_checked
	@cp -u "../../../../PxShared/bin/linux64/libPxFoundationCHECKED_x64.so" "../../../Bin/linux64/libPxFoundationCHECKED_x64.so"; cp -u "../../../../PxShared/bin/linux64/libPxPvdSDKCHECKED_x64.so" "../../../Bin/linux64/libPxPvdSDKCHECKED_x64.so"
mainbuild_SnippetVehicleScale_checked: prebuild_SnippetVehicleScale_checked $(SnippetVehicleScale_checked_bin)
prebuild_SnippetVehicleScale_checked:

$(SnippetVehicleScale_checked_bin): $(SnippetVehicleScale_checked_obj) build_SnippetRender_checked build_SnippetUtils_checked 
	mkdir -p `dirname ./../../../Bin/linux64/SnippetVehicleScaleCHECKED`
	$(CCLD) $(SnippetVehicleScale_checked_obj) $(SnippetVehicleScale_checked_lflags) -o $(SnippetVehicleScale_checked_bin) 
	$(ECHO) building $@ complete!

SnippetVehicleScale_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_checked_cpp_o): $(SnippetVehicleScale_checked_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	cp $(SnippetVehicleScale_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  rm -f $(SnippetVehicleScale_checked_DEPDIR).d

$(SnippetVehicleScale_checked_cc_o): $(SnippetVehicleScale_checked_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))))
	cp $(SnippetVehicleScale_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).checked.P; \
	  rm -f $(SnippetVehicleScale_checked_DEPDIR).d

$(SnippetVehicleScale_checked_c_o): $(SnippetVehicleScale_checked_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetVehicleScale_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	cp $(SnippetVehicleScale_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_checked_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  rm -f $(SnippetVehicleScale_checked_DEPDIR).d

SnippetVehicleScale_profile_hpaths    := 
SnippetVehicleScale_profile_hpaths    += ./../../../Include
SnippetVehicleScale_profile_hpaths    += ./../../../../PxShared/include
SnippetVehicleScale_profile_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetVehicleScale_profile_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetVehicleScale_profile_lpaths    := 
SnippetVehicleScale_profile_lpaths    += ./../../../Lib/linux64
SnippetVehicleScale_profile_lpaths    += ./../../lib/linux64
SnippetVehicleScale_profile_lpaths    += ./../../../Bin/linux64
SnippetVehicleScale_profile_lpaths    += ./../../../../PxShared/lib/linux64
SnippetVehicleScale_profile_lpaths    += ./../../../../PxShared/bin/linux64
SnippetVehicleScale_profile_lpaths    += ./../../lib/linux64
SnippetVehicleScale_profile_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_profile_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_profile_defines   += RENDER_SNIPPET
SnippetVehicleScale_profile_defines   += NDEBUG
SnippetVehicleScale_profile_defines   += PX_PROFILE=1
SnippetVehicleScale_profile_defines   += PX_SUPPORT_PVD=1
SnippetVehicleScale_profile_libraries := 
SnippetVehicleScale_profile_libraries += SnippetRenderPROFILE
SnippetVehicleScale_profile_libraries += SnippetUtilsPROFILE
SnippetVehicleScale_profile_libraries += PhysX3PROFILE_x64
SnippetVehicleScale_profile_libraries += PhysX3CookingPROFILE_x64
SnippetVehicleScale_profile_libraries += PhysX3CharacterKinematicPROFILE_x64
SnippetVehicleScale_profile_libraries += PhysX3ExtensionsPROFILE
SnippetVehicleScale_profile_libraries += PhysX3VehiclePROFILE
SnippetVehicleScale_profile_libraries += PxPvdSDKPROFILE_x64
SnippetVehicleScale_profile_libraries += PhysX3CommonPROFILE_x64
SnippetVehicleScale_profile_libraries += PxFoundationPROFILE_x64
SnippetVehicleScale_profile_libraries += PxTaskPROFILE
SnippetVehicleScale_profile_libraries += PsFastXmlPROFILE
SnippetVehicleScale_profile_libraries += SnippetUtilsPROFILE
SnippetVehicleScale_profile_libraries += SnippetRenderPROFILE
SnippetVehicleScale_profile_libraries += GL
SnippetVehicleScale_profile_libraries += GLU
SnippetVehicleScale_profile_libraries += glut
SnippetVehicleScale_profile_libraries += X11
SnippetVehicleScale_profile_libraries += rt
SnippetVehicleScale_profile_libraries += pthread
SnippetVehicleScale_profile_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_profile_common_cflags    += -MMD
SnippetVehicleScale_profile_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_profile_defines))
SnippetVehicleScale_profile_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_profile_hpaths))
SnippetVehicleScale_profile_common_cflags  += -m64
SnippetVehicleScale_profile_common_cflags  += -Werror -m64 -fPIC -msse2 -mfpmath=sse -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetVehicleScale_profile_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetVehicleScale_profile_common_cflags  += -Wno-uninitialized
SnippetVehicleScale_profile_common_cflags  += -O3 -fno-strict-aliasing
SnippetVehicleScale_profile_cflags	:= $(SnippetVehicleScale_profile_common_cflags)
SnippetVehicleScale_profile_cppflags	:= $(SnippetVehicleScale_profile_common_cflags)
SnippetVehicleScale_profile_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_profile_lflags    += $(addprefix -L, $(SnippetVehicleScale_profile_lpaths))
SnippetVehicleScale_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_profile_libraries)) -Wl,--end-group
SnippetVehicleScale_profile_lflags  += -lrt
SnippetVehicleScale_profile_lflags  += -Wl,-rpath ./
SnippetVehicleScale_profile_lflags  += -m64
SnippetVehicleScale_profile_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_profile
SnippetVehicleScale_profile_cpp_o    = $(addprefix $(SnippetVehicleScale_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_profile_cc_o    = $(addprefix $(SnippetVehicleScale_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_profile_c_o      = $(addprefix $(SnippetVehicleScale_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_profile_obj      = $(SnippetVehicleScale_profile_cpp_o) $(SnippetVehicleScale_profile_cc_o) $(SnippetVehicleScale_profile_c_o)
SnippetVehicleScale_profile_bin      := ./../../../Bin/linux64/SnippetVehicleScalePROFILE

clean_SnippetVehicleScale_profile: 
	@$(ECHO) clean SnippetVehicleScale profile
	@$(RMDIR) $(SnippetVehicleScale_profile_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_profile_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetVehicleScale/profile

build_SnippetVehicleScale_profile: postbuild_SnippetVehicleScale_profile
postbuild_SnippetVehicleScale_profile: mainbuild_SnippetVehicleScale_profile
	@cp -u "../../../../PxShared/bin/linux64/libPxFoundationPROFILE_x64.so" "../../../Bin/linux64/libPxFoundationPROFILE_x64.so"; cp -u "../../../../PxShared/bin/linux64/libPxPvdSDKPROFILE_x64.so" "../../../Bin/linux64/libPxPvdSDKPROFILE_x64.so"
mainbuild_SnippetVehicleScale_profile: prebuild_SnippetVehicleScale_profile $(SnippetVehicleScale_profile_bin)
prebuild_SnippetVehicleScale_profile:

$(SnippetVehicleScale_profile_bin): $(SnippetVehicleScale_profile_obj) build_SnippetRender_profile build_SnippetUtils_profile 
	mkdir -p `dirname ./../../../Bin/linux64/SnippetVehicleScalePROFILE`
	$(CCLD) $(SnippetVehicleScale_profile_obj) $(SnippetVehicleScale_profile_lflags) -o $(SnippetVehicleScale_profile_bin) 
	$(ECHO) building $@ complete!

SnippetVehicleScale_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_profile_cpp_o): $(SnippetVehicleScale_profile_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	cp $(SnippetVehicleScale_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  rm -f $(SnippetVehicleScale_profile_DEPDIR).d

$(SnippetVehicleScale_profile_cc_o): $(SnippetVehicleScale_profile_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))))
	cp $(SnippetVehicleScale_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).profile.P; \
	  rm -f $(SnippetVehicleScale_profile_DEPDIR).d

$(SnippetVehicleScale_profile_c_o): $(SnippetVehicleScale_profile_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetVehicleScale_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	cp $(SnippetVehicleScale_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_profile_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  rm -f $(SnippetVehicleScale_profile_DEPDIR).d

SnippetVehicleScale_release_hpaths    := 
SnippetVehicleScale_release_hpaths    += ./../../../Include
SnippetVehicleScale_release_hpaths    += ./../../../../PxShared/include
SnippetVehicleScale_release_hpaths    += ./../../../../PxShared/src/foundation/include
SnippetVehicleScale_release_hpaths    += ./../../../../PxShared/src/fastxml/include
SnippetVehicleScale_release_lpaths    := 
SnippetVehicleScale_release_lpaths    += ./../../../Lib/linux64
SnippetVehicleScale_release_lpaths    += ./../../lib/linux64
SnippetVehicleScale_release_lpaths    += ./../../../Bin/linux64
SnippetVehicleScale_release_lpaths    += ./../../../../PxShared/lib/linux64
SnippetVehicleScale_release_lpaths    += ./../../../../PxShared/bin/linux64
SnippetVehicleScale_release_lpaths    += ./../../lib/linux64
SnippetVehicleScale_release_defines   := $(SnippetVehicleScale_custom_defines)
SnippetVehicleScale_release_defines   += PHYSX_PROFILE_SDK
SnippetVehicleScale_release_defines   += RENDER_SNIPPET
SnippetVehicleScale_release_defines   += NDEBUG
SnippetVehicleScale_release_defines   += PX_SUPPORT_PVD=0
SnippetVehicleScale_release_libraries := 
SnippetVehicleScale_release_libraries += SnippetRender
SnippetVehicleScale_release_libraries += SnippetUtils
SnippetVehicleScale_release_libraries += PhysX3_x64
SnippetVehicleScale_release_libraries += PhysX3Cooking_x64
SnippetVehicleScale_release_libraries += PhysX3CharacterKinematic_x64
SnippetVehicleScale_release_libraries += PhysX3Extensions
SnippetVehicleScale_release_libraries += PhysX3Vehicle
SnippetVehicleScale_release_libraries += PxPvdSDK_x64
SnippetVehicleScale_release_libraries += PhysX3Common_x64
SnippetVehicleScale_release_libraries += PxFoundation_x64
SnippetVehicleScale_release_libraries += PxTask
SnippetVehicleScale_release_libraries += PsFastXml
SnippetVehicleScale_release_libraries += SnippetUtils
SnippetVehicleScale_release_libraries += SnippetRender
SnippetVehicleScale_release_libraries += GL
SnippetVehicleScale_release_libraries += GLU
SnippetVehicleScale_release_libraries += glut
SnippetVehicleScale_release_libraries += X11
SnippetVehicleScale_release_libraries += rt
SnippetVehicleScale_release_libraries += pthread
SnippetVehicleScale_release_common_cflags	:= $(SnippetVehicleScale_custom_cflags)
SnippetVehicleScale_release_common_cflags    += -MMD
SnippetVehicleScale_release_common_cflags    += $(addprefix -D, $(SnippetVehicleScale_release_defines))
SnippetVehicleScale_release_common_cflags    += $(addprefix -I, $(SnippetVehicleScale_release_hpaths))
SnippetVehicleScale_release_common_cflags  += -m64
SnippetVehicleScale_release_common_cflags  += -Werror -m64 -fPIC -msse2 -mfpmath=sse -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetVehicleScale_release_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetVehicleScale_release_common_cflags  += -Wno-uninitialized
SnippetVehicleScale_release_common_cflags  += -O3 -fno-strict-aliasing
SnippetVehicleScale_release_cflags	:= $(SnippetVehicleScale_release_common_cflags)
SnippetVehicleScale_release_cppflags	:= $(SnippetVehicleScale_release_common_cflags)
SnippetVehicleScale_release_lflags    := $(SnippetVehicleScale_custom_lflags)
SnippetVehicleScale_release_lflags    += $(addprefix -L, $(SnippetVehicleScale_release_lpaths))
SnippetVehicleScale_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetVehicleScale_release_libraries)) -Wl,--end-group
SnippetVehicleScale_release_lflags  += -lrt
SnippetVehicleScale_release_lflags  += -Wl,-rpath ./
SnippetVehicleScale_release_lflags  += -m64
SnippetVehicleScale_release_objsdir  = $(OBJS_DIR)/SnippetVehicleScale_release
SnippetVehicleScale_release_cpp_o    = $(addprefix $(SnippetVehicleScale_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetVehicleScale_cppfiles)))))
SnippetVehicleScale_release_cc_o    = $(addprefix $(SnippetVehicleScale_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetVehicleScale_ccfiles)))))
SnippetVehicleScale_release_c_o      = $(addprefix $(SnippetVehicleScale_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetVehicleScale_cfiles)))))
SnippetVehicleScale_release_obj      = $(SnippetVehicleScale_release_cpp_o) $(SnippetVehicleScale_release_cc_o) $(SnippetVehicleScale_release_c_o)
SnippetVehicleScale_release_bin      := ./../../../Bin/linux64/SnippetVehicleScale

clean_SnippetVehicleScale_release: 
	@$(ECHO) clean SnippetVehicleScale release
	@$(RMDIR) $(SnippetVehicleScale_release_objsdir)
	@$(RMDIR) $(SnippetVehicleScale_release_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetVehicleScale/release

build_SnippetVehicleScale_release: postbuild_SnippetVehicleScale_release
postbuild_SnippetVehicleScale_release: mainbuild_SnippetVehicleScale_release
	@cp -u "../../../../PxShared/bin/linux64/libPxFoundation_x64.so" "../../../Bin/linux64/libPxFoundation_x64.so"; cp -u "../../../../PxShared/bin/linux64/libPxPvdSDK_x64.so" "../../../Bin/linux64/libPxPvdSDK_x64.so"
mainbuild_SnippetVehicleScale_release: prebuild_SnippetVehicleScale_release $(SnippetVehicleScale_release_bin)
prebuild_SnippetVehicleScale_release:

$(SnippetVehicleScale_release_bin): $(SnippetVehicleScale_release_obj) build_SnippetRender_release build_SnippetUtils_release 
	mkdir -p `dirname ./../../../Bin/linux64/SnippetVehicleScale`
	$(CCLD) $(SnippetVehicleScale_release_obj) $(SnippetVehicleScale_release_lflags) -o $(SnippetVehicleScale_release_bin) 
	$(ECHO) building $@ complete!

SnippetVehicleScale_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetVehicleScale_release_cpp_o): $(SnippetVehicleScale_release_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))))
	cp $(SnippetVehicleScale_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cppfiles))))).P; \
	  rm -f $(SnippetVehicleScale_release_DEPDIR).d

$(SnippetVehicleScale_release_cc_o): $(SnippetVehicleScale_release_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetVehicleScale_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))))
	cp $(SnippetVehicleScale_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_ccfiles))))).release.P; \
	  rm -f $(SnippetVehicleScale_release_DEPDIR).d

$(SnippetVehicleScale_release_c_o): $(SnippetVehicleScale_release_objsdir)/%.o:
	$(ECHO) SnippetVehicleScale: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetVehicleScale_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))))
	cp $(SnippetVehicleScale_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetVehicleScale_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetVehicleScale/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetVehicleScale_release_objsdir),, $@))), $(SnippetVehicleScale_cfiles))))).P; \
	  rm -f $(SnippetVehicleScale_release_DEPDIR).d

clean_SnippetVehicleScale:  clean_SnippetVehicleScale_debug clean_SnippetVehicleScale_checked clean_SnippetVehicleScale_profile clean_SnippetVehicleScale_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
